### ISSUE TITLE
[ps vita] Menu Scale Factor -> GPU Crash

### ISSUE THREAD

**Issue by liz-desartiges** [libretro/RetroArch#10456]
## Description

When changing Menu Scale Factor the GPU crash 

### Steps to reproduce the bug

1. Go to User Interface -> Appearance -> Menu Scale Factor
2. Change this settings
3. Your screen is now stucked or you get a Message "GPU Driver detects GPU Crash"

- RetroArch: 1.8.5

### Environment information

- OS: ps vita
Driver : vita2d
[GPUCRASH.tar.gz](https://github.com/libretro/RetroArch/files/4485626/GPUCRASH.tar.gz)

**Comment by Calistex** [comment]
I tried to reproduce this on 1.10.0, selecting different values, didn't get any crash, it freezes for like 2 seconds and then the setting is correctly changed, so I guess it is fixed.

**Comment by winstoncooke** [comment]
> I tried to reproduce this on 1.10.0, selecting different values, didn't get any crash, it freezes for like 2 seconds and then the setting is correctly changed, so I guess it is fixed.

I am still having this problem on 1.10.2.

I'm repeating the steps to reproduce by OP. It displays a message stating:
```
An error has occurred.
The PS Vita system will be powered off.
```
The system then shuts down, leaving me unable to change the UI scale.

**Comment by zoltanvb** [comment]
Could not reproduce with 1.20.0.
