### ISSUE TITLE
Controllers Not Reusing Ports

### ISSUE THREAD

**Issue by nickp85** [libretro/RetroArch#11294]
Device: Nvidia Shield 2017
Controller: PS4 DualShock
Version: 9/6 nightly

When I am using this controller via Bluetooth to the Shield, if it disconnects for any reason while RetroArch is running then reconnects, it's added as a second port instead of reconnecting to port 1. This leaves RetroArch in an unusable state requiring a force close and relaunch since the controller in port 1 is dead and no way to reconnect it.

**Comment by hizzlekizzle** [comment]
This is known. IIRC, it has to do with the OS/driver not reporting disconnections, so RetroArch doesn't know it ever happened and when it reconnects, it looks like another identical controller.

You shouldn't need to completely force quit, though. Just going out to the homescreen and then reopening the program should do the trick in most cases.

**Comment by nickp85** [comment]
@hizzlekizzle if that's the case, then I'd really like to get 11296 fixed because backgrounding the app and then reopening it while Duckstation is running a game is an immediate crash

**Comment by danbo** [comment]
See #3414 and #6707, also https://forums.libretro.com/t/problem-with-controller-port-assignment-auto-incrementation/14289

I'm sure there are more...

1. In the base of a bluetooth controller, is it not possible to lock a port to the bt mac address?
2. Perhaps it would be helpful to also split out / lock a device for menu / navigation, because it looks like devices are fighting for port 1 to control the menu. This way if a device moves to another port, it doesn't matter because that device is also intended dedicated for menu control.

**Comment by twinaphex** [comment]
Fixed according to @ComradeEcho

**Comment by KodiKaiju** [comment]
I am still having this issue running Retroarch on Chromecast with Google TV.

**Comment by ComradeEcho** [comment]
> I am still having this issue running Retroarch on Chromecast with Google TV.

Which controller/input driver is being used on your setup?

**Comment by KodiKaiju** [comment]
> > I am still having this issue running Retroarch on Chromecast with Google TV.
> 
> Which controller/input driver is being used on your setup?

I am using an Xbox Wireless Controller (2020). Input driver is "android". 
Thank you for replying ComradeEcho! Your work and skills are amazing.

**Comment by ComradeEcho** [comment]
Thanks - I thought this issue was only affecting the HID driver

I'll try to get this going on an android setup and see what I can see

**Comment by aairey** [comment]
Still an issue today with Android 13, latest retroarch and an 8bitdo Pro 2 Bluetooth controller.

Easy to reproduce:
1. Start any game
2. Let the controller go to sleep
3. Start up the controller again, and it will connect on Port #2.
