### ISSUE TITLE
[Android] Android 11/12 Scoped Storage updates prevent RA from using USB or network directories

### ISSUE THREAD

**Issue by sage2050** [libretro/RetroArch#13493]
## Description

I'm not an android dev but fix looks pretty simple
https://developer.android.com/about/versions/11/privacy/storage

### Expected behavior

User should be able to set directories outside of RA app

### Actual behavior

User can't use directories outside of RA app

### Steps to reproduce the bug

1. Launch RA
2. Try to change a folder directory. Scoped storage only allowed the app to see its own files without special permissions.

### Bisect Results

started happening immediately after android 11 update.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.14

### Environment information

- OS: Android TV (Android 11)

**Comment by janlugt** [comment]
I think this has been fixed by https://github.com/libretro/RetroArch/pull/13615.

**Comment by LuanVSO** [comment]
Not fixed, the path to the drive will be listed but retroarch will not see the files inside it
![Screenshot_20230417_124509_ZArchiver.png](https://user-images.githubusercontent.com/43626415/232544679-1b21fd44-abfb-4ad6-a05e-88f15a71dc5d.png)

**Comment by xTMODx** [comment]
I can confirm the issue, I can see the storage (external SSD) but when I open it in RetroArch no subfolder are shown. Total Commander show the drive and I can see the content
