### ISSUE TITLE
'Analog to Digital' Remap Not Saving

### ISSUE THREAD

**Issue by mediamoshpit** [libretro/RetroArch#13817]
## Description

The 'Analog to Digital Type' setting is not being saved alongside other remap settings.

### Expected behavior

For the user selection to persist between sessions.

### Actual behavior

The selection always reverts back to 'none'

### Steps to reproduce the bug

1. Select any 'Analog to to Digital Type' option other than the default 'none'.
2. Close content.
3. Relaunch content associated with the sectioning and check 'controls' menu to see if selection persists.

### Version/Commit

- RetroArch: 1.10.2

### Environment information

- OS: Linux (v5.10) - Lakka 4.0 RPi4b
- Git: de4e56e
- Compiler: GCC (10.2.0) 64-bit

**Comment by GABO1423** [comment]
Duplicate of #13768.

**Comment by mediamoshpit** [comment]
The thing is, I do have exististing remap files and the setting is still not being saved. Perhaps this is only in Lakka?

**Comment by jdgleaver** [comment]
Whoops... This was something of an edge case that I didn't notice before, since the bug only manifests when configuration overrides are active...

This should fix the issue: https://github.com/libretro/RetroArch/pull/13824

**Comment by mediamoshpit** [comment]
@jdgleaver I may be wrong, but this behavior seems to still exist when saving a 'content directory' remap. All other instances seem fine. Could you double check me on that?

**Comment by jdgleaver** [comment]
@mediamoshpit It's working fine for me. It uses the same code path regardless of the remap type, so there should be no difference between them...
