### ISSUE TITLE
[Windows] Save state thumbnail not showing on load

### ISSUE THREAD

**Issue by askotx** [libretro/RetroArch#14603]
## Description

On initial load, if I get a previous save state, it doesn't show on GUI

### Expected behavior

It should display available save state thumnail

### Actual behavior

It "detects" a previous thumbnail, because it shows "Press Y to show save state thumbnail in fullscreen mode" message on low bar

### Steps to reproduce the bug

1. Load a game via command line, in my case by a front end, that has a save state thumbnail
2. It doesn't display any thumbnail

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
-1.10.0 ~ got this issue
-1.11.0 ~ also
-1.12.0 ~ still same

### Environment information

OS: Win 10 22H2 and previous
GPU: Nvidia GT 1030 
GPU driver: 526.47 and previous
CPU: i5-3570S
RAM: 8GB DDR3

I've attached a pair of images that shows this current behavior, retroarch detects previous save state thumbnail, but doesn't show content, next image and after I updated a new save state thumbnail and it show it correctly
![IMG_20221107_184512](https://user-images.githubusercontent.com/2125887/200462496-40a8ea7a-5c18-41bc-82e3-f096bc3b4615.jpg)
![IMG_20221107_185032](https://user-images.githubusercontent.com/2125887/200462502-6b6243fe-268e-4791-a30b-249a15916bec.jpg)

**Comment by sonninnos** [comment]
I can't reproduce no matter how the content is launched.

Ozone didn't even have savestate thumbnails until 1.11.0.

**Comment by askotx** [comment]
Then my bad about version, but if you watch on first picture, it shows save state slot 1 and in the bottom text [Fullscreen thumbnail] and it display that label when a thumbnail is available, let me test it more please

**Comment by sonninnos** [comment]
Sure, that shouldn't be possible, since the footer label relies on the existence of the file..

**Comment by askotx** [comment]
I've added two videos to show issues, first one was on load after waking up pc, but I forget to start recording before that, sorry: 
https://youtu.be/JJiNddmu5xg

Second one:
I've started from a front-end, then start a game, try to display actual save states, enable retroachievements, restart content and voila, no thumbnail
https://youtu.be/DdYvrf2LxYo

**Comment by sonninnos** [comment]
I tried following the steps but can't reproduce. First I assumed it might somehow be because you went from the playlist Quick Menu back to Quick Menu under Main Menu, but nope, still works here.

**Comment by askotx** [comment]
Maybe, it could be related to enable  Retroachievements then Restart game, that's when it happens for sure

**Comment by sonninnos** [comment]
Tried that, no difference.

**Comment by LibretroAdmin** [comment]
Is this issue fixed now?

**Comment by sonninnos** [comment]
Beats me, but sure would like to be able to trigger it.

**Comment by askotx** [comment]
@LibretroAdmin, it's not fixed, but it couldn't be reproduced too.

When it happens, it does on mupen64plus-next with vulkan driver and all parallel components selected

**Comment by sonninnos** [comment]
The menu code has nothing to do with cores. So it does not happen with any other video driver and any other core then? I tested with Mupen64, Vulkan, and Parallel, and it behaved just like any other core here.

**Comment by askotx** [comment]
I just tested with mupen64plus core, last version was 1.12.0~ and previous, also I haven't tested with opengl, any other core or version 1.13.0, but I closed this issue because isn't reproducible
