### ISSUE TITLE
Lost menu visibility to “Update Core Info Files” in the online updater menu in iOS/GLUI

### ISSUE THREAD

**Issue by trotsky40** [libretro/RetroArch#14794]
Between the 12/22 nightly IPA and 12/23 nightly IPA, there is no longer access to update core info files in the online updated menu using GLUI on iOS. 

12/22 nightly:
![25AA6CEC-3EEA-45B0-9E2C-A265A02243DE](https://user-images.githubusercontent.com/25250513/210198711-929d2a34-2aea-4103-8bfe-91ef0b69a2f1.png)

12/23 nightly:
![227E50C4-02F7-4664-98C8-4B0078A0B798](https://user-images.githubusercontent.com/25250513/210198734-f2e4398b-679a-4645-a71c-501faea3d3c2.png)

**Comment by gouchi** [comment]
This [PR](https://github.com/libretro/RetroArch/pull/14796) should fix this issue.

**Comment by trotsky40** [comment]
Not fixed on the most recent build available on buildbot. I will check again with later builds.

**Comment by trotsky40** [comment]
I don't think https://github.com/libretro/RetroArch/pull/14796 fixed the issue. Still seeing the same behaviour in the most recent builds.

**Comment by gouchi** [comment]
Which iOS version are you running as the change is only for :

https://github.com/libretro/RetroArch/tree/master/pkg/apple/RetroArch_iOS11_Metal.xcodeproj

**Comment by trotsky40** [comment]
I am testing on both an iPhone 12 and M2 iPad Pro, both running the latest iOS (16.2). I am using the iOS-arm64 build from buildbot http://buildbot.libretro.com/nightly/apple/ios-arm64/

**Comment by gouchi** [comment]
I don't know well iOS builds but `ios-arm64` should be using `RetroArch_iOS11_Metal.xcodeproj` according to the [CI](https://github.com/libretro/RetroArch/blob/master/.gitlab-ci.yml#L390-L404).

**Comment by gouchi** [comment]
It should be ok for iOS with this [PR](https://github.com/libretro/RetroArch/pull/14811) the other one was for [tvOS only](https://github.com/libretro/RetroArch/pull/14796).

**Comment by trotsky40** [comment]
Appears to have been resolved by: https://github.com/libretro/RetroArch/commit/1bd3e32ad75496c5c12775dc261c0e909e10c6cb
