### ISSUE TITLE
RetroArch Android 1.16.0 stable build - Problem Touchscreen Menu

### ISSUE THREAD

**Issue by master1274** [libretro/RetroArch#15812]
On version 1.16.0 and current nightly builds, calling the menu using the on-screen layer is broken. Impossible to use normally. Constant false positives. Link to video with problem https://drive.google.com/file/d/1gj33dHIYKqPH6TPYnpjzWK8rlH_xMBEF/view?usp=drivesdk

**Comment by master1274** [comment]
The problem is common. Not localized to certain devices and versions of Android.

**Comment by Barozzu** [comment]
I confirm the problem. Since version 1.16.0, the touch menu button behaves inadequately.

**Comment by master1274** [comment]
Yes. Already fixed in the current nightly build

**Comment by 6lackmag3** [comment]
@sonninnos I must admit that bug persists in 1.16.0 stable builds available on buildbot.

**Comment by master1274** [comment]
Reopen until fixed in stable release

**Comment by sonninnos** [comment]
But that is how it always is..

**Comment by sonninnos** [comment]
Closing since new stable is out.
