### ISSUE TITLE
Retroarch is unable to hash PSP CHDs converted with the "createdvd" option (correct option for iso files)

### ISSUE THREAD

**Issue by trotsky40** [libretro/RetroArch#16145]
## Description

Retroarch is able to run PSP titles that have been converted to the CHD with the "createdvd". However, they are not hashed correctly to activate RetroAchievements. This error is generated in the log: "[INFO] [RCHEEVOS]: RetroAchievements game load failed: hash generation failed" (full log attached). 

### Expected behavior

CHDs for PSP titles should run and activate RetroAchievements. 

### Actual behavior

CHDs created with "createdvd" run but do not activate RetroAchievements. 

### Steps to reproduce the bug

1. Update Retroarch and PPSSPP core to the latest versions. 
2. Run a PSP title in CHD format created with "createdvd" 
3. RetroAchievements do not activate and give an error. 

### Bisect Results

This has happened in RetroArch since CHD support was added to the PPSSPP core. Standalone PPSSPP does not have this issue (it properly hashes the CHD files).  

### Version/Commit
You can find this information under Information/System Information

-  RetroArch 1.16.0 (Git 72c901a)
- Core version: PPSSPP v1.16.6-156-g5de1a5f

### Environment information
[retroarch__2024_01_20__10_07_36.log](https://github.com/libretro/RetroArch/files/13998839/retroarch__2024_01_20__10_07_36.log)

- OS: Windows 10 22H2 (also see the same behavior on iOS and SteamOS)
- Compiler: N/A. Sourced from the buildbot

**Comment by Jamiras** [comment]
lbchdr, which RetroArch uses to read CHDs doesn't support dvd format yet: https://github.com/rtissera/libchdr/issues/101#issuecomment-1653233362

Additionally, the version of libchdr inluded in RetroArch is significantly out of date.

**Comment by SiriusVI87** [comment]
I'm having the same issue. Retroarch actually launches the chd files created with "createdvd", but I get the hash error. Everything works with the "wrong" createcd setting.

**Comment by derVedro** [comment]
Issue completed - is it safe to assume that this problem will be solved after some time in the near future?

**Comment by trotsky40** [comment]
It is already solved if you are using the nightly version.

**Comment by lazepeda01** [comment]
The fix in #18040 appears to be incomplete. PS2 createdvd CHDs still fail 
to hash on the latest RetroArch with the LRPS2 core.

Confirmed on RetroArch 1.22.2 with Shrek 2 (USA).chd:
- chdman info shows: Version 5, unitbytes=2048, Tag='DVD ', zstd compression
- RetroArch log shows: hash generation failed
- Independent tool using libchdr produces the correct hash: 3d9206a51e2ab540c3c0f344cd30520d
- The same hash matches the registered RA checksum on the Shrek 2 achievement page
- The game runs and plays correctly; the failure is purely in the hashing layer

The bug also appears inconsistent, as some createdvd PS2 CHDs hash correctly 
while others with identical chdman info output do not.

**Comment by spaceage64** [comment]
> The fix in [#18040](https://github.com/libretro/RetroArch/pull/18040) appears to be incomplete. PS2 createdvd CHDs still fail to hash on the latest RetroArch with the LRPS2 core.
> 
> Confirmed on RetroArch 1.22.2 with Shrek 2 (USA).chd:
> 
> * chdman info shows: Version 5, unitbytes=2048, Tag='DVD ', zstd compression
> * RetroArch log shows: hash generation failed
> * Independent tool using libchdr produces the correct hash: 3d9206a51e2ab540c3c0f344cd30520d
> * The same hash matches the registered RA checksum on the Shrek 2 achievement page
> * The game runs and plays correctly; the failure is purely in the hashing layer
> 
> The bug also appears inconsistent, as some createdvd PS2 CHDs hash correctly while others with identical chdman info output do not.

I think this is not the correct place to mention this as this thread seems to be concerned with PSP games only?

**Comment by lazepeda01** [comment]
I understand where you're coming from, but I believe the issue stems from the same place and doesn't just affect PSP games, but any files made with createdvd. I thought it might be more useful to bring it back to this issue with relevant history rather than create some bloat with another separate issue containing the same information.
