### ISSUE TITLE
G-Sync support

### ISSUE THREAD

**Issue by nfp0** [libretro/RetroArch#1633]
Regarding the support of variable refresh rate systems like G-Sync or Freesync.
Is RetroArch supposed to work correctly with them?

I have a G-Sync capable monitor, and from my tests, it seems RetroArch is not taking advantage of G-Sync appropriately.

I understand RetroArch utilizes Dynamic Rate Control to sync the video rendering to the reported monitor frequency. For this to work, say, on a 60Hz screen, a 60.01hz game is slowed down to 60hz, and games that run at significantly different fps cannot correctly take advantage of Dynamic Rate Control.
With G-Sync, the emulator doesn't have to sync the video and a 60.01hz game will display at the exact 60.01hz on the monitor. A 50Hz game will display at 50Hz. A 75Hz game will display at 75Hz, etc.
Now that variable refresh rate systems are a reality, why can't RetroArch leverage this advantage? For this to work, theoretically I would just need to disable V-Sync on the emulator settings and the driver would take care of syncronizing the monitor to the precise frequency that RetroArch is outputting, making for a perfect, non-stuttering, non-tearing, non-input-laggy experience.

I've tried many different configurations on RetroArch with the BSNES core, and I can't seem to get it to work. I always get video stuttering. With the monitor set at a maximum of 60Hz it seems to work correctly, but this nullifies the advantage of the 120Hz reduced input lag. Turning on the black frame insertion also solves the problem, but I don't want to use black frame insertion and that also introduces input lag.

I would greatly appreciate if anyone looked at this issue.
Thanks.

**Comment by hizzlekizzle** [comment]
I believe the way to do it is to disable vsync and make sure audio sync is on (that is, block on audio rather than video). You might try reducing the audio latency, as well.

**Comment by twinaphex** [comment]
Ask @ToadKing, he owns a G-Sync monitor and has used it successfully with RetroArch before.

He can explain to you which settings to enable/disable.

**Comment by BlueNinja0** [comment]
@hizzlekizzle That solution makes sense, but I've searched for the audio sync option and I can't find it anywhere.

@twinaphex  Thanks, I've sent him an email.

**Comment by twinaphex** [comment]
> @hizzlekizzle That solution makes sense, but I've searched for the audio sync option and I can't find it anywhere.

Go to Settings -> Audio Settings, it should be there.

**Comment by aliaspider** [comment]
it is hidden by default I think, so enable advanced settings first :
``settings`` -> ``menu settings`` -> ``show advanced settings``

**Comment by BlueNinja0** [comment]
@twinaphex Are you referring to the "Audio sync enable" option? If so, it was already enabled by default. Or is it another option?

**Comment by Awakened0** [comment]
My 120hz monitor doesn't have GSync, but changing Vsync Swap Interval to 2 fixes the stutter at that refresh rate for me.

**Comment by BlueNinja0** [comment]
@Awakened0 I tried that before and it also works for me (only if I also enable Hard GPU Sync though), but I wanted to take advantage of the perfect uncompromised sync that G-Sync allows.

**Comment by BlueNinja0** [comment]
@Awakened0 No, the thing is: Just disabling VSync is precisely what should make it work. G-Sync is doing it's job because I don't get any screen tearing even with V-Sync off, but RetroArch doesn't seem to be outputting frames in a smooth manner.
Both RetroArch and FRAPS report that it's outputting 60fps, which is correct. I'm clueless as to what might be missing and why the hell does it work fine when I enable black frame insertion.

**Comment by Awakened0** [comment]
I mean that the swap interval setting only applies when Vsync is enabled in RetroArch. Maybe if it was possible to use swap interval 2 with Vsync off it would fix your stuttering while maintaining Gsync.

**Comment by aliaspider** [comment]
what problems are you having with vsync off and audio sync on ? stuttering ? 
you can try to use the "limit maximum runspeed" option in general settings to use a cpu timer instead, try with both audio sync on and off and see if that helps.

**Comment by BlueNinja0** [comment]
@Awakened0 Yes, it would be useful if swap interval 2 also worked with V-Sync off. That way we could duplicate frames independently of V-Sync being on or not. Useful for 120hz monitors.

@aliaspider The problem is stuttering yes. I've disabling disabling "audio sync" and the game ran at a much faster speed, obviously. Activating the "limit maximum runspeed" restored the speed to normal levels, but the stuttering came back. Not as much, but it's still there.
When I disable G-Sync and use "audio sync" + V-Sync + "hard gpu sync", it's 100% smooth, it never ever stutters.
Disabling audio sync and enabling the cpu timer made all the sense, so why is there still some stuttering remaining? It should be perfect with that configuration you suggested. : /

**Comment by aliaspider** [comment]
cool !
did you also test cores running at 50fps? because that is the most interesting use case for g-sync, and you would also be able to see clearly if there is a difference to normal v-sync, assuming of course that g-sync does work as advertised.

**Comment by BlueNinja0** [comment]
I haven't tested it out yet, but I'm also curious about that!
Care to recommend me a core and ROM for me to test out?

**Comment by aliaspider** [comment]
any core that supports PAL would work.

**Comment by BlueNinja0** [comment]
Okay, I have partial success on the 50Hz front.
With V-Sync we have the usual horrible micro-stuttering associated with playing a 50Hz game on a 60Hz screen (or 120Hz in this case). But as soon as I use the G-Sync method I posted above, the micro-stuttering is gone! G-Sync automatically sets the monitor for 50Hz refresh and the motion is mostly fluid, like on old PAL TVs.

I say mostly because another, more random, kind of stuttering was introduced, more akin to the inconstant stuttering I was experiencing before I was using "Hard GPU Sync" even on 60Hz games. It was bearable IMO, but it's strange that I can't achieve the perfect 100% smoothness I managed to get on the 60Hz games. Regardless, the improvement between V-Sync and G-Sync on the 50Hz games is night and day. The micro-stuttering is completely eliminated.
My CPU is an i5 3570K overclocked to 4.5Ghz, so I think that's not the problem, even though I used bsnes's core. But maybe someone with different hardware should give it a try.

Another peculiar thing I found is that, when on a PAL game and on the settings for G-Sync I listed on my other post, if I use the "save state" option from the menu, the game accelerates to 60Hz instead of 50Hz, and the sound is gone. The emulator has to be restarted to get the normal behavior again. Weird...

**Comment by ToadKing** [comment]
G-Sync should work under the correct conditions.

* V-Sync and audio sync should both be on. When this is off you technically aren't using G-sync and tearing is possible
* Exclusive fullscreen mode should be enabled
* Audio rate control should be disabled

**Comment by BlueNinja0** [comment]
@ToadKing I think you're wrong about G-Sync. V-Sync should be turned off. It's not possible to have screen tearing with G-Sync because only full frames are drawn. That's it's sole purpose, to eliminate screen tearing without the need to synchronize an application to the screen's Hz.

You can easily test this with any fullscreen application.

**Comment by ToadKing** [comment]
Actually I was reading some things wrong. V-Sync is just stubbed out when G-Sync is enabled so it shouldn't have any effect being on or off. Sorry about that.

**Comment by BlueNinja0** [comment]
Yes, usually there is no consequence of having V-Sync on with G-Sync, but in some cases, depending on the application, you might be introducing V-Sync related input lag, without any advantage. Therefore it is recommended to always disable V-Sync on all applications when using G-Sync, just to make sure.

**Comment by BlueNinja0** [comment]
Sorry for double-post, but can anyone tell me why do I need "hard GPU sync" for G-Sync to work correctly and eliminate the random stutter?

What does "hard GPU sync" do exactly, and why leaving it disabled causes so much random stutter in my G-Sync setup described in my post above?

**Comment by Awakened0** [comment]
That option is meant to reduce video latency (input lag) caused by video driver buffering. Maister describes the feature in the input latency section here: https://github.com/libretro/RetroArch/wiki/Getting-optimal-vsync-performance

So it's something you'd want on anyways as long as your CPU can handle it. I'm not sure why having it on would help with G-Sync. Seems like a nice side effect :)

**Comment by BlueNinja0** [comment]
Yeah, I've read that. I understand it reduces input lag, but it makes no sense that having it disabled causes big random stuttering in G-Sync.

Also, I'm worried about the partial success of G-Sync on 50Hz PAL games. The random stuttering occurs even with "hard GPU sync" on. I would like to call the developer's attention to this issue, considering G-Sync and FreeSync seem to be the holy grail solution for emulation with perfect sync, independently of frequency.

**Comment by twinaphex** [comment]
Did you really turn off rate control? Rate Control Delta needs to be set to 0.0 otherwise its not disabled and still active.

**Comment by BlueNinja0** [comment]
I assume you're talking about this option?
![retroarch audio options](https://cloud.githubusercontent.com/assets/11202422/7370774/516dd13c-edb4-11e4-8284-3c26ca465ada.PNG)

Indeed I didn't have it on 0.000. I thought I just had to disable "Audio sync enable" and it would be enough. But now I've also set "Audio rate control delta" to 0.000 and the same issue persists. 50Hz has a stutter every 2 or so seconds, but it's not constant. It's random.

Another question: Is the "Refresh rate" setting on the video settings relevant in my situation where I have V-Sync and audio sync off?

**Comment by twinaphex** [comment]
Yes, that's the setting I mean.

In any case, I don't have any G-Sync monitor, only ToadKing does. RetroArch certainly wasn't made with it in mind back when the A/V syncing system was being written.

I dunno if @Themaister can still respond to technical questions like this but he'd be your best bet.

**Comment by BlueNinja0** [comment]
@twinaphex Of course. That is understandable. Variable refresh rate monitors weren't even on the horizon. But theoretically, G-Sync does not need support from the application level. It's application agnostic. Any dedicated fullscreen application takes advantage of the variable refresh rate.

What I find weird is the fact that it works perfectly at 60Hz and stutters a lot at 50Hz on RetroArch (not the expected 50Hz microstutter, mind you). Also weird is the fact that I needed to activate "Hard GPU Sync" for it to be smooth.

I'm not even planning on playing any 50Hz games, but I love this project and I want to report and test what I can, since there seems to be little people using RetroArch with variable frame rate monitors yet, which are of special relevance for the emulation scene.

**Comment by twinaphex** [comment]
>  But theoretically, G-Sync does not need support from the application level. It's application agnostic. Any dedicated fullscreen application takes advantage of the variable refresh rate.

**Comment by twinaphex** [comment]
This is still Windows-only, right?

You tried messing around with some of the settings in the nvidia driver control panel?

I'll try asking around and see if some engineers can tell me anything substantive about any issues they might be experiencing here. I am reluctant to add a whole bunch of hacks to our basic syncing model just for G-Sync though.

**Comment by BlueNinja0** [comment]
Of course, I agree. This ought to be well implemented, not some side hack.
Keep in mind even though variable framerate is still in it's infancy, it is already a VESA standard and more and more monitors are going to support it with both NVidia and AMD already embracing it one way or another. And as I said, this is of special importance for emulators, where we have to make compromises, like programming special A/V synchronization algorithms in the emulator to cope with our crippled fixed 60Hz or 120Hz monitors.

And no, this is also on Linux already, fortunately. : )
http://www.blurbusters.com/gsync-support-arrives-in-new-linux-drivers/

**Comment by Googer** [comment]
Personally I think properly-working variable sync support is of even greater interest for arcade game emulation for perfectly smooth and accurate low-lag synchronization, given so many machines have funky refresh rates (Mortal Kombat using something in the vicinity of 53 Hz as I recall as an example).  Hopefully the hardware supporting this becomes mainstream sooner rather than later so we don't need to shell out stupid money for specialized gaming monitors just to get support for this. :p

**Comment by ToadKing** [comment]
Everything works currently on my setup. I have all default settings other than exclusive fullscreen and audio rate control delta set to 0. Not sure why BlueNinja0 is still having an issue.

Does your monitor say it's in G-Sync mode?

**Comment by BlueNinja0** [comment]
@ToadKing I only have an issue on 50Hz games. 60Hz games are perfectly smooth, even with audio control rate on 0.005. Yes, my monitor says it's in G-Sync mode.

Are you sure you are using all the default settings? That implies you are also using "Audio sync" and not using "Limit Maximum Run Speed" in general settings. Could you please share your settings file so that I can investigate this further?
I'm on the latest 1.1 Nightly by the way (build date April 28 2015), if that matters.

**Comment by ToadKing** [comment]
This is my settings: https://gist.github.com/ToadKing/5fb7d7288646082545fa

You'll want to use audio sync with G-sync instead of limit maximum run speed.

**Comment by BlueNinja0** [comment]
@ToadKing thanks for your help.

I was previously using "limit maximum run speed" incorrectly thinking it was an accurate way to limit the fps, but it isn't and indeed there was a minimal amount of judder. Thanks for the heads up. I've read on the RGUI that it is not accurate.
But the "audio sync" gives me even more stutter. If I disable it, the picture is absolutely smooth, but of course, running at 120fps.

I've tried the exact same configuration as you. I checked my config file against yours and I can't for the life of me get it smooth. I even used the same snes core as you. I'm using this ROM to test the smoothness with the "Grid scroll test", could you give it a try?
http://sourceforge.net/projects/testsuite240p/files/SNES_SFC/
But I've also tried with normal games and, albeit less noticeable, the result is the same.

I'm out of ideas. My computer is certainly able to run it, as it can run it perfectly smooth at 120fps. But here are my specs anyway:
i5 3570k @ 4.5Ghz
8GB RAM
GTX 680 SLI (yes I tried with SLI disabled)

I tried the MESS emulator and I managed to get perfect smoothness on both 60Hz and 50Hz games, meaning G-Sync was working correctly. But I like RetroArch more, and I wanted to use bsnes core.
I'm really out of ideas.

@ToadKing What do you have set as the maximum refresh rate allowed for your G-Sync in the NVidia drivers?

**Comment by bidinou** [comment]
Hi everyone ! Is it supposed to work nowadays on Linux ? I have a FreeSync monitor and using Lakka (KMS). I still have issues getting perfectly smooth scrollings in some games, even after tweaking tons of settings. (recent i5 nuc with iris 450).

**Comment by hizzlekizzle** [comment]
it should work. If you want to open a thread on the forum about it, I'll help you troubleshoot there.

**Comment by bidinou** [comment]
Thanks a lot ! I created a new issue : https://github.com/libretro/RetroArch/issues/3871
The main mystery seems to be that my monitor in freesync mode sets itself around 70-75 Hz for a 60 Hz games and Retroarch detects a rate around 55-60 Hz !!

**Comment by SirTuttles** [comment]
For anyone who may still be unable to get the smooth scrolling they desire, here's one more setting combo to try:

- Audio Sync: Off
- audio_rate_control = "false"
- Vsync in RetroArch: Off
- Vsync in Nvidia Control Panel: On [why?](https://www.blurbusters.com/gsync/gsync101/)
- Maximum runspeed: 1
- _Windows power plan: Performance_

"limit maximum runspeed option in general settings to use a cpu timer instead" - aliaspider

Power plans other than 'Performance' let windows adjust the CPU frequency on the fly. Sooo tell it not to :) !

I don't know that you need audio sync off when Maximum runspeed set to 1. It's possible that it may even be more beneficial to keeping it on.

**Comment by BlueNinja0** [comment]
@SirTuttles Did you try that with non-60Hz games? Like 50Hz PAL games or arcade 75Hz games?

**Comment by BlueNinja0** [comment]
@mdrejhon Excellent analysis! I was never aware that micro-stutter could happen this way. This might explain why it seemed I successfully configured Retroarch for VRR but still felt something was off. There was always this feeling of unevenness in the motion.

**Comment by mdrejhon** [comment]
UPDATE: Someone has posted a potential (partial, full) solution on Blur Busters Forums

https://forums.blurbusters.com/viewtopic.php?f=5&t=3903&p=31135#p31128

Unconfirmed fix.

Reading elsewhere, it seems it might fix many modules but may not fix MAME module (due to above possible framepacing bug) according to: https://forums.libretro.com/t/gsync-please-help-solve-this-mistery/12501

**Comment by mdrejhon** [comment]
Another suggestion for non-GSYNC is a new algorithm I have come up for emulator developers:
[Blur Busters Lagless Raster Follower Algorithm For Emulator Developers](https://www.blurbusters.com/blur-busters-lagless-raster-follower-algorithm-for-emulator-developers/)

Basically I've discovered a way to successfully synchronize the realworld raster to the virtual raster scanline within a ~0.5ms delay (a few scanlines worth of jittering).

**Comment by OverHaze** [comment]
The only way I have found to get smooth gsync is to use the Unconfirmed fix above, frame limit with Riva Tuner, turn off vsync at the driver level and then set frame delay to at least 10. 

That last bit is obviously an issue. Basically you can say goodbye to using Higan with this method!

**Comment by hizzlekizzle** [comment]
@mdrejhon I don't think your method will work with RetroArch/libretro, since--AFAIK--the lowest granularity we can go is one frame. That is, we can't really run a scanline or few and then vblank.

**Comment by OverHaze** [comment]
@hizzlekizzle Is a solution to the Gsync issue something that is currently being worked on?

**Comment by hizzlekizzle** [comment]
@OverHaze As far as we can tell, it seems to be fine with all cores except for the MAME-git core, which has microstutters(?). I think other cores should largely be fine, from what I've heard. @bparker06 has a gsync monitor now but he hasn't gotten any actionable reports to test/fix.

**Comment by mdrejhon** [comment]
> @mdrejhon I don't think your method will work with RetroArch/libretro, since--AFAIK--the lowest granularity we can go is one frame. That is, we can't really run a scanline or few and then vblank.

Sounds like it would be hard to do without rearchitecturing for line-based hooks at this time.  I'm talking to other emu devs that has expressed interest, there's now a working experimential raster chasing mod for GroovyMAME, and Toni is working on a beam chaser mode for WinUAE.  So it's coming to multiple emulators.  

I am currently investigating beginning a cross-platform raster-polling library (inquire within if interested) -- Oculus has something similar already for lowered-latency Android VR rendering as an approximate raster can be calculated from a VSYNC heartbeat.  So that is a portable beam chasing fallback for platforms that don't give you a raster register -- which apparently works, even on phones (which also have scanned displays too).

Maybe hold off until we see how complex it is in other emulators, and wait until a mature open-source cross-platform raster-poller becomes available for beam chasing applications.

**Comment by Awakened0** [comment]
@hizzlekizzle I think those MAME micro stutters were fixed when this issue was closed: https://github.com/libretro/mame/issues/28

**Comment by mdrejhon** [comment]
I still get reports of microstutters when MAME is used with GSYNC -- so maybe something else is happening.  Maybe what happened is frametime variances fell to sub-refresh-cycle leagues necessary to stop VSYNC ON microstuttering -- but that frametime variances aren't being made more exact than that (to make GSYNC/FreeSync look like VSYNC ON).

**Comment by bparker06** [comment]
Just for reference, I am successfully using G-Sync on Linux with the current default settings of RetroArch. The only thing that is really needed for it to work (at least on Linux) is to be in non-windowed fullscreen mode. I also use the "G-Sync Visual Indicator" setting in the nvidia-settings control panel to verify that it's on.

**Comment by twinaphex** [comment]
I think we have finally addressed this issue now with VRR runloop. So unless anybody objects, closing this issue.
