### ISSUE TITLE
Unable to install 1.19.1 release on Android 

### ISSUE THREAD

**Issue by sidkumararaja** [libretro/RetroArch#16669]
## Description

Trying to install the stable 1.19.1 APK on Android - I'm getting the error 'This app was built for an older version of Android and doesn't include the latest privacy protections'. I have tried using the aarch64 APK as well. I'm on a Pixel 7, running Android 14. I got the binaries from buildbot. What's weird is that the 1.17.0 version worked fine. I uninstalled it to install the newer version. 

### Expected behavior

Retroarch installs successfully. 

### Actual behavior

Retroarch fails to install due to unsupported OS version. 

### Steps to reproduce the bug

1. Download official APK binary. 
2. Install using Android file manager (permissions enabled for external apps)

### Version/Commit

- RetroArch: 1.19.1

### Environment information

- OS: Android 14

**Comment by yuvi3000** [comment]
Hey there. I thought I had this bug as well, but it seemed to just be a recent security update on my Android device.

Clicking "More Info" allowed me to click "Run Anyway" or something to that effect instead of "OK"

Clicking OK causes the device to say that the app was not installed.

**Comment by E3FxGaming** [comment]
On my Google Pixel 7 Pro I had to download the 64-bit version (on https://retroarch.com/index.php?page=platforms scroll down to "Android" and select "Download (64bit)").

The file you download should be called "RetroArch_aarch64.apk".

Installation should be possible without any problems/warning dialogues and when you go to your Android Settings app -> Apps -> "See all xxx apps" -> you should have a "RetroArch (AArch64)" app installed. If you have any other RetroArch installations you can uninstall them (after creating a backup of your save games, configs and roms, just to be sure).

The Google-designed processor inside the Pixel 7 and newer Pixel phones isn't compatible with 32 bit apps anyways, so you're not missing out on anything by choosing the 64bit version.

**Comment by gouchi** [comment]
@sidkumararaja Can you confirm it is working with [64bit version](https://buildbot.libretro.com/stable/1.19.1/android/RetroArch_aarch64.apk) ? So that we can close this issue.

Thank you.

**Comment by RickAndTired** [comment]
I'm getting the same error with 32bit and 64bit versions

If you click `More details` it will show an `Install anyway` button - not sure if this is safe

Pixel 4a - Android 13

![Screenshot from 2024-08-09 14-08-32](https://github.com/user-attachments/assets/c860976a-e9b7-41f9-9823-f97f5ddeb9b7)

**Comment by davidhedlund** [comment]
> I'm getting the same error with 32bit and 64bit versions
> 
> If you click `More details` it will show an `Install anyway` button - not sure if this is safe
> 
> Pixel 4a - Android 13
> 
> ![Screenshot from 2024-08-09 14-08-32](https://private-user-images.githubusercontent.com/53553229/356755877-c860976a-e9b7-41f9-9823-f97f5ddeb9b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MzMyNzMsIm5iZiI6MTcyMzkzMjk3MywicGF0aCI6Ii81MzU1MzIyOS8zNTY3NTU4NzctYzg2MDk3NmEtZTliNy00MWY5LTk4MjMtZjk3ZjVkZGViOWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDIyMTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZDM0OGM5NmFmMGRhMzFhNGFiYjNjZDhkZTZmMjc3M2Y3NDRmZmVmOThlMDZhYWIwMmE4NjhkOTUzM2NhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u7f6FJimt1rVZGngIMYdhhwTRYUSdCKWIYqZIJRHrWw)

Same here on Android 10 with:
* https://buildbot.libretro.com/stable/1.9.1/android/RetroArch.apk
* https://buildbot.libretro.com/stable/1.9.1/android/RetroArch_aarch64.apk
* https://buildbot.libretro.com/stable/1.9.1/android/RetroArch_ra32.apk

Even when I'm using APKMirror Installer, and pressing "Install anyway":

![image](https://github.com/user-attachments/assets/3617d172-c378-44c1-a3ba-7b4a2981ebd5)

**Comment by davidhedlund** [comment]
To summarize this issue: Android [10](https://github.com/libretro/RetroArch/issues/16669#issuecomment-2295001656) to Android [14](https://github.com/libretro/RetroArch/issues/16669#issue-2341648121) is affected, for various users.

**Comment by Korb** [comment]
F-Droid currently offers version 1.19.1 (1597175262) ​​for installation.

> Added on 09/06/2024
> Size: 23.7 MiB
> Android: 4.1+

> This app was built for an older version of Android and **cannot be updated automatically**.

> Starting August 31 2024:
> New apps and app updates must target Android 14 (API level 34) or higher to be submitted to Google Play; except for Wear OS and Android TV apps, which must target Android 13 (API level **33**) or higher.
"[Meet Google Play's target API level requirement](https://developer.android.com/google/play/requirements/target-sdk)" / "[Target API level requirements for Google Play apps](https://support.google.com/googleplay/android-developer/answer/11926878)"

The current version of [SDK Platform Tools](https://developer.android.com/tools/releases/platform-tools) is **35**.0.2 (July 2024).

**Comment by davidhedlund** [comment]
This issue started in 1.19.0, not 1.19.1. I submitted a detailed issued here:
* https://github.com/libretro/RetroArch/issues/17014

**Comment by davidhedlund** [comment]
Solved in RetroArch 1.20.0:
* https://github.com/libretro/RetroArch/issues/17014

So this issue can now be closed.

**Comment by gouchi** [comment]
@sidkumararaja Please close this issue. Thank you.

**Comment by Korb** [comment]
> "This app was built for an older version of Android"
(…)
> Solved in RetroArch 1.20.0

> 1.20.0 (1597175263) (Suggested)
> Added on 13/01/2025
> Size: 26.4 MiB
> Android: 4.1+
> Requires: arm64-v8a, armeabi-v7a, x86, x86_64

I still see a notification that this app is not fully compatible with Android 14 and is therefore not recommended for installation.

**Comment by davidhedlund** [comment]
> > "This app was built for an older version of Android"
> > (…)
> > Solved in RetroArch 1.20.0
> 
> > 1.20.0 (1597175263) (Suggested)
> > Added on 13/01/2025
> > Size: 26.4 MiB
> > Android: 4.1+
> > Requires: arm64-v8a, armeabi-v7a, x86, x86_64
> 
> I still see a notification that this app is not fully compatible with Android 14 and is therefore not recommended for installation.

Please participate in:
* https://github.com/libretro/RetroArch/issues/17014

Specifically, give all data in the table columns so I can expand the table.

**Comment by davidhedlund** [comment]
> > "This app was built for an older version of Android"
> > (…)
> > Solved in RetroArch 1.20.0
> 
> > 1.20.0 (1597175263) (Suggested)
> > Added on 13/01/2025
> > Size: 26.4 MiB
> > Android: 4.1+
> > Requires: arm64-v8a, armeabi-v7a, x86, x86_64
> 
> I still see a notification that this app is not fully compatible with Android 14 and is therefore not recommended for installation.

Thank you for adding this to https://github.com/libretro/RetroArch/issues/17014#issuecomment-2672195777
