### ISSUE TITLE
RetroArch is half off-screen when fullscreen

### ISSUE THREAD

**Issue by klazoklazo** [libretro/RetroArch#16779]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
RetroArch is half off-screen when fullscreen.

![image](https://github.com/user-attachments/assets/2ebfb1c7-948b-47ea-a145-6f8097acb616)

![image](https://github.com/user-attachments/assets/93eef79e-139e-4e48-82a5-042cc45f827a)

### Expected behavior

RetroArch's fullscreen image should be inside the monitor it's displaying in.

### Actual behavior

RetroArch's fullscreen image is instead pushed half of the monitors resolution to the left. This also means any monitors to the left of the used display gets to see the left half of the fullscreened RetroArch view. Moving the fullscreened view between monitors somehow fixes this, but the view regenerating when reopening the program or launching a game reproduces this issue.

Disabling Wayland through Flatseal and forcing it to fallback to Xwayland fixes this issue, but produces a different issue.

### Steps to reproduce the bug

1. Launch RetroArch
2. Turn on fullscreen mode

Alternatively

1. Have fullscreen mode already enabled
2. Launch RetroArch

### Bisect Results

[Try to bisect and tell us when this started happening]

Installed through Flatpak, unsure of how to do this.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Fedora Workstation 40
- Compiler: None, installed through Flatpak

**Comment by gouchi** [comment]
I can not reproduce this issue using Fedora 40 on Wayland using GLcore video driver.

May you provide some log using  ?

`flatpak run  org.libretro.RetroArch -v`

Perhaps you are using several monitors ?

Thank you.

P.S = If it is related to the Flatpak package, it will be better to open the [issue in this repository](https://github.com/flathub/org.libretro.RetroArch/issues/).

**Comment by klazoklazo** [comment]
Update!! I managed to fix the issue in a more permanent form by changing the monitor RetroArch displayed on in the settings. Display 0 (auto) seemingly can't decide between either of my two monitors (I am indeed using multiple monitors), so changing it to display 1 fixes the problem.

**Comment by klazoklazo** [comment]
Another update, I've moved to Ubuntu 24.04.1 LTS and tried to run RetroArch through the Flatpak and the problem is no longer fixable with the method I had described previously. I tried forcing the application to run in X11 as well but it broke in a different way, see here: https://github.com/libretro/RetroArch/issues/15259

Through this [thread of Reddit comments](https://new.reddit.com/r/RetroArch/comments/1h3trxp/ubuntu_24041_lts_fullscreen_doesnt_work_in_general/) one of the devs tried helping me in utilizing a different installation method of RetroArch but they all had issues with window decorations and apparently only the PPA version can deal with Ubuntu 24.04.1's version of `libdecor-0-dev` due to the others being sandboxxed.

Unfortunately after fixing that problem the PPA version similarly shows the same problem with its fullscreen mode being half off-screen with no way to fix it like in the Flatpak. I tried forcing it to run in X11 through using environment variables (full command I tried using was `Exec=env GDK_BACKEND=x11 retroarch` but it resulted in the window decorations breaking again and instability whenever I tried fullscreening or un-fullscreening RetroArch.

Screenshots below:

The PPA version of RetroArch running in Wayland with window decorations through manually installing `libdecor-0-dev`:

![image](https://github.com/user-attachments/assets/ceb8f4d0-0007-49c3-a095-cdec8c017f58)

Fullscreening the setup shown above results in the same problem shown in the original post:

![image](https://github.com/user-attachments/assets/77b16abe-32ba-4468-b5a8-7c5e440a31d5)

Running RetroArch in X11 results in the window decorations breaking again:

![image](https://github.com/user-attachments/assets/b2b51066-1fa5-4b93-b63d-1bd0dd7eefe0)

Fullscreening RetroArch commonly causes the window to seemingly disappear, I assume this is a crash?

![image](https://github.com/user-attachments/assets/205fd5c9-1a6a-4e8d-a67f-fc5dd97c621d)

**Comment by nfp0** [comment]
I have the same or very similar problem on a clean new RetroArch config. I am running KDE on Wayland and I have 2 screens.

In fullscreen mode, if RetroArch's "Monitor Index" setting is set to "Auto", it will show up in a window off-center as you can see here:

![Image](https://github.com/user-attachments/assets/cf520935-3f67-4b49-8f56-155321ba5c0c)
(Log in the background, in case it helps)

Alt-tabbing makes it go to the correct position (fill the whole screen).
Setting "Monitor Index" to specific monitors also works correctly. It's only the "Auto" that is failing.

@gouchi This is happening to me in both Vulkan and GLcore. Worse yet, on GLcore, even setting the "Monitor Index" does not fix the issue.

**Comment by amigthea** [comment]
@nfp0 same setup, same problem

vulkan on arch KDE Wayland with a second monitor, I need to alt-tab everytime to fix when Monitor Index is on auto

**Comment by The-Pezman** [comment]
It looks like I have a similar issue. I'm running Kubuntu 25.04, and installed Retroarch through the flatpak. I have an external monitor attached to my laptop, which is what I want to play the games on.

Whenever I open retroarch, it starts with the upper left corner in the center of the screen:

![Image](https://github.com/user-attachments/assets/623bda7d-909f-4655-b249-b88eeac212fc)

I can at least drag the window when it's like that. But when I turn it full screen, it's stuck in that position:

![Image](https://github.com/user-attachments/assets/80e0c3b8-03d5-411e-a8f1-41b1837bc47c)

**Comment by 0x09AF** [comment]
Same on **Arch KDE** with **Wayland** and 2 external monitors. RetroArch version **1.20**  
When it starts in the middle like that - I usually use `kwin` hotkeys to move the window between the monitors and it snaps to the monitor I need.

![Image](https://github.com/user-attachments/assets/35cd3798-80d1-4151-a3dc-8c5e2f559fe5)

**Comment by The-Pezman** [comment]
That doesn't work in fullscreen mode

**Comment by 0x09AF** [comment]
> That doesn't work in fullscreen mode
> […](#)

It works for me in fullscreen because kwin shortcuts are global. I am not sure how Flatpak works, but I use a native package

**Comment by tonybonesyou** [comment]
> Update!! I managed to fix the issue in a more permanent form by changing the monitor RetroArch displayed on in the settings. Display 0 (auto) seemingly can't decide between either of my two monitors (I am indeed using multiple monitors), so changing it to display 1 fixes the problem.

I just installed RetroArch in Bazzite 42 Fedora and was having the same issue where fullscreen put the top left corner in the middle of the screen and it would go off the screen to the bottom right. Your fix of choosing '1' in 'Monitor Index' fixed it for me, so I wanted to thank you!

**Comment by Smellbringer** [comment]
> I have the same or very similar problem on a clean new RetroArch config. I am running KDE Wayland on Arch and I have 2 screens.
> 
> In fullscreen mode, if RetroArch's "Monitor Index" setting is set to "Auto", it will show up in a window off-center as you can see here:
> 
> ![Image](https://github.com/user-attachments/assets/cf520935-3f67-4b49-8f56-155321ba5c0c) (Log in the background, in case it helps)
> 
> Alt-tabbing makes it go to the correct position (fill the whole screen). Setting "Monitor Index" to specific monitors also works correctly. It's only the "Auto" that is failing.
> 
> [@gouchi](https://github.com/gouchi) This is happening to me in both Vulkan and GLcore. Worse yet, on GLcore, even setting the "Monitor Index" does not fix the issue.
> 
> EDIT: Not sure if it's related to this issue, but this other issue seems to be more exact to what I'm experiencing: [#17372](https://github.com/libretro/RetroArch/issues/17372)

I could kiss you, sir.

Running CachyOS, KDE Plasma, 2 Monitors, and this is exactly what I needed. Thank you.

**Comment by trr** [comment]
Problem present on 1.22.1 on kwin_wayland for me.

I do not have multiple monitors, nor does setting the monitor index to something other than 0 fix it.


On gl and glcore driver the problem occurs basically all the time, on vulkan it happens around 50% of the time.  When it works, it appears to first appear in the wrong place (windowed with top left corner in middle of screen, half off the screen) and then move up into the right position (fullscreen).

Workaround for now is to add a window rule in kwin for the application to force fullscreen.

Looks like a race condition / timing type issue with when retroarch chooses to make the newly created window fullscreen and/or where it places the window briefly before it does so.

**Comment by v4u6h4n** [comment]
arch on kde here, have the same problem on wayland, and only one monitor connected, cant seem to find a combination of options that fixes it. so am doing same window rule fix as @trr

**Comment by joshcancode** [comment]
Same issue, new Arch install using KDE, dual monitor setup

**Comment by delazerirafael5** [comment]
I have the same issue here. My setup is also a dual monitor (both screens same resolution, refresh rate and color profile) in KDE Wayland, cachyOS, amdgpu driver, Retroarch 1.22.2 compiled from git. When using X11, I don't have any problems at all with Retroarch, although I had problems with mismatched refresh rates above 60Hz when playing anything (probably a X11 issue). I've manage to workaround this retroarch fullscreen problem by creating window rules in KWin:


<img width="652" height="328" alt="Image" src="https://github.com/user-attachments/assets/e99e58e6-d241-4a9e-bece-c653d7c9526f" />

**Comment by Avilnetro** [comment]
Just wanted to confirm the same issue here. Arch Linux, KDE, Wayland, single monitor. Trying to use native fullscreen within RetroArch causes the top left corner of the window to draw at the center 0,0 of my display, causing three quarters of the window to be cut off. Using delazerirafael5's above workaround resolves the problem, although I set my rule to "Apply initially" rather than "Force". This works well, just with the added detriment of not being able to cycle between fullscreen and windowed mode without an application restart.

**Comment by The-Pezman** [comment]
delazerirafael5's fix worked for me as well! However, I'm still hopeful we can address the root issue

**Comment by PoloniumRain** [comment]
Think i've fixed it... Could someone here test this out on real hardware? I'll submit a PR if it works.

I don't use Linux and only recently got some distros running inside VM's out of curiosity. At first i thought this problem might be due to the VM, but obviously not.

Here's my RetroArch [build](https://github.com/user-attachments/files/25185902/retroarch.zip) with the fix.

If that doesn't run on your distro for some reason, then build RA yourself with [these](https://github.com/user-attachments/files/25161776/files.zip) two patched files (diffs below). Place them inside this directory: `gfx\drivers_context`

Out of the 9 distros i've tried, the fullscreen issue happens on 7 of them. It's always Wayland with `gl`, `glcore` , `gl1` and apparently `Vulkan` as well (cant test the latter). All three GL video drivers should now work, and **_maybe_** Vulkan too, but i can't test that as Vulkan isn't supported by my VM software.

<br/><br/>Diffs:

`wayland_ctx.c`

```diff
    EGLint *attr              = egl_fill_attribs(
          (gfx_ctx_wayland_data_t*)data, egl_attribs);

+   if (!wl->fractional_scale &&
+       wl_compositor_get_version(wl->compositor) >=
+       WL_SURFACE_SET_BUFFER_SCALE_SINCE_VERSION)
+      wl_surface_set_buffer_scale(wl->surface, wl->buffer_scale);
+
    wl->win = wl_egl_window_create(wl->surface,
       wl->buffer_width,
       wl->buffer_height);

    if (!egl_create_context(&wl->egl, (attr != egl_attribs)
             ? egl_attribs : NULL))
       goto error;

    egl_set_swap_interval(&wl->egl, wl->egl.interval);
 #endif

+   if (fullscreen)
+      wl->ignore_configuration = false;
 
    if (!gfx_ctx_wl_set_video_mode_common_fullscreen(wl, fullscreen))
       goto error;
```


`wayland_vk_ctx.c`

```diff
    if (!gfx_ctx_wl_set_video_mode_common_size(wl, width, height, fullscreen))
       goto error;

+   if (!wl->fractional_scale &&
+       wl_compositor_get_version(wl->compositor) >=
+       WL_SURFACE_SET_BUFFER_SCALE_SINCE_VERSION)
+      wl_surface_set_buffer_scale(wl->surface, wl->buffer_scale);
+
    if (!vulkan_surface_create(&wl->vk, VULKAN_WSI_WAYLAND,
          wl->input.dpy, wl->surface,
          wl->buffer_width,
          wl->buffer_height,
          wl->swap_interval))
       goto error;
+
+   if (fullscreen)
+      wl->ignore_configuration = false;
+
    if (!gfx_ctx_wl_set_video_mode_common_fullscreen(wl, fullscreen))
       goto error;
```

**Comment by The-Pezman** [comment]
Was a new version just pushed? I think this has been fixed now.

**Comment by PoloniumRain** [comment]
@The-Pezman Well i haven't done anything lol. The issue is still there in the latest commit.

If fullscreen suddenly started working, it's probably because you're using a build that is built with older libraries/dependences. 

But newer libraries/dependencies = broken fullscreen (especially on Arch based distros, but Fedora always works).

So right now, this means that depending on where RetroArch is downloaded from, or your personal build environment, it may or may not have the fullscreen issue. The fix i posted above is built with newer libraries/dependences and will **still** work, at least for GL based video drivers.

But i'm still waiting for someone to test my fix with Vulkan. I've just edited my post above with a new build that should work on more distros. Could you please give it a go? :)

**Comment by CosmicHeron** [comment]
Confirming that the patch works after recompiling on Arch Linux.
