### ISSUE TITLE
CloudSync begin failed

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#17315]
### Is there an existing issue for this?

- [X] This is a bug in RetroArch frontend
- [X] I have searched the existing issues

### Description

Followed the instructions over on https://docs.libretro.com/guides/retroarch-cloud-sync/ in order to have cloud sync. As far as I can tell I have followed the instructions correctly, and the WebDav share works correctly in macOS finder, but when I open RetroArch a message that says _Cloud Sync in progress 0%_ appears for five seconds or so, then it is replaced with _Cloud Sync failed_. In order to try and solve this I enabled logging, but only the line ```[WARN] [CloudSync] begin failed``` appears, which is not helpful. I have also tried this on iOS and the same two tooltips appear. Both were almost clean installs, so it might have something to do with that.

### Expected behavior

Either working cloud sync or a descriptive error message.

### Steps to reproduce the bug

1. Follow this guide https://docs.libretro.com/guides/retroarch-cloud-sync/ on a clean install of RetroArch (found on macOS (Apple Silicon) and iOS).
2. Enable logging.

### Version/Commit

1.19.1 (Git a0208dd56)

### Check in the nightly version

I don't know

### Platform & operating system

macOS 15.2

### Relevant log output

```shell
[INFO] RetroArch 1.19.1 (Git a0208dd56)
[INFO] === Build =======================================
[INFO] CPU Model Name: Apple M4
[INFO] Capabilities: NEON VFPV3 VFPV4 
[INFO] Version: 1.19.1
[INFO] Git: a0208dd56
[INFO] Built: Jun  5 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "cocoa".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Core]: Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "cocoavk".
[INFO] [Vulkan]: Detecting screen resolution: 480x360.
[INFO] [macOS]: Native window size: 960 x 720.
[INFO] [Vulkan]: Found GPU at index 0: "Apple M4".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using semaphores for WSI acquire.
[INFO] [Vulkan]: Using GPU: "Apple M4".
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 960x720.
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [Joypad]: Found joypad driver: "mfi".
[INFO] [Video]: Found display server: "null".
[INFO] [CoreAudio3]: Using buffer size of 24576 bytes: (latency = 64 ms)
[INFO] [Audio]: Started synchronous audio driver.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Playlist]: Loading history file: "/Users/pablo/Library/Application Support/RetroArch/config/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/Users/pablo/Library/Application Support/RetroArch/config/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/Users/pablo/Library/Application Support/RetroArch/config/content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/Users/pablo/Library/Application Support/RetroArch/config/content_favorites.lpl".
[DEBUG] [Audio]: Started audio driver "coreaudio3" (is_shutdown=false)
[DEBUG] [Audio]: Stopped audio driver "coreaudio3"
[INFO] [Vulkan]: QueuePresent failed, destroying swapchain.
[INFO] [Vulkan]: Got 3 swapchain images.
[WARN] [CloudSync] begin failed
[INFO] [Core Info]: Wrote to cache file: "/Users/pablo/Library/Application Support/RetroArch/info/core_info.cache".
[INFO] [Config]: Saved new config to "/Users/pablo/Library/Application Support/RetroArch/config/retroarch.cfg".
[DEBUG] [Audio]: Started audio driver "coreaudio3" (is_shutdown=true)
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[DEBUG] [Audio]: Stopped audio driver "coreaudio3"
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[DEBUG] [Video]: Average monitor Hz: 74.940048 Hz. (4.920 % frame time deviation, based on 2048 last samples).
```

**Comment by KiralyCraft** [comment]
From what I remember, "begin failed" usually implies some sort of connectivity issues. The WebDav code is indeed a bit of magic, I'll look into it if I get some time. Meanwhile it may be clearer for @warmenhoven

**Comment by warmenhoven** [comment]
1.20 adds a bit of logging code so you can get a little bit more insight into failures, but my guess is you won't see a lot of additional logs because it's not actually connecting correctly. You might be able to use tcpdump to see if it's even attempting to connect to the right host.

**Comment by troilus** [comment]
I set a https server in ra and logs show ra visit the https address, but it 0% .  I checked the log on the WebDAV server it shows ra connect the server with http

**Comment by warmenhoven** [comment]
If the app is compiled without SSL support then even with an https URL it will not use SSL.

**Comment by warmenhoven** [comment]
Just saw your edit; iOS should be compiled with SSL. Can you send the log?

**Comment by troilus** [comment]
> Just saw your edit; iOS should be compiled with SSL. Can you send the log?
Sorry, I tried again today, and it's not due to HTTPS. The issue is that synchronization only starts if it's the first sync (or if I delete the previously existing manifest.server file on the server). Otherwise, it stays stuck at 0%. Regardless of whether the synchronization is successful or not, the date on my WebDAV server always shows HTTP, so it shouldn't be an HTTPS issue.

logs when there is a manifest.server in webdav server at it stucked at 0%:
iOS log:
`
[INFO] RetroArch 1.20.0 (Git ab3b175848)
[INFO] === Build =======================================
[INFO] 容量: NEON VFPV3 VFPV4 
[INFO] Version: 1.20.0
[INFO] Git: ab3b175848
[INFO] Built: Jan  5 2025
[INFO] =================================================
[INFO] [Input]: Found input driver: "cocoa".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: libretro API 版本: 1, 未按照 API 编译: 1
[INFO] [Core]: Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "cocoavk".
[DEBUG] [Vulkan]: Config requires windowed mode, but context driver does not support it. Forcing fullscreen for this session.
[INFO] [Vulkan]: Detecting screen resolution: 1170x2532.
[INFO] [Vulkan]: Found GPU at index 0: "Apple A15 GPU".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using semaphores for WSI acquire.
[INFO] [Vulkan]: Using GPU: "Apple A15 GPU".
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[DEBUG] [Vulkan]: Swapchain supports present mode: FIFO.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 1170x2532.
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [Joypad]: Found joypad driver: "mfi".
[INFO] [Video]: Found display server: "apple".
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[DEBUG] [SDL audio]: Opened SDL audio out device with ID 2
[DEBUG] [SDL audio]: Requested a speaker frequency of 48000 Hz, got 48000 Hz
[DEBUG] [SDL audio]: Requested 2 channels for speaker, got 2
[DEBUG] [SDL audio]: Requested a 1024-frame speaker buffer, got 1024 frames (4096 bytes)
[DEBUG] [SDL audio]: Got a speaker silence value of 0
[DEBUG] [SDL audio]: Requested speaker audio format: 16-bit signed integer little endian
[DEBUG] [SDL audio]: Received speaker audio format: 16-bit signed integer little endian
[INFO] [SDL audio]: Requested 64 ms latency for output device, got 85 ms
[DEBUG] [SDL audio]: Initialized speaker sample queue with 8192 bytes
[INFO] [Audio]: Started synchronous audio driver.
[WARN] [Audio]: Rate control was desired, but driver does not support needed features.
[INFO] [Microphone]: Initialized microphone driver.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Playlist]: 正在读取历史文件: "/private/var/mobile/Containers/Data/Application/697ACD11-5BF9-4CD4-83DD-514FD45EDF5B/Documents/RetroArch/config/content_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/private/var/mobile/Containers/Data/Application/697ACD11-5BF9-4CD4-83DD-514FD45EDF5B/Documents/RetroArch/config/content_music_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/private/var/mobile/Containers/Data/Application/697ACD11-5BF9-4CD4-83DD-514FD45EDF5B/Documents/RetroArch/config/content_video_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/private/var/mobile/Containers/Data/Application/697ACD11-5BF9-4CD4-83DD-514FD45EDF5B/Documents/RetroArch/config/content_image_history.lpl".
[INFO] [Playlist]: 正在加载收藏文件: "/private/var/mobile/Containers/Data/Application/697ACD11-5BF9-4CD4-83DD-514FD45EDF5B/Documents/RetroArch/config/content_favorites.lpl".
[DEBUG] [Audio]: Started audio driver "sdl2" (is_shutdown=false)
[DEBUG] [Audio]: Stopped audio driver "sdl2"
[DEBUG] [Vulkan]: Creating swapchain with present mode: FIFO.
[DEBUG] [Audio]: Started audio driver "sdl2" (is_shutdown=false)
[INFO] [CloudSync] begin succeeded
[DEBUG] [webdav] GET https://webdav4.xanyi.top:20000/retroarch/manifest.server
[DEBUG] [Audio]: Started audio driver "sdl2" (is_shutdown=false)
[INFO] [Config]: 已保存新配置到 "~/Documents/RetroArch/config/retroarch.cfg".
[DEBUG] [Audio]: Started audio driver "sdl2" (is_shutdown=true)

`

log of webdav server:
`
{"level":"debug","time":"2025-02-18T08:40:47.598","sender":"DAV","connection_id":"DAV_cupte3sf21kp9bqk2lrg","message":"connection added, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:35238\", num open connections: 1"}
{"level":"info","time":"2025-02-18T08:40:47.599","sender":"webdavd","elapsed_ms":0,"method":"OPTIONS","proto":"HTTP/1.1","remote_addr":"127.0.0.1:35238","request_id":"cupte3sf21kp9bqk2lrg","uri":"http://webdav4.xanyi.top:20000/retroarch/","user_agent":"libretro"}
{"level":"debug","time":"2025-02-18T08:40:47.599","sender":"DAV","connection_id":"DAV_cupte3sf21kp9bqk2lrg","message":"connection removed, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:35238\" close fs error: <nil>, num open connections: 0"}
{"level":"debug","time":"2025-02-18T08:40:48.276","sender":"DAV","connection_id":"DAV_cupte44f21kp9bqk2ls0","message":"connection added, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:35238\", num open connections: 1"}
{"level":"debug","time":"2025-02-18T08:40:48.276","sender":"DAV","connection_id":"DAV_cupte44f21kp9bqk2ls0","message":"transfer added, id: 1, active transfers: 1"}
{"level":"info","time":"2025-02-18T08:40:48.277","sender":"Download","local_addr":"127.0.0.1:30001","remote_addr":"127.0.0.1:35238","elapsed_ms":0,"size_bytes":8426,"username":"troilusxi","file_path":"/home/sftpgostore/troilusxi/retroarch/manifest.server","connection_id":"DAV_cupte44f21kp9bqk2ls0","protocol":"DAV"}
{"level":"debug","time":"2025-02-18T08:40:48.277","sender":"DAV","connection_id":"DAV_cupte44f21kp9bqk2ls0","message":"transfer removed, id: 1 active transfers: 0"}
{"level":"info","time":"2025-02-18T08:40:48.277","sender":"webdavd","elapsed_ms":0,"method":"GET","proto":"HTTP/1.1","remote_addr":"127.0.0.1:35238","request_id":"cupte44f21kp9bqk2ls0","uri":"http://webdav4.xanyi.top:20000/retroarch/manifest.server","user_agent":"libretro"}
{"level":"debug","time":"2025-02-18T08:40:48.277","sender":"DAV","connection_id":"DAV_cupte44f21kp9bqk2ls0","message":"connection removed, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:35238\" close fs error: <nil>, num open connections: 0"}

`

logs when I make a empty restroarch folder on webdav server,it sync correctly:
`
[INFO] RetroArch 1.20.0 (Git ab3b175848)
[INFO] === Build =======================================
[INFO] 容量: NEON VFPV3 VFPV4 
[INFO] Version: 1.20.0
[INFO] Git: ab3b175848
[INFO] Built: Jan  5 2025
[INFO] =================================================
[INFO] [Input]: Found input driver: "cocoa".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: libretro API 版本: 1, 未按照 API 编译: 1
[INFO] [Core]: Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "cocoavk".
[DEBUG] [Vulkan]: Config requires windowed mode, but context driver does not support it. Forcing fullscreen for this session.
[INFO] [Vulkan]: Detecting screen resolution: 1170x2532.
[INFO] [Vulkan]: Found GPU at index 0: "Apple A15 GPU".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using semaphores for WSI acquire.
[INFO] [Vulkan]: Using GPU: "Apple A15 GPU".
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[DEBUG] [Vulkan]: Swapchain supports present mode: FIFO.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 1170x2532.
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [Joypad]: Found joypad driver: "mfi".
[INFO] [Video]: Found display server: "apple".
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[DEBUG] [SDL audio]: Opened SDL audio out device with ID 2
[DEBUG] [SDL audio]: Requested a speaker frequency of 48000 Hz, got 48000 Hz
[DEBUG] [SDL audio]: Requested 2 channels for speaker, got 2
[DEBUG] [SDL audio]: Requested a 1024-frame speaker buffer, got 1024 frames (4096 bytes)
[DEBUG] [SDL audio]: Got a speaker silence value of 0
[DEBUG] [SDL audio]: Requested speaker audio format: 16-bit signed integer little endian
[DEBUG] [SDL audio]: Received speaker audio format: 16-bit signed integer little endian
[INFO] [SDL audio]: Requested 64 ms latency for output device, got 85 ms
[DEBUG] [SDL audio]: Initialized speaker sample queue with 8192 bytes
[INFO] [Audio]: Started synchronous audio driver.
[WARN] [Audio]: Rate control was desired, but driver does not support needed features.
[INFO] [Microphone]: Initialized microphone driver.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Playlist]: 正在读取历史文件: "/private/var/mobile/Containers/Data/Application/697ACD11-5BF9-4CD4-83DD-514FD45EDF5B/Documents/RetroArch/config/content_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/private/var/mobile/Containers/Data/Application/697ACD11-5BF9-4CD4-83DD-514FD45EDF5B/Documents/RetroArch/config/content_music_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/private/var/mobile/Containers/Data/Application/697ACD11-5BF9-4CD4-83DD-514FD45EDF5B/Documents/RetroArch/config/content_video_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/private/var/mobile/Containers/Data/Application/697ACD11-5BF9-4CD4-83DD-514FD45EDF5B/Documents/RetroArch/config/content_image_history.lpl".
[INFO] [Playlist]: 正在加载收藏文件: "/private/var/mobile/Containers/Data/Application/697ACD11-5BF9-4CD4-83DD-514FD45EDF5B/Documents/RetroArch/config/content_favorites.lpl".
[DEBUG] [Audio]: Started audio driver "sdl2" (is_shutdown=false)
[DEBUG] [Audio]: Stopped audio driver "sdl2"
[DEBUG] [Vulkan]: Creating swapchain with present mode: FIFO.
[DEBUG] [Audio]: Started audio driver "sdl2" (is_shutdown=false)
[DEBUG] [Audio]: Started audio driver "sdl2" (is_shutdown=false)
[INFO] [CloudSync] begin succeeded
[DEBUG] [webdav] GET https://webdav4.xanyi.top:20000/retroarch/manifest.server
[INFO] [CloudSync] server manifest fetch succeeded
[INFO] [CloudSync] created manifest with 0 files
[WARN] [CloudSync] opened local manifest
[INFO] [CloudSync] created manifest with 62 files
[INFO] [CloudSync] created in-memory manifest of current disk state
[INFO] [CloudSync] uploading saves/2048/2048.srm
........
`
`
{"level":"debug","time":"2025-02-18T08:56:28.781","sender":"DAV","connection_id":"DAV_cuptlf4f21kp9bqk328g","message":"connection added, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:39342\", num open connections: 1"}
{"level":"warn","time":"2025-02-18T08:56:28.781","sender":"DAV","connection_id":"DAV_cuptlf4f21kp9bqk328g","message":"stat error for path \"/retroarch/desktop.ini\": stat /home/sftpgostore/troilusxi/retroarch/desktop.ini: no such file or directory"}
{"level":"info","time":"2025-02-18T08:56:28.781","sender":"webdavd","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"127.0.0.1:39342","request_id":"cuptlf4f21kp9bqk328g","resp_status":404,"uri":"http://webdav4.xanyi.top:20000/retroarch/desktop.ini","user_agent":"Microsoft-WebDAV-MiniRedir/10.0.19045","error":"file does not exist"}
{"level":"debug","time":"2025-02-18T08:56:28.781","sender":"DAV","connection_id":"DAV_cuptlf4f21kp9bqk328g","message":"connection removed, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:39342\" close fs error: <nil>, num open connections: 0"}
{"level":"debug","time":"2025-02-18T08:56:28.791","sender":"DAV","connection_id":"DAV_cuptlf4f21kp9bqk3290","message":"connection added, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:39342\", num open connections: 1"}
{"level":"info","time":"2025-02-18T08:56:28.792","sender":"webdavd","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"127.0.0.1:39342","request_id":"cuptlf4f21kp9bqk3290","uri":"http://webdav4.xanyi.top:20000/","user_agent":"Microsoft-WebDAV-MiniRedir/10.0.19045"}
{"level":"debug","time":"2025-02-18T08:56:28.792","sender":"DAV","connection_id":"DAV_cuptlf4f21kp9bqk3290","message":"connection removed, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:39342\" close fs error: <nil>, num open connections: 0"}
{"level":"debug","time":"2025-02-18T08:56:29.532","sender":"DAV","connection_id":"DAV_cuptlfcf21kp9bqk329g","message":"connection added, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:39342\", num open connections: 1"}
{"level":"debug","time":"2025-02-18T08:56:29.533","sender":"DAV","connection_id":"DAV_cuptlfcf21kp9bqk329g","message":"transfer added, id: 1, active transfers: 1"}
{"level":"info","time":"2025-02-18T08:56:29.533","sender":"Download","local_addr":"127.0.0.1:30001","remote_addr":"127.0.0.1:39342","elapsed_ms":0,"size_bytes":512,"username":"troilusxi","file_path":"/home/sftpgostore/troilusxi/retroarch/manifest.server","connection_id":"DAV_cuptlfcf21kp9bqk329g","protocol":"DAV"}
{"level":"debug","time":"2025-02-18T08:56:29.533","sender":"DAV","connection_id":"DAV_cuptlfcf21kp9bqk329g","message":"transfer removed, id: 1 active transfers: 0"}
{"level":"info","time":"2025-02-18T08:56:29.533","sender":"webdavd","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"127.0.0.1:39342","request_id":"cuptlfcf21kp9bqk329g","uri":"http://webdav4.xanyi.top:20000/retroarch/manifest.server","user_agent":"Microsoft-WebDAV-MiniRedir/10.0.19045"}
{"level":"debug","time":"2025-02-18T08:56:29.533","sender":"DAV","connection_id":"DAV_cuptlfcf21kp9bqk329g","message":"connection removed, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:39342\" close fs error: <nil>, num open connections: 0"}
{"level":"debug","time":"2025-02-18T08:56:30.233","sender":"DAV","connection_id":"DAV_cuptlfkf21kp9bqk32a0","message":"connection added, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:39342\", num open connections: 1"}
{"level":"info","time":"2025-02-18T08:56:30.234","sender":"webdavd","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"127.0.0.1:39342","request_id":"cuptlfkf21kp9bqk32a0","uri":"http://webdav4.xanyi.top:20000/retroarch","user_agent":"Microsoft-WebDAV-MiniRedir/10.0.19045"}
{"level":"debug","time":"2025-02-18T08:56:30.234","sender":"DAV","connection_id":"DAV_cuptlfkf21kp9bqk32a0","message":"connection removed, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:39342\" close fs error: <nil>, num open connections: 0"}
{"level":"debug","time":"2025-02-18T08:56:30.386","sender":"DAV","connection_id":"DAV_cuptlfkf21kp9bqk32ag","message":"connection added, local address \"127.0.0.1:30001\", remote address \"127.0.0.1:39342\", num open connections: 1"}
{"level":"debug","time":"2025-02-18T08:56:30.387","sender":"DAV","connection_id":"DAV_cuptlfkf21kp9bqk32ag","message":"transfer added, id: 1, active transfers: 1"}
`

**Comment by warmenhoven** [comment]
@troilus Can you try again with 1.21 and send me the logs? I think I fixed some stuff.

@Salokyn android didn't support ssl until today, but did support non-ssl webdav cloud sync in 1.20.

**Comment by MC-loud** [comment]
Not fixed, HTTP works but not HTTPS.
There's nothing relevant in the log besides an HTTP -1 status code.
Tried on both desktop 1.22.2-1.1 and android 1.22.

**Comment by Salokyn** [comment]
Works for me now in HTTPS on Android 13 with v1.22

**Comment by MC-loud** [comment]
[webdav] Failed: https://sftp.nas.homelab.test/RetroArch/: HTTP -1

[CloudSync] Begin failed.

**Comment by fernio** [comment]
By looking at the code of the `webdav_sync_begin()` function, it seems to me only Basic auth is supported (independent of using HTTP or HTTPS). I also encountered the "CloudSync Begin failed" error with a WebDAV server I spun up in my local network using Digest authentication, and fixed it by changing authentication to Basic.

**Comment by warmenhoven** [comment]
Digest is supported as well, I use digest on my WebDAV server. It tries basic first because it needs information from the server before attempting digest. If you attach a log I can try to see if there's something going wrong with it.

**Comment by fernio** [comment]
I don't have the log now, but it was basically the same as what MC-loud posted, except that my URL was plain HTTP, not HTTPS.

**Comment by marksherman** [comment]
I'm having a similar problem which I think may be the same bug, whatever it is. RetroArch 1.22.2 on Android - stuck at `Cloud Sync in progress 0%`. It starts immediately upon start of RetroArch and stays at 0% seemingly forever.

I tried RetroArch on another computer, running MacOS 26, and it also instantly gets stuck at 0%, exactly the same.

Looking at the server log, the only times the android device even hit the server was when I was using a different app, meaning _retroarch isn't even trying the server._

The webdav share is working. I can access it from the android device in another app no problem (Cx File Explorer). Can read and write from that other app and from other machines. The webdav folder is empty.

HTTP, digest authentication, Apache. 

My server is running on the local LAN. It has single-name DNS resolution (as evidenced by the other app seeing it correctly), but I tried putting in the IP address as well. Definitely including the trailing slash. Zillion-checked the username and password.



I'm going to plug it in to wall power and let it cook for a while and see if anything happens, but it hasn't so far and I've been going at this for a while. 

Here's a log file, set to debug. I cut out a repetitious line about android video. There's nothing in here even mentioning cloud sync, mirroring what others above have said.

```
Using old --libretro behavior. Setting libretro_directory to "/data/data/com.retroarch/cores/" instead.
RetroArch 1.22.2 (Git eafea9a)
=== Build =======================================
Capabilities: NEON VFPV3 VFPV4
[INFO] Version: 1.22.2
[INFO] Git: eafea9a
[INFO] Built: Dec 11 2025
[INFO] =================================================
[Input] Found input driver: "android".
[Environ] SET_PIXEL_FORMAT: RGB565.
[Core] Version of libretro API: 1, Compiled against API: 1
[Core] Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[Video] Set video size to: 960x720.
[Android] EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay.
[EGL] EGL version: 1.4.
[GL] Found GL context: "egl_android".
[GL] Config requires windowed mode, but context driver does not support it. Forcing fullscreen for this session.
[GL] Detecting screen resolution: 0x0.
[EGL] Current context: 0xaf82f8b0.
[GL] Vendor: NVIDIA Corporation, Renderer: NVIDIA Tegra.
[GL] Version: OpenGL ES 2.0 17.01214.
[GL] Using resolution 1280x720.
[GL] Default shader backend found: glsl.
[GL] Using GLSL shader backend.
[GLSL] Stock GLSL shaders will be used.
[GLSL] Found GLSL vertex shader.
[GLSL] Found GLSL fragment shader.
[GLSL] Linking GLSL program.
[GLSL] Found GLSL vertex shader.
[GLSL] Found GLSL fragment shader.
[GLSL] Linking GLSL program.
[GLSL] Found GLSL vertex shader.
[GLSL] Found GLSL fragment shader.
[GLSL] Linking GLSL program.
[GL] Using 4 textures.
[GL] Loaded 1 program(s).
[Input] Found joypad driver: "android".
[Video] Found display server: "android".
[Audio] Set audio input rate to: 48000.00 Hz.
[OpenSL] Requested audio latency: 128 ms.
[OpenSL] Setting audio latency: Block size = 4096, Blocks = 6, Total = 24576...
[Audio] Started synchronous audio driver.
[Display] Found display driver: "gl".
[Playlist] Loading favorites file: "/storage/emulated/0/RetroArch/playlists/builtin/content_favorites.lpl".
[Playlist] Loading history file: "/storage/emulated/0/RetroArch/playlists/builtin/content_history.lpl".
[Playlist] Loading history file: "/storage/emulated/0/RetroArch/playlists/builtin/content_image_history.lpl".
[Playlist] Loading history file: "/storage/emulated/0/RetroArch/playlists/builtin/content_music_history.lpl".
[Input] Grab mouse state => ON
[Audio] Stopped audio driver "opensl".
[EGL] Current context: 0xaf82f8b0.
```

**Comment by marksherman** [comment]
and thank you! I love everything you do and why you do it.

**Comment by marksherman** [comment]
Interesting: if I change the webdav server url to include `http://` it DOES hit the server, then immediately fail. 

Looking at the RetroArch log, it's hitting the server, and getting an unauthorized error! That's something.

Here's the relevant bit from the log:
```
[webdav] Failed: http://192.168.1.11/webdav/: HTTP 401
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<hr>
<address>Apache/2.4.66 (Debian) Server at 192.168.1.11 Port 80</address>
</body></html>

[CloudSync] Begin failed.
```

The corresponding event in the Apache server's access log:
```
192.168.1.216 - - [21/Mar/2026:20:58:36 +0000] "OPTIONS /webdav/ HTTP/1.1" 401 793 "-" "libretro"
```
Each "sync now" or restart of the app gets exactly one line of the above.

Maybe RetroArch doesn't support Digest type authentication after all, as suspected above.

**Comment by marksherman** [comment]
SOLVED FOR ME: 
- You must specify the protocol in the webdav address, `http://` (the instructions don't specify this)
- The server must use Basic authentication (the instructions also don't mention this but they're not specific to apache)

🤦
