### ISSUE TITLE
Can't launch games externally on Android as of the 2025-01-17 nightly release unless the complete core path is passed

### ISSUE THREAD

**Issue by leonstyhre** [libretro/RetroArch#17433]
### Is there an existing issue for this?

- [x] This is a bug in RetroArch frontend
- [x] I have searched the existing issues

### Description

On Android,  all cores fail to load when launched externally (from a frontend or via the am command) as of the 2025-01-17-RetroArch_aarch64.apk nightly build unless the complete path to the core file is included in the Intent. It works fine in 2025-01-16-RetroArch_aarch64.apk and earlier. 

### Expected behavior

Doing something like the following should work:

`am start -n com.retroarch.aarch64/com.retroarch.browser.retroactivity.RetroActivityFuture -e CONFIGFILE /storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg -e LIBRETRO mesen_libretro_android.so -e ROM /storage/emulated/0/ROMs/nes/1942.zip`

And this has worked fine up until the 2025-01-17 nightly build.
To make game launching work in the latest nighly builds, the following is required:

`am start -n com.retroarch.aarch64/com.retroarch.browser.retroactivity.RetroActivityFuture -e CONFIGFILE /storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg -e LIBRETRO /data/data/com.retroarch.aarch64/cores/mesen_libretro_android.so -e ROM /storage/emulated/0/ROMs/nes/1942.zip`

As you can see the path to the core file is passed in the second example.

### Steps to reproduce the bug

Running any game/core using the am command without passing the entire path to the core file, such as this:

`am start -n com.retroarch.aarch64/com.retroarch.browser.retroactivity.RetroActivityFuture -e CONFIGFILE /storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg -e LIBRETRO mesen_libretro_android.so -e ROM /storage/emulated/0/ROMs/nes/1942.zip`

### Version/Commit

1.20.0 (Git 48d903e)

### Present in the nightly version

Yes, this is reproduced in the nightly build

### Platform & operating system

Android

### Affected Cores

All cores

### Environment information

Any Android device.

### Relevant log output

```shell

```

**Comment by Jetup13** [comment]
Can confirm. Log:

```
=== Build =======================================
Capabilities: ASIMD 
[INFO] Version: 1.20.0
[INFO] Git: 5db9b7f
[INFO] Built: Jan 19 2025
[INFO] =================================================
[Core]: Frontend is built for dynamic libretro cores, but path is not set. Cannot continue.
Fatal error received in: "init_libretro_symbols()"
```

Might be related to commit 69ceb95?

**Comment by zoltanvb** [comment]
Thank you for the quick and precise issue report! I spent some time looking into it, but found eventually that it is already fixed by #17431 , so next nightly should be OK already, hand-built version looks good:

```
DDV_sprout:/ $ cat /sdcard/RetroArch/logs/retroarch__2025_01_19__21_50_23.log                                                      
--libretro argument "mesen_libretro_android.so" matches core file "/data/user/0/com.retroarch.aarch64/cores/mesen_libretro_android.so".
RetroArch 1.20.0 (Git 274cd419fa)
=== Build =======================================
Képességek: ASIMD 
[INFO] Version: 1.20.0
[INFO] Git: 274cd419fa
[INFO] Built: Jan 19 2025
[INFO] =================================================
[Input]: Found input driver: "android".
[Core]: Loading dynamic libretro core from: "/data/user/0/com.retroarch.aarch64/cores/mesen_libretro_android.so"

```

**Comment by leonstyhre** [comment]
Thanks a lot! I tested the nightly build from a few hours back and I can confirm that the problem is gone! It caused quite a big problem for our frontend (ES-DE) so really nice that it's fixed :)

**Comment by leonstyhre** [comment]
Hi! It seems like the issue is back again in the nightly build, @zoltanvb could you perhaps investigate this? Many thanks in advance!

**Comment by leonstyhre** [comment]
Actually I'm not entirely sure if this issue has reoccured, it got reported to me by a user and I could reproduce it on one device but after removing and installing the latest nightly build again it worked, and on another device there were no problems at all. Could it be that somehow making an upgrade to the nightly build causes issues and reinstalling it completely fixes it again? Anyway I'll see if more people report the problem, and if it's not a concern I'll go ahead and close this issue again.

**Comment by leonstyhre** [comment]
This was probably a false alarm somehow, I'll go ahead and close the issue again!
