### ISSUE TITLE
Scanning causes a crash

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [libretro/RetroArch#17548]
### Is there an existing issue for this?

- [x] This is a bug in RetroArch frontend
- [x] I have searched the existing issues

### Description

Whenever I scan on my phone, the app crashes. I’m using SideStore, is there a workaround for this?

https://github.com/user-attachments/assets/44d5eade-70cd-44bf-83cb-0bcdd79e82a7

### Expected behavior

The rom file should be scanned correctly.

### Steps to reproduce the bug

Null

### Version/Commit

You’ll find out in the video

### Present in the nightly version

Yes, this is reproduced in the nightly build

### Platform & operating system

iOS-arm64

### Relevant log output

```shell

```

**Comment by warmenhoven** [comment]
Looks like it's dying trying to scan a file inside a zip;

![image](https://github.com/user-attachments/assets/00770de6-261d-47dc-af53-12dc52acbe67)

**Comment by Iamthebestintheworld222** [comment]
It also crashes when scanning uncompressed romshttps://github.com/user-attachments/assets/218e3442-ff25-4432-a33b-ab4d5aeb0aee

**Comment by LibretroAdmin** [comment]
https://github.com/libretro/RetroArch/commit/56d3042efd62fbbf91ee6ee84b2f6071904f9729

There's a possibility the next nightly will fix it

**Comment by mitchirhd** [comment]
If somebody comes across this because they have this issue on Linux, try Proton.
Launching Retroarch with Proton (I tried with 10.0-4) and scanning seems to work. Afterwards you can swap back to native and all the content will still be there. To get out of the Proton prefix and find my roms when scanning I had to select the Z: drive, from there on it's the Linux filesystem.

**Comment by gouchi** [comment]
@Iamthebestintheworld222 is it fixed with nightly ? Thank you.

**Comment by MatGS-Minty** [comment]
Sadly this is still an issue on the latest iOS with the latest Appstore Retroarch version.
Retroarch crashes without error when scanning certain directories. I haven't found out which files cause the crash yet.
