### ISSUE TITLE
[Crash] Unable to run anything on Citra Android

### ISSUE THREAD

**Issue by acidion-ad** [libretro/RetroArch#17585]
### Is there an existing issue for this?

- [x] This is a bug in RetroArch frontend
- [x] I have searched the existing issues

### Description

App exits after the starting splash appears for all the various games (unencrypted) I have tried. Enabling 'Hardware Shared Context' makes no difference (I have seen this recommendation is several posts).

Both Citra and Citra 2018 cores work on PC, without issue, using the same 3ds files so this appears to be an android issue specifically. 

I have tried both available 'Citra' cores on Android (https://github.com/libretro/RetroArch/issues/17584) and one fails harder than the other.
 
The first Core can't even make it to the splash screen and exits the app cutting off logging.
https://pastebin.com/yBEv9Rvi
The 2nd core displays splash screen and then exits the app.
https://pastebin.com/FxK7Nn1U

> Render.OpenGL @ video_core/renderer_opengl/gl_shader_util.cpp:LoadProgram:101: Error linking shader:
> Error: Image Image location or component exceeds max allowed.
> Error: Linking failed.
> Debug @ video_core/renderer_opengl/gl_shader_util.cpp:operator():105: Assertion Failed!
> Shader not linked

This gentleman has the same reported issue, not so long ago, with no resolution provided - https://www.reddit.com/r/RetroArch/comments/1icdg38/i_cant_emulate_3dsupdate/

I can see no other issues reporting this problem so I presume it is something new or a very specific issue. Can anyone confirm they are successfully running 3DS emulation on an Android phone/device using the _current RetroArch_ version with the _currently provided cores_?

### Expected behavior

app does not crash when starting emulation

### Steps to reproduce the bug

1. Emulate a game using either of the available Citra cores (Android) 

### Version/Commit

1.20.0

### Present in the nightly version

I don't know

### Platform & operating system

Android 14

### Affected Cores

Citra

### Environment information

* Android 14
* ROG Phone 8 Pro 

### Relevant log output

```shell
Using old --libretro behavior. Setting libretro_directory to "/data/user/0/com.retroarch/cores/" instead.
RetroArch 1.20.0 (Git 6412f4feef)
=== Build =======================================
Capabilities: ASIMD 
[INFO] Version: 1.20.0
[INFO] Git: 6412f4feef
[INFO] Built: Jan  4 2025
[INFO] =================================================
[Input]: Found input driver: "android".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Version of libretro API: 1, Compiled against API: 1
[Core]: Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[Video]: Set video size to: 960x720.
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.5
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x7599c98e90.
[GL]: Vendor: Qualcomm, Renderer: Adreno (TM) 750.
[GL]: Version: OpenGL ES 3.2 V@0762.18 (GIT@af856151b0, Id776b0abd7, 1714112817) (Date:04/26/24).
[GL]: Using resolution 1080x2400.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[Audio]: Set audio input rate to: 48000.00 Hz.
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 768, Blocks = 32, Total = 24576 ...
[Audio]: Started synchronous audio driver.
[Display]: Found display driver: "gl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_music_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_image_history.lpl".
[Playlist]: Loading favorites file: "/storage/emulated/0/Android/data/com.retroarch/files/content_favorites.lpl".
[Input]: Grab mouse state => ON
[Content]: Updating firmware status for: "/data/user/0/com.retroarch/cores/citra_libretro_android.so" on "/storage/emulated/0/RetroArch/system".
[Core]: Using content: "/storage/emulated/0/RetroArch/downloads/Stella Glow (USA).3ds".
[Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[Core]: Unloading core..
[Core]: Unloading core symbols..
RetroArch 1.20.0 (Git 6412f4feef)
=== Build =======================================
Capabilities: ASIMD 
[INFO] Version: 1.20.0
[INFO] Git: 6412f4feef
[INFO] Built: Jan  4 2025
[INFO] =================================================
[Input]: Found input driver: "android".
[Core]: Loading dynamic libretro core from: "/data/user/0/com.retroarch/cores/citra_libretro_android.so"
[Overrides]: Redirecting save file to "/storage/emulated/0/RetroArch/saves/Citra/Stella Glow (USA).srm".
[Overrides]: Redirecting save state to "/storage/emulated/0/RetroArch/states/Citra/Stella Glow (USA).state".
[Environ]: GET_VFS_INTERFACE. Core requested version >= V1, providing V3.
[Environ]: SET_VARIABLES.
[Environ]: SET_CONTROLLER_INFO.
[Environ]: GET_LOG_INTERFACE.
[Content]: Content loading skipped. Implementation will load it on its own.
[Environ]: SET_HW_SHARED_CONTEXT.
[Environ]: SET_PIXEL_FORMAT: XRGB8888.
[Environ]: SET_HW_RENDER, context type: gl.
Requesting OpenGLES3 context.
[Environ]: SET_INPUT_DESCRIPTORS:
[Environ]: SAVE_DIRECTORY: "/storage/emulated/0/RetroArch/saves/Citra".
Frontend @ citra_libretro/citra_libretro.cpp:retro_load_game:596: Starting Citra RetroArch game...
[Environ]: SET_GEOMETRY: 400x480, Aspect: 0.833.
Common.Filesystem @ common/file_util.cpp:SetUserPath:713: Using /storage/emulated/0/RetroArch/saves/Citra/Citra/ as the user directory
Frontend @ citra_libretro/citra_libretro.cpp:UpdateSettings:447: User dir set to "/storage/emulated/0/RetroArch/saves/Citra/Citra/".
RPC_Server @ core/rpc/rpc_server.cpp:RPCServer:12: Starting RPC server ...
RPC_Server @ core/rpc/rpc_server.cpp:HandleRequestsLoop:113: Request handler started.
RPC_Server @ core/rpc/rpc_server.cpp:RPCServer:16: RPC started.
Service.NWM @ core/hle/service/nwm/nwm_uds.cpp:NWM_UDS:1518: Network isn't initalized
Service.HTTP @ core/hle/service/http_c.cpp:DecryptClCertA:806: ClCertA file missing
Core @ core/telemetry_session.cpp:GetTelemetryId:47: failed to open telemetry_id: /storage/emulated/0/RetroArch/saves/Citra/Citra/config/telemetry_id
Loader @ core/loader/ncch.cpp:Load:192: Program ID: 0004000000173700
Service.FS @ core/file_sys/ncch_container.cpp:OpenFile:130: Failed to open /storage/emulated/0/RetroArch/saves/Citra/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/00173700/content/00000000.app
Loader @ core/hle/kernel/process.cpp:ParseKernelCaps:141: ExHeader kernel version: 2.50
Service.CFG @ core/hle/service/cfg/cfg.cpp:SetPreferredRegionCodes:660: Preferred region code set to 1
[SRAM]: Skipping SRAM load.
[Core]: Version of libretro API: 1, Compiled against API: 1
[Core]: Geometry: 400x480, Aspect: 0.000, FPS: 60.00, Sample rate: 32728.00 Hz.
[Video]: Set video size to: 900x1080.
[Video]: Using HW render, OpenGL driver forced.
[Video]: Using configured "gl" driver for GL HW render.
Android EGL: GLES version = 3.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.5
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Created shared context: 0x7599ca6a80.
[EGL]: Current context: 0x7599ca70b0.
[GL]: Vendor: Qualcomm, Renderer: Adreno (TM) 750.
[GL]: Version: OpenGL ES 3.2 V@0762.18 (GIT@af856151b0, Id776b0abd7, 1714112817) (Date:04/26/24).
[GL]: Using resolution 1080x2400.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 1 textures.
[GL]: Loaded 1 program(s).
[GL]: Initializing HW render (8192x8192).
[GL]: Max texture size: 16384 px, renderbuffer size: 16384 px.
[GL]: Supports FBO (render-to-texture).
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
Render.OpenGL @ video_core/renderer_opengl/renderer_opengl.cpp:Init:988: GL_VERSION: OpenGL ES 3.2 V@0762.18 (GIT@af856151b0, Id776b0abd7, 1714112817) (Date:04/26/24)
Render.OpenGL @ video_core/renderer_opengl/renderer_opengl.cpp:Init:989: GL_VENDOR: Qualcomm
Render.OpenGL @ video_core/renderer_opengl/renderer_opengl.cpp:Init:990: GL_RENDERER: Adreno (TM) 750
Render.OpenGL @ video_core/renderer_opengl/gl_format_reinterpreter.cpp:ShaderD24S8toRGBA8:292: Texture views are unsupported, reinterpretation will do intermediate copy
Render.OpenGL @ video_core/renderer_opengl/gl_format_reinterpreter.cpp:FormatReinterpreterOpenGL:378: Using shader for D24S8 to RGBA8 reinterpretation
Render.OpenGL @ video_core/renderer_opengl/gl_shader_manager.cpp:LoadDiskCache:446: Cannot load disk cache as separate shader programs are unsupported!
[Environ]: SET_GEOMETRY: 400x480, Aspect: 0.833.
[Audio]: Set audio input rate to: 32728.00 Hz.
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 768, Blocks = 32, Total = 24576 ...
[Audio]: Started synchronous audio driver.
[Display]: Found display driver: "gl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_music_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_image_history.lpl".
[Playlist]: Loading favorites file: "/storage/emulated/0/Android/data/com.retroarch/files/content_favorites.lpl".
Service.SRV @ core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11
Service.SRV @ core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called
Service.APT @ core/hle/service/apt/apt.cpp:GetLockHandle:317: (STUBBED) called applet_attributes=0X00000000
Service.APT @ core/hle/service/apt/apt.cpp:SetScreenCapPostPermission:804: (STUBBED) called, screen_capture_post_permission=0
Service.NDM @ core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:186: (STUBBED) bit_mask=0x0000000F
Service.NDM @ core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000006
Service.APT @ core/hle/service/apt/apt.cpp:NotifyToWait:296: (STUBBED) app_id=768
Service.APT @ core/hle/service/apt/apt.cpp:AppletUtility:592: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
Service.APT @ core/hle/service/apt/apt.cpp:AppletUtility:592: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
Service.FS @ core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:600: (STUBBED) called, version: 0x0B0300C8
Service.FS @ core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
Service.FS @ core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
Service.FS @ core/file_sys/savedata_archive.cpp:CreateFile:233: /storage/emulated/0/RetroArch/saves/Citra/Citra/nand/data/00000000000000000000000000000000/extdata/00048000/F000000B/user/gamecoin.dat already exists
Service.PTM @ core/hle/service/ptm/ptm.cpp:GetTotalStepCount:107: (STUBBED) called
Service.GSP @ core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:706: called flag=00000000 process=11 thread_id=0
Render.OpenGL @ video_core/renderer_opengl/gl_rasterizer_cache.cpp:MortonCopy:188: Out of bound texture
Service.DSP @ audio_core/hle/hle.cpp:LoadComponent:497: Firmware hash: 0xdcdb8c683bf28fdd
Service.DSP @ audio_core/hle/hle.cpp:LoadComponent:501: Structures hash: 0x228655de1258d999
Service.DSP @ core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:189: called size=0xC25C, prog_mask=0x000000FF, data_mask=0x000F00FF
Service.DSP @ core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:255: Registered interrupt=2, channel=2, event=event-00133b28
Service.DSP @ core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:271: (STUBBED) called
Service.DSP @ core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:281: (STUBBED) called mask=0x2000
Audio.DSP @ audio_core/hle/hle.cpp:PipeWrite:257: Application has requested initialization of DSP hardware
Service.DSP @ core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
Service.DSP @ core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
Service.APT @ core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:607: (STUBBED) called, cpu_percent=30, value=1
Service.Y2R @ core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:212: (STUBBED) called
Render.OpenGL @ video_core/renderer_opengl/gl_shader_util.cpp:LoadProgram:101: Error linking shader:
Error: Image Image location or component exceeds max allowed.
Error: Linking failed.
Debug @ video_core/renderer_opengl/gl_shader_util.cpp:operator():105: Assertion Failed!
Shader not linked
```

**Comment by lim2222** [comment]
Crash due to permission denied,why?

Using old --libretro behavior. Setting libretro_directory to "/data/user/0/com.retroarch/cores/" instead.
RetroArch 1.20.0 (Git a6ea47d)
=== Build =======================================
容量: ASIMD 
[INFO] Version: 1.20.0
[INFO] Git: a6ea47d
[INFO] Built: Feb 13 2025
[INFO] =================================================
[Input]: Found input driver: "android".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: libretro API 版本: 1, 未按照 API 编译: 1
[Core]: Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[Video]: Set video size to: 768x720.
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.5
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x78ae89d880.
[GL]: Vendor: Qualcomm, Renderer: Adreno (TM) 650.
[GL]: Version: OpenGL ES 3.2 V@444.0 (GIT@a676c8e, I49c2a65814, 1602779917) (Date:10/15/20).
[GL]: Using ARB_sync to reduce latency.
[GL]: Using resolution 1080x2310.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[Audio]: Set audio input rate to: 48000.00 Hz.
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 576, Blocks = 43, Total = 24768 ...
[Audio]: Started synchronous audio driver.
[Display]: Found display driver: "gl".
[Playlist]: 正在读取历史文件: "/storage/emulated/0/Android/data/com.retroarch/files/content_history.lpl".
[Playlist]: 正在读取历史文件: "/storage/emulated/0/Android/data/com.retroarch/files/content_music_history.lpl".
[Playlist]: 正在读取历史文件: "/storage/emulated/0/Android/data/com.retroarch/files/content_image_history.lpl".
[Playlist]: 正在加载收藏文件: "/storage/emulated/0/Android/data/com.retroarch/files/content_favorites.lpl".
[Content]: Updating firmware status for: "/data/user/0/com.retroarch/cores/citra_libretro.so" on "/storage/emulated/0/RetroArch/system".
[Core]: Using content: "/storage/emulated/0/3DS/Taiko no Tatsujin Don to Katsu no Jikuu Daibouken.3ds".
[Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[Core]: Unloading core..
[Core]: Unloading core symbols..
RetroArch 1.20.0 (Git a6ea47d)
=== Build =======================================
容量: ASIMD 
[INFO] Version: 1.20.0
[INFO] Git: a6ea47d
[INFO] Built: Feb 13 2025
[INFO] =================================================
[Input]: Found input driver: "android".
[Core]: Loading dynamic libretro core from: "/data/user/0/com.retroarch/cores/citra_libretro.so"
[Overrides]: Core-specific overrides found at "/storage/emulated/0/RetroArch/config/Citra/Citra.cfg".
[Overrides]: Game-specific overrides found at "/storage/emulated/0/RetroArch/config/Citra/Taiko no Tatsujin Don to Katsu no Jikuu Daibouken.cfg".
[Overrides]: Game-specific overrides stacking on top of previous overrides.
[Config]: Loading config: "/storage/emulated/0/Android/data/com.retroarch/files/retroarch.cfg".
[Config]: Appending override config: "/storage/emulated/0/RetroArch/config/Citra/Citra.cfg".
[Config]: Appending override config: "/storage/emulated/0/RetroArch/config/Citra/Taiko no Tatsujin Don to Katsu no Jikuu Daibouken.cfg".
[Overrides]: 重定向游戏存档文件至 "/storage/emulated/0/RetroArch/saves/Citra/Taiko no Tatsujin Don to Katsu no Jikuu Daibouken.srm".
[Overrides]: 正在重定向状态存储至 "/storage/emulated/0/RetroArch/states/Citra/Taiko no Tatsujin Don to Katsu no Jikuu Daibouken.state".
[Environ]: GET_VFS_INTERFACE. Core requested version >= V1, providing V3.
[Environ]: SET_VARIABLES.
[Core]: 发现游戏特定的核心选项 "/storage/emulated/0/RetroArch/config/Citra/Taiko no Tatsujin Don to Katsu no Jikuu Daibouken.opt".
[Environ]: SET_CONTROLLER_INFO.
[Environ]: GET_LOG_INTERFACE.
[Content]: 跳过游戏加载。实现将自行加载。
[Environ]: SET_INPUT_DESCRIPTORS:
[Environ]: SET_GEOMETRY: 400x480, Aspect: 0.833.
[   0.004057] Frontend <Info> citra_libretro/citra_libretro.cpp:retro_load_game:664: Starting Citra RetroArch game...
[Environ]: SET_PIXEL_FORMAT: XRGB8888.
[Environ]: SET_HW_SHARED_CONTEXT.
[Environ]: SET_HW_RENDER, context type: gl.
Requesting OpenGLES3 context.
[   0.004146] Frontend <Info> citra_libretro/citra_libretro.cpp:retro_load_game:685: Using OpenGL hw renderer
[   0.004638] Loader <Warning> core/loader/loader.cpp:GetLoader:129: File /storage/emulated/0/3DS/Taiko no Tatsujin Don to Katsu no Jikuu Daibouken.3ds has a different type than its extension.
[   0.004764] Common.Filesystem <Error> common/file_util.cpp:CreateDir:267: mkdir failed on /data/.local/: Permission denied
[   0.004772] Common <Error> common/file_util.cpp:CreateFullPath:293: CreateFullPath: directory creation failed

**Comment by daliang987** [comment]
When you open the emulator, you have a few seconds to quickly go to the shortcut menu in the emulator, find the core options, turn off all the options related to shader, and you can play the game

**Comment by pudup** [comment]
My log is different but the newest version of citra core crashes instantly on selecting a ROM. The log has nothing interesting, simply crashes after selecting renderer.
Earlier versions run fine, if manually added to cores folder in root.

**Comment by pudup** [comment]
Leaving another comment to say my issue in my comment above this is now fixed. The citra core updated many times and it works as of the update I got at the time of this comment.

**Comment by acidion-ad** [comment]
> Leaving another comment to say my issue in my comment above this is now fixed. The citra core updated many times and it works as of the update I got at the time of this comment.

Thanks for the update. I've refreshed my cores and it now loads into game. I am still crashing in-game once past menus etc but it's progress (tested 3 games). This tells me it's a core issue not an RA issue. Originally I raised this as an RA issue as it worked on PC but not on Android, that no longer appears to be the case.
