### ISSUE TITLE
No Vulkan HDR metadata (causes brightness issues on linux)

### ISSUE THREAD

**Issue by CallieEZ** [libretro/RetroArch#18186]
### Is there an existing issue for this?

- [x] This is a bug in RetroArch frontend
- [x] I have searched the existing issues

### Description

Enabling HDR on linux using KDE's built in HDR support results in overbrightened colors. This is most likely related to how mesa handles the brightness of VK_COLOR_SPACE_HDR10_ST2084_EXT differently compared to the windows implementation, as detailed in this issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/12689. This issue can be circumvented for now by using http://github.com/Zamundaaa/VK_hdr_layer and running retroarch with ENABLE_HDR_WSI=1. 

### Steps to reproduce the bug

1. Boot retroarch with HDR enabled using the vulkan video driver on plasma 6.4
2. Enable HDR in video settings
3. Observe extremely inaccurate and bright colors 

### Version/Commit

1.20.0

### Present in the nightly version

I don't know

### Platform & operating system

Linux AMD64

### Relevant log output

```shell

```

**Comment by gouchi** [comment]
Hi,

Can you make a test with [nightly build](https://buildbot.libretro.com/nightly/linux/x86_64/RetroArch.7z) ? And provide some [log](https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-in-linux).

Also if possible to provide some screenshots ?

Thank you.

**Comment by matheuswillder** [comment]
I can confirm that this issue also occurs in Gnome (log file at the end).

For some reason, the HDR option doesn't appear in the AppImage build, either the latest stable or the nightly one above, but it does appear in the Flatpak build, so the videos below are from that.

Video showing the issue described (if the video doesn't load, right click on it>Save video as..., save it to some folder and open it with a player):

https://github.com/user-attachments/assets/89b5542e-aa88-42e4-9b8f-cf91bdf53ba7

Also, I don't know if this is the same issue as above, but with HDR enabled, if I load an HDR shader (/shaders_slang/hdr folder), the menu background image has the colors distorted. This is particularly noticeable in the XMB menu, as it allows you to use a custom background image, but it also occurs in the Ozone menu, where it change the background to solid black, and if I use a On-Screen Overlay (like RGPad), its colors change as well. This also occurs on Android.

Video showing this (also in Gnome) (if the video doesn't load, right click on it>Save video as..., save it to some folder and open it with a player):

https://github.com/user-attachments/assets/95fb50a7-daef-4843-94bc-3eeb3a0d72c4

Video showing this (Android) (if the video doesn't load, right click on it>Save video as..., save it to some folder and open it with a player):

https://github.com/user-attachments/assets/8079b27f-44df-4c0e-8625-9ef2f8edb17a

I couldn't generate a log using those commands in the Flatpak build, but I enabled logging in the settings, closed RetroArch, opened it, and followed exactly the steps in the first video (open RetroArch, enable HDR, load the ROM, waited a few seconds, and closed it).

[retroarch__2025_08_19__23_01_03.log](https://github.com/user-attachments/files/21873734/retroarch__2025_08_19__23_01_03.log)

I noticed all of this a few weeks ago. I was trying to set up an HDR shader, but the results weren't good. [After exchanging some comments with CyberLabSystems on the RetroArch subreddit](https://www.reddit.com/r/RetroArch/comments/1lq7fwj/comment/n18j7zd/), I noticed that HDR was buggy in RetroArch on Linux.

But due to personal issues I'm short on time at the moment, so just now I made these videos and posted the log. I hope this helps fix the issue.

Edit: I've added a video showing the issue on Android. The HDR shader actually appears to be working correctly, but the background image and overlay aren't (notice that the B button, which should be yellow, turns red after loading the HDR shader).

Also, since the HDR option doesn't appear in the AppImage build, I think the best way to test this would be to use the Flathub test builds: https://github.com/flathub/org.libretro.RetroArch. I can do more testing if needed when I have some free time.

**Comment by gouchi** [comment]
@MajorPainTheCactus @CRefice might have some input.

Thank you for your help.

**Comment by matheuswillder** [comment]
Looking at the links above, it seems that upgrading Mesa to 25.1 or up should solve the problem.

>NOTE: Mesa 25.1+ implements the color management protocol directly, this Vulkan layer is no longer necessary with that.

This should be easy to do with Flatpak, as it can use its own runtime versions regardless of the version installed on the system. @RobLoach, should I open an issue about it in https://github.com/flathub/org.libretro.RetroArch?

**Comment by Zamundaaa** [comment]
> Enabling HDR on linux using KDE's built in HDR support results in overbrightened colors. This is most likely related to how mesa handles the brightness of VK_COLOR_SPACE_HDR10_ST2084_EXT differently compared to the windows implementation, as detailed in this issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/12689. This issue can be circumvented for now by using [http://github.com/Zamundaaa/VK_hdr_layer](https://github.com/Zamundaaa/VK_hdr_layer) and running retroarch with ENABLE_HDR_WSI=1.

The Vulkan layer shouldn't behave differently from Mesa, it does exactly the same for PQ. Only scRGB is handled differently (on compositors that support it).

This issue probably comes down to two things:
- RetroArch doesn't seem to set any HDR metadata, which is often required for properly displaying HDR content
- your configuration is most likely wrong. Indeed, Wayland (and MacOS, and Android, really everything except Windows) does HDR differently from Windows. For correct behavior, you need either
    - paper white and max luminance to both match the Wayland compositor. Vulkan has no way to set that, so that would likely be a bit larger change in RetroArch; you'd need to use `VK_COLOR_SPACE_PASS_THROUGH_EXT` in Vulkan and set colorspace data through Wayland directly instead. OR
    - paper white to be 203 (for PQ), and peak luminance to be `preferred_peak * 203 / preferred_reference`. The preferred HDR metadata of a window can be looked up with the Wayland color management protocol's `wp_color_management_surface_feedback_v1`

Ideally, Retroarch would just hide the HDR luminance settings on Wayland and always automatically use the compositor settings.

**Comment by CallieEZ** [comment]
> > Enabling HDR on linux using KDE's built in HDR support results in overbrightened colors. This is most likely related to how mesa handles the brightness of VK_COLOR_SPACE_HDR10_ST2084_EXT differently compared to the windows implementation, as detailed in this issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/12689. This issue can be circumvented for now by using [http://github.com/Zamundaaa/VK_hdr_layer](https://github.com/Zamundaaa/VK_hdr_layer) and running retroarch with ENABLE_HDR_WSI=1.
> 
> The Vulkan layer shouldn't behave differently from Mesa, it does exactly the same for PQ. Only scRGB is handled differently (on compositors that support it).
> 
> This issue probably comes down to two things:
> 
>     * RetroArch doesn't seem to set any HDR metadata, which is often required for properly displaying HDR content
> 
>     * your configuration is most likely wrong. Indeed, Wayland (and MacOS, and Android, really everything except Windows) does HDR differently from Windows. For correct behavior, you need either
>       
>       * paper white and max luminance to both match the Wayland compositor. Vulkan has no way to set that, so that would likely be a bit larger change in RetroArch; you'd need to use `VK_COLOR_SPACE_PASS_THROUGH_EXT` in Vulkan and set colorspace data through Wayland directly instead. OR
>       * paper white to be 203 (for PQ), and peak luminance to be `preferred_peak * 203 / preferred_reference`. The preferred HDR metadata of a window can be looked up with the Wayland color management protocol's `wp_color_management_surface_feedback_v1`
> 
> 
> Ideally, Retroarch would just hide the HDR luminance settings on Wayland and always automatically use the compositor settings.

I have Paperwhite set to 200 in both retroarch and kde and peak set to the same as in kde settings and still get oversaturation.

**Comment by Zamundaaa** [comment]
Then there's likely some additional issue present in your case. Please run
```
WAYLAND_DEBUG=1 retroarch 2>&1 | grep 'image_description'
```
and post the output here.

**Comment by CallieEZ** [comment]
> Then there's likely some additional issue present in your case. Please run
> 
> ```
> WAYLAND_DEBUG=1 retroarch 2>&1 | grep 'image_description'
> ```
> 
> and post the output here.


```
[3660656.630] {mesa vk display queue}  -> wp_color_manager_v1#52.create_parametric_creator(new id wp_image_description_creator_params_v1#67)
[3660656.632] {mesa vk display queue}  -> wp_image_description_creator_params_v1#67.set_primaries_named(6)
[3660656.634] {mesa vk display queue}  -> wp_image_description_creator_params_v1#67.set_tf_named(11)
[3660656.635] {mesa vk display queue}  -> wp_image_description_creator_params_v1#67.create(new id wp_image_description_v1#63)
[3660656.684] {mesa vk display queue} wp_image_description_v1#63.ready(277)
[3660656.689] {mesa vk display queue}  -> wp_color_management_surface_v1#71.set_image_description(wp_image_description_v1#63, 0)
[3660656.692] {mesa vk display queue}  -> wp_image_description_v1#63.destroy()


```

**Comment by Zamundaaa** [comment]
Just to be sure, maybe also add your complete display settings (`kscreen-doctor -o`), but it looks like on the Wayland side everything's correct.

**Comment by CallieEZ** [comment]
> Just to be sure, maybe also add your complete display settings (`kscreen-doctor -o`), but it looks like on the Wayland side everything's correct.

```
Output: 1 DP-1 243fa9e8-9144-4cb1-bbda-0ab8a18f2a50
        enabled
        connected
        priority 1
        DisplayPort
        replication source:0
        Modes:  1:2560x1440@60!  2:2560x1440@240*  3:2560x1440@180  4:2560x1440@144  5:2560x1440@120  6:1920x1200@60  7:1920x1080@240  8:1920x1080@120  9:1920x1080@120  10:1920x1080@100  11:1920x1080@60  12:1920x1080@60  13:1920x1080@60  14:1920x1080@50  15:1920x1080@30  16:1920x1080@30  17:1920x1080@25  18:1920x1080@24  19:1920x1080@24  20:1600x1200@60  21:1680x1050@60  22:1280x1024@60  23:1440x900@60  24:1280x960@60  25:1280x800@60  26:1280x720@60  27:1280x720@60  28:1280x720@50  29:1024x768@75  30:1024x768@60  31:800x600@75  32:800x600@60  33:720x576@50  34:720x576@50  35:720x480@60  36:720x480@60  37:720x480@60  38:720x480@60  39:640x480@75  40:640x480@60  41:640x480@60  42:640x480@60  43:1600x1200@240  44:1280x1024@240  45:1024x768@240  46:1920x1200@240  47:1280x800@240  48:1600x900@60  49:1600x900@240  50:1368x768@60  51:1368x768@240  52:1280x720@240 
        Geometry: 0,0 2560x1440
        Scale: 1
        Rotation: 1
        Overscan: 0
        Vrr: Automatic
        RgbRange: Full
        HDR: enabled
                SDR brightness: 200 nits
                SDR gamut wideness: 0%
                Peak brightness: 630 nits, overridden with: 630 nits
                Max average brightness: 259 nits
                Min brightness: 0.0011 nits
        Wide Color Gamut: enabled
        ICC profile: /home/cncz/XG27AQDMG.icm
        Color profile source: EDID
        Color power preference: prefer efficiency and performance
        Brightness control: supported, set to 100% and dimming to 100%
        Color resolution: automatic (10), range: [8; 16] bits per color
        Allow EDR: unsupported
Output: 2 DP-2 20f02f07-d651-4a37-8e30-7f4e73cbc880
        enabled
        connected
        priority 2
        DisplayPort
        replication source:0
        Modes:  53:2560x1440@165*!  54:2560x1440@144  55:2560x1440@120  56:2560x1440@100  57:2560x1440@60  58:1920x1200@165  59:1920x1080@120  60:1920x1080@120  61:1920x1080@100  62:1920x1080@60  63:1920x1080@60  64:1920x1080@60  65:1920x1080@50  66:1600x1200@165  67:1680x1050@165  68:1280x1024@165  69:1440x900@165  70:1280x800@165  71:1280x720@60  72:1280x720@60  73:1280x720@50  74:1024x768@60  75:800x600@60  76:720x480@60  77:720x480@60  78:640x480@60  79:640x480@60  80:640x480@60  81:1600x1200@60  82:1280x1024@60  83:1024x768@165  84:1920x1200@60  85:1280x800@60  86:1920x1080@165  87:1600x900@60  88:1600x900@165  89:1368x768@60  90:1368x768@165  91:1280x720@165 
        Geometry: 2560,0 2560x1440
        Scale: 1
        Rotation: 1
        Overscan: 0
        Vrr: Automatic
        RgbRange: Full
        HDR: disabled
        Wide Color Gamut: disabled
        ICC profile: /home/cncz/.local/share/DisplayCAL/storage/Monitor_2 #2 2025-08-23 15-51 S XYZLUT+MTX/Monitor_2 #2 2025-08-23 15-51 S XYZLUT+MTX.icc
        Color profile source: sRGB
        Color power preference: prefer efficiency and performance
        Brightness control: supported, set to 100% and dimming to 100%
        Color resolution: automatic (10), range: [8; 16] bits per color
        Allow EDR: unsupported
```

**Comment by Zamundaaa** [comment]
Yeah, nothing wrong or weird there.

**Comment by CallieEZ** [comment]
Guess I'll send in a comparison video just in case the default mode is supposed to look this saturated, any clue how to capture HDR desktop video on kde?

**Comment by Zamundaaa** [comment]
There's unfortunately no way to do that yet. I wanted to look into whether or not it can be added to Pipewire and adding support for it in KWin, but didn't get around to it yet.

**Comment by CallieEZ** [comment]
Here's some tone mapped screenshots for now I guess, not 100% indicative but gets the gist of it (taken with expand gamut off):

No HDR:

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/9d2823bc-ab2f-4e42-b4b4-35c79a475c0a" />

Default HDR (brightness isn't consistent, skin is red-ish, some similar colors are hard to distinguish in highlights):

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/ff5f9d77-1c4f-4946-bb19-3d3d6b9d2aa2" />

HDR WSI (bright but distinguishable, although not in the screenshot, colors are very much in-line with SDR):

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/de856972-f451-4d6c-90e4-1e91557fff87" />

**Comment by Zamundaaa** [comment]
Ah, I think I see what's going on. The WSI layer uses the frog protocol, with which (as of Plasma 6.4) KWin happens to be more forgiving with missing HDR metadata. It will generally work well with that, as long as the screen has enough HDR headroom to perfectly show the image. When it doesn't have enough headroom, it's very bad though.

So adding HDR metadata should take care of this.

**Comment by matheuswillder** [comment]
I think the title of this issue shouldn't mention specifically Linux KDE, since I demonstrated above, even with videos, that this also occurs on Gnome and even Android.

**Comment by gouchi** [comment]
As @matheuswillder demonstrated, @cncz42 can you rename the issue title by removing the fact the issue is only happening on KDE.

@Zamundaaa To fix the issue, do we have to modify something from RA side or it is outside ?

> So adding HDR metadata should take care of this.

Thank you.

**Comment by Zamundaaa** [comment]
This is something you have to do. You can set HDR metadata matching the content through Vulkan

**Comment by gouchi** [comment]
@Zamundaaa so IIUC we will need to query for [VK_EXT_hdr_metadata](https://mesamatrix.net/#ExtensionsthatarenotpartofanyVulkanversion_Extensions/#:~:text=VK_EXT_hdr_metadata) to check if the Vulkan driver support the extension then use [vkSetHdrMetadataEXT](https://docs.vulkan.org/refpages/latest/refpages/source/vkSetHdrMetadataEXT.html) to set the metadata ?

Perhaps in the [vulkan_create_swapchain](https://github.com/libretro/RetroArch/blob/575754d584b6829f747c68f86db67612d4b895ed/gfx/common/vulkan_common.c#L1914) function ?

Thank you.

**Comment by Zamundaaa** [comment]
@gouchi yes, but probably not when creating the swapchain. The metadata needs to match the actually used settings.

You can call `vkSetHdrMetadataEXT` basically anywhere you want before `vkQueuePresentKHR`

**Comment by matheuswillder** [comment]
Just to add some new info here, in the Sony Megatron development thread, we discovered that the issue of wrong colors/broken tonemapping in the image backgrounds that I demonstrated in the videos above is not related to the over brightness issue, [it's a different issue that also occurs in Windows](https://forums.libretro.com/t/sony-megatron-colour-video-monitor/36109/2872). With HDR enabled and an HDR shader loaded, the tonemapping for the entire UI is broken: boxarts/thumbnails, menu driver image background, overlays, etc. Edit: this should take care of it: https://github.com/libretro/RetroArch/pull/18648

And back to the over brightness issue, I also did some tests using HDR in KDE, and at least on my hardware/display, the over brightness issue seems even worse in KDE than in Gnome, and trying to adjust it in the system settings and in the RetroArch/shader settings didn't help. My `kscreen-doctor -o` output:

<details>

```
Output: 1 HDMI-A-1
        enabled
        connected
        priority 1
        HDMI
        Modes:  1:1920x1080@180*!  2:2560x1440@75  3:1920x1080@144  4:1920x1080@120  5:1920x1080@120  6:1920x1080@100  7:1920x1080@60  8:1920x1080@60  9:1920x1080@60  10:1920x1080@50  11:1680x1050@180  12:1280x1024@75  13:1440x900@180  14:1280x800@180  15:1280x720@60  16:1280x720@60  17:1024x768@120  18:1024x768@75  19:1024x768@60  20:800x600@120  21:800x600@75  22:800x600@60  23:720x576@50  24:720x480@60  25:720x480@60  26:640x480@120  27:640x480@75  28:640x480@60  29:640x480@60  30:640x480@60  31:1280x1024@60  32:1280x1024@180  33:1024x768@180  34:1280x800@60  35:1600x900@60  36:1600x900@180  37:1368x768@60  38:1368x768@180  39:1280x720@180 
        Geometry: 0,0 1920x1080
        Scale: 1
        Rotation: 1
        Overscan: 0
        Vrr: Never
        RgbRange: Automatic
        HDR: enabled
                SDR brightness: 301 nits
                SDR gamut wideness: 0%
                Peak brightness: 302 nits
                Max average brightness: 302 nits
                Min brightness: 0.2971 nits
        Wide Color Gamut: enabled
        ICC profile: none
        Color profile source: sRGB
        Color power preference: prefer efficiency and performance
        Brightness control: supported, set to 100% and dimming to 100%

```

</details>

**Comment by MajorPainTheCactus** [comment]
Hi chaps just added some fixes for Vulkan HDR in the currently open PR 'Fixed HDR Vulkan bugs https://github.com/libretro/RetroArch/pull/18658' The changes may very well help with some of this stuff - whilst possibly not directly fixing the hdr meta data stuff.  The Windows Vulkan driver is particularly forgiving of incorrect settings where as Android drivers most definitely aren't (largely because they use a tile based renderer in the hardware) but Linux should see a number of issues disappear.

**Comment by matheuswillder** [comment]
I was testing the current nightly build of RetroArch and the most updated version of Sony Megatron (update it in **Online Updater>Update Slang Shaders**), and I think the colors and brightness with HDR enabled look good enough if I set **Shader Parameters>Colour Space** to **r2020**, all the other colour space options there make the game's colors and brightness look a little washed out/wrong.

HDR needs to be enabled and calibrated correctly in **RetroArch>Settings>Video>HDR**, according to the **Peak Luminance** and **Paper White Luminance** of your monitor/screen.

The shader preset I used was this:

**global.slangp**:
```
#reference "../shaders/shaders_slang/hdr/crt-sony-megatron-v2-default-NTSC.slangp"
cust_artifacting = "0.000000"
cust_fringing = "0.000000"
hcrt_lcd_resolution = "0.000000"
hcrt_colour_space = "4.000000"
hcrt_crt_screen_type = "2.000000"
hcrt_red_scanline_min = "1.000000"
hcrt_red_scanline_max = "1.100000"
hcrt_red_scanline_attack = "0.850000"
hcrt_green_scanline_min = "1.000000"
hcrt_green_scanline_max = "1.100000"
hcrt_green_scanline_attack = "0.850000"
hcrt_blue_scanline_min = "1.000000"
hcrt_blue_scanline_max = "1.100000"
hcrt_blue_scanline_attack = "0.850000"
```

Can anyone else experiencing this issue try it and confirm if it looks correct this way?

Unfortunately, due to the issue in my monitor I've [reported here](https://forums.libretro.com/t/sony-megatron-colour-video-monitor/36109/3070), I won't be using Sony Megatron until I buy a better monitor, but other than that, HDR enabled and the Sony Megatron shaders looks mostly fine now (it's not the same as in SDR, but it also doesn't look completely washed out/wrong like it did before).

System: Debian 14 Forky with Gnome (current Testing)
RetroArch Nightly (06-03-2026 20:20 build)
[Sony Megatron 2.8.0](https://github.com/libretro/slang-shaders/pull/861)

Edit: I tested it in KDE now and the colors and brightness issues still the same with the same build and system as above, so apparently it only work correctly in Gnome for now.

And just to add, you can, but you **don't need** to enable HDR in the system, you just need to enable HDR in RetroArch. If you enable it in the system, you'll first have to calibrate it in the system, and then enable it in RetroArch and calibrate it there as well to get the correct image. Enabling HDR only in RetroArch will give you the correct result more easily.

**Comment by MajorPainTheCactus** [comment]
Hi @matheuswillder, ok so:

"if I set *Shader Parameters>Colour Space* to *r2020*, all the other colour
space options there make the game's colors and brightness look a little
washed out/wrong.

...

but other than that, HDR enabled and the Sony Megatron shaders looks mostly fine now (it's not the same as in SDR, but it also doesn't look completely washed out/wrong like it did before)"

So this shouldn't be correct, rec 2020 should massively over saturate the
image. So we've either got a bug or something else is wrong. The r709
option should be accurate to SDR - SDR should look washed out compared to
r2020 (in HDR). 

So one thing Id recommend is not using the Sony Megatron
for this testing as its quite a complex shader with many moving parts.
Instead we should turn custom shaders off and just use the internal HDR
shader to identify bugs and get things in HDR working. First with scanlines
off and then with scanlines on to identify where bugs might be appearing.

**Comment by matheuswillder** [comment]
Hi @MajorPainTheCactus, thanks for the reply and your work in this.

> So one thing Id recommend is not using the Sony Megatron
> for this testing as its quite a complex shader with many moving parts.
> Instead we should turn custom shaders off and just use the internal HDR
> shader to identify bugs and get things in HDR working. First with scanlines
> off and then with scanlines on to identify where bugs might be appearing.
> […](#)

I can't see any difference when turning scanlines on or off in **Settings>Video>HDR**, should I be seeing something even without any shaders loaded?

But I see a difference in the colors, yes. These screenshots below are taken with the system DE, apparently it capture what I'm seeing on the screen whether in SDR or HDR (I checked it on other device, but sorry if I'm wrong).

SDR:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/dd9a2356-d18a-4b0e-a0bc-aa8999c3d825" />

HDR (scanlines on):
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/be1f8500-0816-46a2-887e-43e0479b51e2" />

HDR (scanlines off):
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/9336f6c5-654b-4c10-9191-96956e0f4050" />

Now, with the shader preset I sent above:

SDR:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c286aef9-71bb-4af8-a78c-6c9581ab138a" />

HDR (r709), notice the washed out colors, Yoshi doesn't even look properly green:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/bc0c8d53-c9c5-45bc-9b7c-49aa2eb1acd1" />

HDR (r2020), the colors seem more accurate, Yoshi is green, the sky is blue, and so on. It doesn't match SDR, but it's not completely washed out/wrong:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/4e4292b9-d30d-48da-af5e-712cbef5c9f7" />

I suffer from a severe health condition that affects my vision, but with r2020 does this seem more correct to me, or is it also wrong?

**Comment by matheuswillder** [comment]
I'll post this in this new comment because I saw you replied to the last one by email, so you might not see if I just edit the previous comment.

I figured out what's going on with the internal shader.

When I enable integer scaling, in Settings>Video>Scaling>Integer Scaling, the internal shader never display scanlines. When I disable it, I can see the scanlines. So the idea came to me, what if I keep integer scaling enabled and cut a little more of the overscan? And it works:

HDR on, scanlines on, no custom shaders loaded:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/da6bce3f-4a35-417d-95f6-d49944ce6ee0" />

HDR on, scanlines off, no custom shaders loaded:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/0fb58986-ed9d-4392-b77c-b13efbbc86be" />

It seems the internal shader doesn't like low resolutions (1080p) so it need more screen space to display something lol
