### ISSUE TITLE
Content icon overlaying the Quick Menu icons

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1891]
![retroarch - bug 1](https://cloud.githubusercontent.com/assets/5431285/8509741/821df5d4-228c-11e5-9bb3-3d7cf6062512.png)

**Comment by twinaphex** [comment]
Yes, we should bring this to @kivutar's attention.

**Comment by sergiobenrocha2** [comment]
I don't know if it's related.

Load some N64 game, then return to xmb and go to SuperGrafx playlist

![retroarch - bug 5](https://cloud.githubusercontent.com/assets/5431285/8513976/afb6202c-2357-11e5-8e19-75110dac437f.png)

**Comment by Kivutar** [comment]
This is unrelated.

Concerning that overlapping issue in the quick menu now. XMB is not made to support such teleports. XMB relies on ugly hacks that cache the previous list, in order to be able to fade out those lists. This duplicate icon is due to this caching strategy, coupled with the teleportation of the position in the tree.

We should avoid performing any "push" like this when comming back from the game to the menu. It is very hard to handle such pushes in XMB.

And I would add that it is a severe ergonomy issue, in a driver like XMB, to have this use case where hitting CANCEL then hitting OK does not take you back to the identical position.

If you are in the quick menu, then hit CANCEL, then hit OK, you don't end up in the quick menu. This is misleading.

That's why I prefer the behaviour we had before: when entering a playlist entry, we arrive on the quick menu, where most entries are hidden except the "Run" one. This way, when we enter the game, and go back to the menu, we don't need to "push" any list: we already are in the quick menu.

And when we hit CANCEL, followed by OK, we end up on the quick menu again. Which is less misleading.

**Comment by Kivutar** [comment]
I would add to that, http://libretro.com/forums/showthread.php?t=3460
It's impossible to manually add a ROM to the paylist, and access the "Run" entry, if the CRC is not in the database.
Going back to the previous implementation of the "quick menu" would also fix that.

**Comment by sergiobenrocha2** [comment]
Load one game by Load Content, and come back to xmb

![screenshot - 27102015 - 18 05 11](https://cloud.githubusercontent.com/assets/5431285/10771003/8e282ca2-7cd5-11e5-8421-626f6dd0eae2.png)

**Comment by sergiobenrocha2** [comment]
It appears after you load one game by Load Content and come back to quick menu. Get out the quick menu and returns to it, and the icon disappears.

![screenshot - 27102015 - 19 54 10](https://cloud.githubusercontent.com/assets/5431285/10773845/f1169cea-7ce4-11e5-8850-f7c0bfa56fa4.png)

**Comment by Kivutar** [comment]
A part of these issues are resolved. At least this one I think https://github.com/libretro/RetroArch/issues/1891#issuecomment-151627947

**Comment by twinaphex** [comment]
Let us know if these issues still happen and reopen. Closed until further notice.

**Comment by sergiobenrocha2** [comment]
The "Run" icon is behind the others now.

![screenshot - 10072016 - 22 08 06](https://cloud.githubusercontent.com/assets/5431285/16717340/d3c786ec-46ea-11e6-9d83-b84cc90a19d7.png)

**Comment by Kivutar** [comment]
This one started from this commit bd8a7d030e2845767639ab15dde23a4de9e64684

**Comment by twinaphex** [comment]
@kivutar @sergiobenrocha2 I think this commit should fix these issues -

https://github.com/libretro/RetroArch/commit/050e29140b8ce53a494bbf915cd447b562e219de

Let me know if there are still ongoing issues.

**Comment by Kivutar** [comment]
We need to avoid this codepath when launching from history or any playlist: https://github.com/libretro/RetroArch/blob/050e29140b8ce53a494bbf915cd447b562e219de/tasks/task_content.c#L1928-L1943

I'm trying to find a way to implement that special case.

**Comment by Kivutar** [comment]
@sergiobenrocha2 it's ok, it's fixed

**Comment by twinaphex** [comment]
This should hopefully take care of the last remaining issues -

https://github.com/libretro/RetroArch/commit/defe51ff69cde3e2d8c2a2a71a3c46759dd0d154

**Comment by sergiobenrocha2** [comment]
Nice, it's fine now
