### ISSUE TITLE
Add Content doesn't build playlist of 7z romsets

### ISSUE THREAD

**Issue by dafzor** [libretro/RetroArch#1994]
If the roms are stored in 7z files retroarch will not create a playlist when scanning them.

Selecting and loading the file directly in retroarch will however work.

**Comment by twinaphex** [comment]
Yeah it doesn't support 7z files right now, only zip and plain files.

I'll start working on a solution for this, might make it in time for v1.2.3.

**Comment by dafzor** [comment]
Out of curiosity could you share any details on this? I find it pretty strange that it can use 7z files directly but not add them to the playlist.

**Comment by twinaphex** [comment]
It's not odd if you look at tasks/task_database.c, support is simply not in there yet.

**Comment by xTMODx** [comment]
Are there any news on this?

**Comment by bparker06** [comment]
I started looking into this and did some preliminary work on it but the notion of compressed files being assumed to be .zip is very ingrained in the code... so it is quite a lot of work to decouple that. The current majority of 7zip code is confined to task_database.c which to my knowledge is still not able to correctly play 7z content directly, from the testing I have done. 

Being stuck in there means that nothing else is able to read 7z files, like the playlist scanner, browsing within archives, loading compressed cores etc.

Also the scanner requires a CRC check which is not implemented for 7z at all yet, that part of the code uses an archive "backend" of which there is only one currently, zlib for .zip files.

**Comment by SpaceAgeHero** [comment]
Hi bparker06,

I'm also interested in this functionality.
Is there any progress?
:-)

CRC values can (and probably should be) "just" read from the 7z archive headers, right?

**Comment by bparker06** [comment]
@SpaceAgeHero This and some other related bugs should all be fixed now in the latest master and nightlies. You can scan/browse/load 7z content now just as you can zip content, and the CRC is now pulled from the archive instead of recomputing it.

**Comment by heyboots** [comment]
I downloaded the Oct 2 nightly and tried scanning my 7zipped NES roms and it still came up with nothing, does the latest compiled nightly not have this in it yet?

**Comment by SpaceAgeHero** [comment]
Adding directories with 7zipped items still doesn't work for me neither with the latest build. Scanning instantly finishes ...

Then I tried scanning a single 7zipped file.
This worked but I couldn't start the game from the collection menu.

**Comment by bparker06** [comment]
@heyboots @SpaceAgeHero Yes it has it, I'm able to scan directories with 7z content and load the games just fine. Perhaps can you check the git version reported by RetroArch in Information -> System Information -> Git version? Also what platform are you running it on?

**Comment by bparker06** [comment]
Just tried the latest nightly on Windows and it is working there for me too (was on Linux before).

**Comment by twinaphex** [comment]
I think we can close this now unless somebody can still reproduce this.

**Comment by heyboots** [comment]
Git version 49d520c, build date Oct 4, Windows 10 x64, still not scanning 7zipped files for me. I just downloaded the latest version not ten minutes ago from the retroarch nightlies folder here: https://buildbot.libretro.com/nightly/windows/x86_64/

**Comment by bparker06** [comment]
@heyboots Have you confirmed that the CRC of the file in the 7z archive matches something that's in the database? In other words... if you extract the file from the 7z and scan just that one file, does it add it to the playlist then?

**Comment by heyboots** [comment]
Ok I grabbed a completely fresh install using only my old config file and it worked then. No idea why it wasn't working before because literally the only folders I did not carry over from my previous install were the folders for saves and thumbnails. and my old config file. No clue what the hell was going on with that.

**Comment by dafzor** [comment]
Also grabbed a 64bit windows nightly (e4992bc) with mupen64plus core and tried to add a n64 rom collection trough add content \ scan directory. Fresh copy with no old config files.

Scan finished instantly and no content was added under n64 on menu, extracting tree of the roms to the same folder and scanning again had two of them be detected.

Trying to play the extracted roms worked as well as opening the 7z file as a directory and selecting the rom inside the 7z archive.

**Comment by belldandu** [comment]
@twinaphex as of the latest version on the google play store (1.4.1) Retroarch is still failing to scan roms files compressed in 7z format when using the scan directories option. However the scan file option lets me load the archive although the game is still not added to the playlist.

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/blob/master/CHANGES.md

> # 1.4.2 (future)
> - SCANNER: Always add 7z & zip to supported extensions

**Comment by treyturner** [comment]
This would be great; my sets are all in 7z, and though NES scanning worked against 7z archives, many other platforms complete their scans immediately with no results added to the playlist.

Two questions: Should this issue be reopened, and is there a workaround we can implement until this fix and 1.4.2 become a reality? Thanks for your time and effort.

**Comment by Danixu** [comment]
Any news about this?, because I'm on 1.6.9 but for now the application is unable to add 7zip files to playlists on scan.
