### ISSUE TITLE
[win] Hiding the console window

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2188]
So, I was googling a bit, and it seems it's really easy to completely skip the console window, all we need is to add -mwindows to the LDFLAGS, I already tested it and it works fine.

That said, the console is useful, so I think we should definitely have a log to file option in the GUI (and it should log to CWD/retroarch.log for simplicity).

A problem I see with this is that only stuff that goes thru libretro's logging interface would be captured and that may not be enough in some cases.

**Comment by Awakened0** [comment]
If you can figure out logging to a file, will future Windows buildbot nightlies and point releases be compiled with the console hidden? Steam doesn't have a non messy way to hide it like dedicated emulation launchers do.

Being able to copy and paste a log from a file rather than getting it from the console should be easier for most users as well. The default view settings for the Windows console usually truncate verbose logs :/

**Comment by fr500** [comment]
Yeah once i figure how to make it I'll change it

**Comment by fr500** [comment]
You don't have to do anything to hide the console window.  This has been
fixed for years.

You just run without --verbose

**Comment by Daniel15** [comment]
Hmm, the console still appears for me. It was messing with my Steam Link.
