### ISSUE TITLE
[Wii] Custom viewport values and display resolution are reset at core change or at Retroarch boot up.

### ISSUE THREAD

**Issue by xmat123x** [libretro/RetroArch#2400]
Custom viewport values are reset at core change or at Retroarch boot up. Same for the non-custom display resolution like switching to 640 by 480 from the default 608 by 480.

When in the display settings in Retroarch Wii, we can see:

custom_viewport_width = "608"
custom_viewport_height = "480"
custom_viewport_x = "0"
custom_viewport_y = "0"

But when viewing the config file on a PC, the values are

current_resolution_id = "0"
custom_viewport_width = "0"
custom_viewport_height = "0"
custom_viewport_x = "0"
custom_viewport_y = "0"

Seems that the values are either not being written or they're being overwritten on boot.

**Comment by twinaphex** [comment]
I see the viewport being reset here.

https://github.com/libretro/RetroArch/blob/master/gfx/drivers/gx_gfx.c#L432

I did not add this, I think @ToadKing did. I also don't know if it is safe to simply remove this line or whether it will cause problems elsewhere. Try deleting this line and recompiling and see if things still work properly then.

**Comment by ToadKing** [comment]
We originally never tried to set the video mode unless you were changing it, which is why that line is there. If your custom viewport is, say 608x480 and you change to a 512x224 video mode then things will be bad. The fix should still reset custom viewports on video mode changes, just not on startup.

**Comment by twinaphex** [comment]
I think we should take a look at Ekeeke's Wii port and other Wii-based emulators and just try to write the video mode handling code differently. It doesn't make sense why we have all these issues in RA Wii remaining forever while others don't experience quite the same problems.

**Comment by xmat123x** [comment]
Resolution saving worked fine in 1.0.0.2 though, the issue is relatively recent.

**Comment by fr500** [comment]
I think this is fixed. Reopen otherwise.

**Comment by SergeEXE** [comment]
On both the latest Stable and Nightly builds, Screen Resolution setting does not save when loading new content, instead reverting back to "Default."

**Comment by Nashismo** [comment]
Problem remains. Resolution reverts back to default. Using the latest official Wii build (19/02/2018).

**Comment by SergeEXE** [comment]
Issue seems to resolve when changing settings BEFORE loading a core and/or starting a game first.
