### ISSUE TITLE
N & M hotkeys can't go through CGP shaders

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#2931]
Those keys now ignore CGP files, they only go through CG files contained in the shader folder.

win7 x64

**Comment by NelsonRosenberg** [comment]
I have the same problem here. Also, it appears that GLSL is the default shader when I open retroarch (as I can see in the debug log), but I'm sure I can use CG shaders. 

I think this does not happen in the x86 version. Only x86_64.

**Comment by fr500** [comment]
Not sure about the first issue
about it using GLSL by default, yes it is by design, if you load a CG
shader it will fall back normally

**Comment by NelsonRosenberg** [comment]
But does it always defaults to GSLS even when I have a Nvideo video card? Were can I change the default then? I say it because in older versions it would load CG shaders on boot and only default to GSLS if my card couldn't handle CG (as far as I know, as I always had nvidia video card). The point is it seem I can't use CG shaders now, even trying to directly apply them or using N/M on the keyboard. There is a log error about this when I try to apply them, I'll try to post it later.

**Comment by twinaphex** [comment]
Cg is on the way out, nvidia left it for dead since 2012 and didn't even bother releasing the source to add further insult to injury. We are steadily moving away from it and deprecating it. GLSL gets promoted over Cg.

You are still able to use Cg shaders/presets just fine if you so desire, it will just no longer be defaulted to. The more advanced ribbon shaders being used in the XMB menu will need GLSL anyway since partial derivative support for Cg is rather spotty.

**Comment by NelsonRosenberg** [comment]
I see. I did not know that. I was under the impression that CG was preffered. Thanks a lot for the helpful explanation. I shall change to use only GSLS.

**Comment by fr500** [comment]
You shouldn't rush to GLSL shaders yet either,  many are auto converted,
just use the CG shaders and ignore the log message.

It's just that the default "empty" shader is now GLSL,  that's it.

**Comment by Awakened0** [comment]
Hope this isn't too hard to fix. I miss being able to hotswap between crt-easymode-halation.cgp and pixellate.cg.

**Comment by fr500** [comment]
Is this fixed? can you try again?

**Comment by Awakened0** [comment]
Still doesn't work as of the 2016-05-09 nightly.

**Comment by fr500** [comment]
Hmmm, well loading CGs manually is fixed at least right?

**Comment by Awakened0** [comment]
I can load a preset and apply it fine from the menu.

**Comment by Tatsuya79** [comment]
No problem with loading in menu either here. 
But switching with hotkeys still not work. 
It is a feature I use a lot, great for comparison.

**Comment by Tatsuya79** [comment]
Now .glslp get excluded too, only .cg are working with those keys.

**Comment by fr500** [comment]
fixed https://github.com/libretro/RetroArch/commit/c38adcabd368692cb51af4174cc2238db6f18f12
:)

**Comment by Tatsuya79** [comment]
Thanks! I confirm that's working now.
