### ISSUE TITLE
RA creating a file instead folder in ~/.config/

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2934]
I just saw this issue on reddit, I can confirm it:

https://www.reddit.com/r/RetroArch/comments/4h9v1z/retroarch_cant_create_directories/

```
./retroarch
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/database/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/database/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
mkdir(/home/sergio/.config/retroarch/) error: Not a directory.
Failed to create directory: "/home/sergio/.config/retroarch/".
Failed to create directory: "/home/sergio/.config/retroarch/".
```

It's creating a "retroarch" file instead a folder in ~/.config/
in a clean environment, without any previous config

7d99e7c broke it.

**Comment by sergiobenrocha2** [comment]
Weird, and the ~/.config/retroarch is the retroarch.cfg actually

**Comment by escalade** [comment]
I can confirm this.

**Comment by sergiobenrocha2** [comment]
Fixed on 8ff8131 and 906b949

**Comment by mozgbrasil** [comment]
Good afternoon

According to images, we see that the error persists

Can you help me, I'm not able to use the application

![captura de tela de 2018-06-11 20-36-25](https://user-images.githubusercontent.com/17202780/41262466-63abfba4-6db7-11e8-817d-958060df6e3a.png)
![captura de tela de 2018-06-11 20-37-20](https://user-images.githubusercontent.com/17202780/41262467-63db6010-6db7-11e8-9964-aba5729ffb93.png)

**Comment by sergiobenrocha2** [comment]
Delete ~/.config/retroarch/ and try again I guess
