### ISSUE TITLE
Shader parameters cause crash on android

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2980]
There are a few GLSL shaders that have parameters enabled, particularly image-adjustment.glsl, trying to open the submenu causes RetroArch to crash

**Comment by fr500** [comment]
thanks to a forum thread discussing a different issue I found out that it doesn't crash if threaded video is disabled.

It still will fail to list the parameters but it at least doesn't crash, so it would be useful to check why it crashes with threaded video enabled.

**Comment by blackman91** [comment]
I can confirm this bug, it happens in the latest android nightly too, I will test to see what was the last retroarch version where this worked.

**Comment by twinaphex** [comment]
Don't know how to fix this, I'd like some help from @Themaister on this if possible.

**Comment by blackman91** [comment]
Hi did the new 1.3.6 release fix this bug?

**Comment by fr500** [comment]
No

**Comment by bparker06** [comment]
finally fixed in 118308fbff293c1066c38e74de2e2ad28ee2c819

**Comment by blackman91** [comment]
The crashing stopped but it still fails to list the shader parameters like fr500 mentioned, should we open a new issue?

**Comment by hizzlekizzle** [comment]
Parameters are working for GLSL and slang for me on Nvidia Shield, both with and without threaded video enabled.

**Comment by bparker06** [comment]
Same here.

**Comment by blackman91** [comment]
So what are the glsl shaders that you can change the parameters? Tried the color mangler in the misc folder but it says no parameters are available.

**Comment by bparker06** [comment]
@blackman91 crt-aperture works for me.

**Comment by blackman91** [comment]
You are right just tested crt-aperture and it is working, it seems color mangler is not working the parameters don't show, could anyone else test this shader?

**Comment by hizzlekizzle** [comment]
@blackman91 that's one that looks indistinguishable from stock.glsl if none of the parameters are tweaked; that is, it looks identical whether it compiled successfully or not. Can you check your logs and see if it's failing to compile?

**Comment by blackman91** [comment]
@hizzlekizzle are the color-mangler shader parameters showing for you? btw the crt-geom shader parameters do show for me.  How do you check logs in android retroarch?

**Comment by hizzlekizzle** [comment]
I just added precision to the parameters for a lot of the shaders, including color-mangler. Give it a few minutes to populate at the buildbot and re-fetch them from the online updater and see if it works any better for you.

**Comment by blackman91** [comment]
Wow thanks a lot man, color-mangler parameters are showing now, confirmed working, nice job.
