### ISSUE TITLE
Can't build on latest libctru 

### ISSUE THREAD

**Issue by Teuns** [libretro/RetroArch#4020]
Hello,

I get stuck on the part to create an ELF but somehow I got these errors even if I linked the libretro_ctr.a libary to it: 
```
ctr/ctr_system.o: In function `APT_ReceiveDeliverArg_':
ctr_system.c:(.text+0x3b4): undefined reference to `aptSendCommand'
ctr/ctr_system.o: In function `__system_initArgv':
ctr_system.c:(.text+0x5ac): undefined reference to `aptSendCommand'
griffin/griffin.o: In function `libretro_get_system_info_static':
griffin.c:(.text+0x10f90): undefined reference to `retro_set_environment'
griffin.c:(.text+0x10fa4): undefined reference to `retro_set_environment'
griffin.c:(.text+0x10fb0): undefined reference to `retro_get_system_info'
griffin/griffin.o: In function `frontend_ctr_exec':
griffin.c:(.text+0x304bc): undefined reference to `APT_PrepareToDoApplicationJump'
griffin.c:(.text+0x304d4): undefined reference to `APT_DoApplicationJump'
griffin/griffin.o: In function `libretro_get_system_info':
griffin.c:(.text+0x43fec): undefined reference to `retro_set_environment'
griffin.c:(.text+0x44000): undefined reference to `retro_set_environment'
griffin.c:(.text+0x4400c): undefined reference to `retro_get_system_info'
griffin/griffin.o: In function `init_libretro_sym':
griffin.c:(.text+0x44374): undefined reference to `retro_init'
griffin.c:(.text+0x44378): undefined reference to `retro_deinit'
griffin.c:(.text+0x4437c): undefined reference to `retro_api_version'
griffin.c:(.text+0x44380): undefined reference to `retro_get_system_info'
griffin.c:(.text+0x44384): undefined reference to `retro_get_system_av_info'
griffin.c:(.text+0x44388): undefined reference to `retro_set_environment'
griffin.c:(.text+0x4438c): undefined reference to `retro_set_video_refresh'
griffin.c:(.text+0x44390): undefined reference to `retro_set_audio_sample'
griffin.c:(.text+0x44394): undefined reference to `retro_set_audio_sample_batch'
griffin.c:(.text+0x44398): undefined reference to `retro_set_input_poll'
griffin.c:(.text+0x4439c): undefined reference to `retro_set_input_state'
griffin.c:(.text+0x443a0): undefined reference to `retro_set_controller_port_device'
griffin.c:(.text+0x443a4): undefined reference to `retro_reset'
griffin.c:(.text+0x443a8): undefined reference to `retro_run'
griffin.c:(.text+0x443ac): undefined reference to `retro_serialize_size'
griffin.c:(.text+0x443b0): undefined reference to `retro_serialize'
griffin.c:(.text+0x443b4): undefined reference to `retro_unserialize'
griffin.c:(.text+0x443b8): undefined reference to `retro_cheat_reset'
griffin.c:(.text+0x443bc): undefined reference to `retro_cheat_set'
griffin.c:(.text+0x443c0): undefined reference to `retro_load_game'
griffin.c:(.text+0x443c4): undefined reference to `retro_load_game_special'
griffin.c:(.text+0x443c8): undefined reference to `retro_unload_game'
griffin.c:(.text+0x443cc): undefined reference to `retro_get_region'
griffin.c:(.text+0x443d0): undefined reference to `retro_get_memory_data'
griffin.c:(.text+0x443d4): undefined reference to `retro_get_memory_size'
griffin/griffin.o: In function `core_init_symbols':
griffin.c:(.text+0x58398): undefined reference to `retro_init'
griffin.c:(.text+0x5839c): undefined reference to `retro_deinit'
griffin.c:(.text+0x583a0): undefined reference to `retro_api_version'
griffin.c:(.text+0x583a4): undefined reference to `retro_get_system_info'
griffin.c:(.text+0x583a8): undefined reference to `retro_get_system_av_info'
griffin.c:(.text+0x583ac): undefined reference to `retro_set_environment'
griffin.c:(.text+0x583b0): undefined reference to `retro_set_video_refresh'
griffin.c:(.text+0x583b4): undefined reference to `retro_set_audio_sample'
griffin.c:(.text+0x583b8): undefined reference to `retro_set_audio_sample_batch'
griffin.c:(.text+0x583bc): undefined reference to `retro_set_input_poll'
griffin.c:(.text+0x583c0): undefined reference to `retro_set_input_state'
griffin.c:(.text+0x583c4): undefined reference to `retro_set_controller_port_device'
griffin.c:(.text+0x583c8): undefined reference to `retro_reset'
griffin.c:(.text+0x583cc): undefined reference to `retro_run'
griffin.c:(.text+0x583d0): undefined reference to `retro_serialize_size'
griffin.c:(.text+0x583d4): undefined reference to `retro_serialize'
griffin.c:(.text+0x583d8): undefined reference to `retro_unserialize'
griffin.c:(.text+0x583dc): undefined reference to `retro_cheat_reset'
griffin.c:(.text+0x583e0): undefined reference to `retro_cheat_set'
griffin.c:(.text+0x583e4): undefined reference to `retro_load_game'
griffin.c:(.text+0x583e8): undefined reference to `retro_load_game_special'
griffin.c:(.text+0x583ec): undefined reference to `retro_unload_game'
griffin.c:(.text+0x583f0): undefined reference to `retro_get_region'
griffin.c:(.text+0x583f4): undefined reference to `retro_get_memory_data'
griffin.c:(.text+0x583f8): undefined reference to `retro_get_memory_size'
griffin/griffin.o: In function `command_event_init_core':
griffin.c:(.text+0xba300): undefined reference to `retro_init'
griffin.c:(.text+0xba304): undefined reference to `retro_deinit'
griffin.c:(.text+0xba308): undefined reference to `retro_api_version'
griffin.c:(.text+0xba30c): undefined reference to `retro_get_system_info'
griffin.c:(.text+0xba310): undefined reference to `retro_get_system_av_info'
griffin.c:(.text+0xba314): undefined reference to `retro_set_environment'
griffin.c:(.text+0xba318): undefined reference to `retro_set_video_refresh'
griffin.c:(.text+0xba31c): undefined reference to `retro_set_audio_sample'
griffin.c:(.text+0xba320): undefined reference to `retro_set_audio_sample_batch'
griffin.c:(.text+0xba324): undefined reference to `retro_set_input_poll'
griffin.c:(.text+0xba328): undefined reference to `retro_set_input_state'
griffin.c:(.text+0xba32c): undefined reference to `retro_set_controller_port_device'
griffin.c:(.text+0xba330): undefined reference to `retro_reset'
griffin.c:(.text+0xba334): undefined reference to `retro_run'
griffin.c:(.text+0xba338): undefined reference to `retro_serialize_size'
griffin.c:(.text+0xba33c): undefined reference to `retro_serialize'
griffin.c:(.text+0xba340): undefined reference to `retro_unserialize'
griffin.c:(.text+0xba344): undefined reference to `retro_cheat_reset'
griffin.c:(.text+0xba348): undefined reference to `retro_cheat_set'
griffin.c:(.text+0xba34c): undefined reference to `retro_load_game'
griffin.c:(.text+0xba350): undefined reference to `retro_load_game_special'
griffin.c:(.text+0xba354): undefined reference to `retro_unload_game'
griffin.c:(.text+0xba358): undefined reference to `retro_get_region'
griffin.c:(.text+0xba35c): undefined reference to `retro_get_memory_data'
griffin.c:(.text+0xba360): undefined reference to `retro_get_memory_size'
```

Do I need to downgrade my libctru to compile it successful, or?

**Comment by aliaspider** [comment]
I have just built it just fine using latest ctrulib.
make sure you have a valid libretro_ctr.a core library in the root folder and that you are really using latest ctrulib.
the makefile will use the CTRULIB environment variable to look for it, and will fall-back to $(DEVKITPRO)/ctrulib if it wasn't set.

**Comment by aliaspider** [comment]
the fallback path when CTRULIB wasn't defined was wrong so maybe that was your issue ? I have just pushed a commit to fix it : 9b69d69d30c4d51a8216c19a5d020b84c883b992

**Comment by Teuns** [comment]
Weird. For me it just shows an warning about an implicit declaration of function 'aptSendComman' [-Werror=implicit-function-declaration] and after it has compiled it shows the undefined reference errors. WIll take a look at your commit

**Comment by Teuns** [comment]
Nope, still facing the 'Undefined reference' errors somehow.

`ctr/ctr_system.o: In function `APT_ReceiveDeliverArg_':
ctr_system.c:(.text+0x3b4): undefined reference to `aptSendCommand'
ctr/ctr_system.o: In function `__system_initArgv':
ctr_system.c:(.text+0x5ac): undefined reference to `aptSendCommand'
griffin/griffin.o: In function `libretro_get_system_info_static':
griffin.c:(.text+0x10f90): undefined reference to `retro_set_environment'
griffin.c:(.text+0x10fa4): undefined reference to `retro_set_environment'
griffin.c:(.text+0x10fb0): undefined reference to `retro_get_system_info'
griffin/griffin.o: In function `frontend_ctr_exec':
griffin.c:(.text+0x304bc): undefined reference to `APT_PrepareToDoApplicationJump'
griffin.c:(.text+0x304d4): undefined reference to `APT_DoApplicationJump'
griffin/griffin.o: In function `libretro_get_system_info':
griffin.c:(.text+0x43fec): undefined reference to `retro_set_environment'
griffin.c:(.text+0x44000): undefined reference to `retro_set_environment'
griffin.c:(.text+0x4400c): undefined reference to `retro_get_system_info'
griffin/griffin.o: In function `init_libretro_sym':
griffin.c:(.text+0x44374): undefined reference to `retro_init'
griffin.c:(.text+0x44378): undefined reference to `retro_deinit'
griffin.c:(.text+0x4437c): undefined reference to `retro_api_version'
griffin.c:(.text+0x44380): undefined reference to `retro_get_system_info'
griffin.c:(.text+0x44384): undefined reference to `retro_get_system_av_info'
griffin.c:(.text+0x44388): undefined reference to `retro_set_environment'
griffin.c:(.text+0x4438c): undefined reference to `retro_set_video_refresh'
griffin.c:(.text+0x44390): undefined reference to `retro_set_audio_sample'
griffin.c:(.text+0x44394): undefined reference to `retro_set_audio_sample_batch'
griffin.c:(.text+0x44398): undefined reference to `retro_set_input_poll'
griffin.c:(.text+0x4439c): undefined reference to `retro_set_input_state'
griffin.c:(.text+0x443a0): undefined reference to `retro_set_controller_port_device'
griffin.c:(.text+0x443a4): undefined reference to `retro_reset'
griffin.c:(.text+0x443a8): undefined reference to `retro_run'
griffin.c:(.text+0x443ac): undefined reference to `retro_serialize_size'
griffin.c:(.text+0x443b0): undefined reference to `retro_serialize'
griffin.c:(.text+0x443b4): undefined reference to `retro_unserialize'
griffin.c:(.text+0x443b8): undefined reference to `retro_cheat_reset'
griffin.c:(.text+0x443bc): undefined reference to `retro_cheat_set'
griffin.c:(.text+0x443c0): undefined reference to `retro_load_game'
griffin.c:(.text+0x443c4): undefined reference to `retro_load_game_special'
griffin.c:(.text+0x443c8): undefined reference to `retro_unload_game'
griffin.c:(.text+0x443cc): undefined reference to `retro_get_region'
griffin.c:(.text+0x443d0): undefined reference to `retro_get_memory_data'
griffin.c:(.text+0x443d4): undefined reference to `retro_get_memory_size'
griffin/griffin.o: In function `core_init_symbols':
griffin.c:(.text+0x58398): undefined reference to `retro_init'
griffin.c:(.text+0x5839c): undefined reference to `retro_deinit'
griffin.c:(.text+0x583a0): undefined reference to `retro_api_version'
griffin.c:(.text+0x583a4): undefined reference to `retro_get_system_info'
griffin.c:(.text+0x583a8): undefined reference to `retro_get_system_av_info'
griffin.c:(.text+0x583ac): undefined reference to `retro_set_environment'
griffin.c:(.text+0x583b0): undefined reference to `retro_set_video_refresh'
griffin.c:(.text+0x583b4): undefined reference to `retro_set_audio_sample'
griffin.c:(.text+0x583b8): undefined reference to `retro_set_audio_sample_batch'
griffin.c:(.text+0x583bc): undefined reference to `retro_set_input_poll'
griffin.c:(.text+0x583c0): undefined reference to `retro_set_input_state'
griffin.c:(.text+0x583c4): undefined reference to `retro_set_controller_port_device'
griffin.c:(.text+0x583c8): undefined reference to `retro_reset'
griffin.c:(.text+0x583cc): undefined reference to `retro_run'
griffin.c:(.text+0x583d0): undefined reference to `retro_serialize_size'
griffin.c:(.text+0x583d4): undefined reference to `retro_serialize'
griffin.c:(.text+0x583d8): undefined reference to `retro_unserialize'
griffin.c:(.text+0x583dc): undefined reference to `retro_cheat_reset'
griffin.c:(.text+0x583e0): undefined reference to `retro_cheat_set'
griffin.c:(.text+0x583e4): undefined reference to `retro_load_game'
griffin.c:(.text+0x583e8): undefined reference to `retro_load_game_special'
griffin.c:(.text+0x583ec): undefined reference to `retro_unload_game'
griffin.c:(.text+0x583f0): undefined reference to `retro_get_region'
griffin.c:(.text+0x583f4): undefined reference to `retro_get_memory_data'
griffin.c:(.text+0x583f8): undefined reference to `retro_get_memory_size'
griffin/griffin.o: In function `command_event_init_core':
griffin.c:(.text+0xba300): undefined reference to `retro_init'
griffin.c:(.text+0xba304): undefined reference to `retro_deinit'
griffin.c:(.text+0xba308): undefined reference to `retro_api_version'
griffin.c:(.text+0xba30c): undefined reference to `retro_get_system_info'
griffin.c:(.text+0xba310): undefined reference to `retro_get_system_av_info'
griffin.c:(.text+0xba314): undefined reference to `retro_set_environment'
griffin.c:(.text+0xba318): undefined reference to `retro_set_video_refresh'
griffin.c:(.text+0xba31c): undefined reference to `retro_set_audio_sample'
griffin.c:(.text+0xba320): undefined reference to `retro_set_audio_sample_batch'
griffin.c:(.text+0xba324): undefined reference to `retro_set_input_poll'
griffin.c:(.text+0xba328): undefined reference to `retro_set_input_state'
griffin.c:(.text+0xba32c): undefined reference to `retro_set_controller_port_device'
griffin.c:(.text+0xba330): undefined reference to `retro_reset'
griffin.c:(.text+0xba334): undefined reference to `retro_run'
griffin.c:(.text+0xba338): undefined reference to `retro_serialize_size'
griffin.c:(.text+0xba33c): undefined reference to `retro_serialize'
griffin.c:(.text+0xba340): undefined reference to `retro_unserialize'
griffin.c:(.text+0xba344): undefined reference to `retro_cheat_reset'
griffin.c:(.text+0xba348): undefined reference to `retro_cheat_set'
griffin.c:(.text+0xba34c): undefined reference to `retro_load_game'
griffin.c:(.text+0xba350): undefined reference to `retro_load_game_special'
griffin.c:(.text+0xba354): undefined reference to `retro_unload_game'
griffin.c:(.text+0xba358): undefined reference to `retro_get_region'
griffin.c:(.text+0xba35c): undefined reference to `retro_get_memory_data'
griffin.c:(.text+0xba360): undefined reference to `retro_get_memory_size'`

**Comment by Teuns** [comment]
<details>
<summary>Error log</summary>
$ make -f Makefile.ctr
/opt/devkitpro/devkitARM/bin/arm-none-eabi-g++ -specs=ctr/3dsx_custom.specs -g -march=armv6k -mtune=mpcore -mfloat-abi=hard -marm -mfpu=vfp -mtp=soft -Wl,-Map,.map  gfx/drivers/ctr_shaders/ctr_sprite.o ctr/ctr_system.o ctr/ctr_memory.o ctr/ctr_linear.o ctr/gpu_old.o griffin/griffin.o -L. -L/opt/devkitpro/libctru/lib  -lretro_ctr  -lctru -lm -o retroarch_3ds.elf
ctr/ctr_system.o: In function `APT_ReceiveDeliverArg_':
ctr_system.c:(.text+0x3b4): undefined reference to `aptSendCommand'
ctr/ctr_system.o: In function `__system_initArgv':
ctr_system.c:(.text+0x5ac): undefined reference to `aptSendCommand'
griffin/griffin.o: In function `libretro_get_system_info_static':
griffin.c:(.text+0x10f90): undefined reference to `retro_set_environment'
griffin.c:(.text+0x10fa4): undefined reference to `retro_set_environment'
griffin.c:(.text+0x10fb0): undefined reference to `retro_get_system_info'
griffin/griffin.o: In function `frontend_ctr_exec':
griffin.c:(.text+0x304bc): undefined reference to `APT_PrepareToDoApplicationJump'
griffin.c:(.text+0x304d4): undefined reference to `APT_DoApplicationJump'
griffin/griffin.o: In function `libretro_get_system_info':
griffin.c:(.text+0x43fec): undefined reference to `retro_set_environment'
griffin.c:(.text+0x44000): undefined reference to `retro_set_environment'
griffin.c:(.text+0x4400c): undefined reference to `retro_get_system_info'
griffin/griffin.o: In function `init_libretro_sym':
griffin.c:(.text+0x44374): undefined reference to `retro_init'
griffin.c:(.text+0x44378): undefined reference to `retro_deinit'
griffin.c:(.text+0x4437c): undefined reference to `retro_api_version'
griffin.c:(.text+0x44380): undefined reference to `retro_get_system_info'
griffin.c:(.text+0x44384): undefined reference to `retro_get_system_av_info'
griffin.c:(.text+0x44388): undefined reference to `retro_set_environment'
griffin.c:(.text+0x4438c): undefined reference to `retro_set_video_refresh'
griffin.c:(.text+0x44390): undefined reference to `retro_set_audio_sample'
griffin.c:(.text+0x44394): undefined reference to `retro_set_audio_sample_batch'
griffin.c:(.text+0x44398): undefined reference to `retro_set_input_poll'
griffin.c:(.text+0x4439c): undefined reference to `retro_set_input_state'
griffin.c:(.text+0x443a0): undefined reference to `retro_set_controller_port_device'
griffin.c:(.text+0x443a4): undefined reference to `retro_reset'
griffin.c:(.text+0x443a8): undefined reference to `retro_run'
griffin.c:(.text+0x443ac): undefined reference to `retro_serialize_size'
griffin.c:(.text+0x443b0): undefined reference to `retro_serialize'
griffin.c:(.text+0x443b4): undefined reference to `retro_unserialize'
griffin.c:(.text+0x443b8): undefined reference to `retro_cheat_reset'
griffin.c:(.text+0x443bc): undefined reference to `retro_cheat_set'
griffin.c:(.text+0x443c0): undefined reference to `retro_load_game'
griffin.c:(.text+0x443c4): undefined reference to `retro_load_game_special'
griffin.c:(.text+0x443c8): undefined reference to `retro_unload_game'
griffin.c:(.text+0x443cc): undefined reference to `retro_get_region'
griffin.c:(.text+0x443d0): undefined reference to `retro_get_memory_data'
griffin.c:(.text+0x443d4): undefined reference to `retro_get_memory_size'
griffin/griffin.o: In function `core_init_symbols':
griffin.c:(.text+0x58398): undefined reference to `retro_init'
griffin.c:(.text+0x5839c): undefined reference to `retro_deinit'
griffin.c:(.text+0x583a0): undefined reference to `retro_api_version'
griffin.c:(.text+0x583a4): undefined reference to `retro_get_system_info'
griffin.c:(.text+0x583a8): undefined reference to `retro_get_system_av_info'
griffin.c:(.text+0x583ac): undefined reference to `retro_set_environment'
griffin.c:(.text+0x583b0): undefined reference to `retro_set_video_refresh'
griffin.c:(.text+0x583b4): undefined reference to `retro_set_audio_sample'
griffin.c:(.text+0x583b8): undefined reference to `retro_set_audio_sample_batch'
griffin.c:(.text+0x583bc): undefined reference to `retro_set_input_poll'
griffin.c:(.text+0x583c0): undefined reference to `retro_set_input_state'
griffin.c:(.text+0x583c4): undefined reference to `retro_set_controller_port_device'
griffin.c:(.text+0x583c8): undefined reference to `retro_reset'
griffin.c:(.text+0x583cc): undefined reference to `retro_run'
griffin.c:(.text+0x583d0): undefined reference to `retro_serialize_size'
griffin.c:(.text+0x583d4): undefined reference to `retro_serialize'
griffin.c:(.text+0x583d8): undefined reference to `retro_unserialize'
griffin.c:(.text+0x583dc): undefined reference to `retro_cheat_reset'
griffin.c:(.text+0x583e0): undefined reference to `retro_cheat_set'
griffin.c:(.text+0x583e4): undefined reference to `retro_load_game'
griffin.c:(.text+0x583e8): undefined reference to `retro_load_game_special'
griffin.c:(.text+0x583ec): undefined reference to `retro_unload_game'
griffin.c:(.text+0x583f0): undefined reference to `retro_get_region'
griffin.c:(.text+0x583f4): undefined reference to `retro_get_memory_data'
griffin.c:(.text+0x583f8): undefined reference to `retro_get_memory_size'
griffin/griffin.o: In function `command_event_init_core':
griffin.c:(.text+0xba300): undefined reference to `retro_init'
griffin.c:(.text+0xba304): undefined reference to `retro_deinit'
griffin.c:(.text+0xba308): undefined reference to `retro_api_version'
griffin.c:(.text+0xba30c): undefined reference to `retro_get_system_info'
griffin.c:(.text+0xba310): undefined reference to `retro_get_system_av_info'
griffin.c:(.text+0xba314): undefined reference to `retro_set_environment'
griffin.c:(.text+0xba318): undefined reference to `retro_set_video_refresh'
griffin.c:(.text+0xba31c): undefined reference to `retro_set_audio_sample'
griffin.c:(.text+0xba320): undefined reference to `retro_set_audio_sample_batch'
griffin.c:(.text+0xba324): undefined reference to `retro_set_input_poll'
griffin.c:(.text+0xba328): undefined reference to `retro_set_input_state'
griffin.c:(.text+0xba32c): undefined reference to `retro_set_controller_port_device'
griffin.c:(.text+0xba330): undefined reference to `retro_reset'
griffin.c:(.text+0xba334): undefined reference to `retro_run'
griffin.c:(.text+0xba338): undefined reference to `retro_serialize_size'
griffin.c:(.text+0xba33c): undefined reference to `retro_serialize'
griffin.c:(.text+0xba340): undefined reference to `retro_unserialize'
griffin.c:(.text+0xba344): undefined reference to `retro_cheat_reset'
griffin.c:(.text+0xba348): undefined reference to `retro_cheat_set'
griffin.c:(.text+0xba34c): undefined reference to `retro_load_game'
griffin.c:(.text+0xba350): undefined reference to `retro_load_game_special'
griffin.c:(.text+0xba354): undefined reference to `retro_unload_game'
griffin.c:(.text+0xba358): undefined reference to `retro_get_region'
griffin.c:(.text+0xba35c): undefined reference to `retro_get_memory_data'
griffin.c:(.text+0xba360): undefined reference to `retro_get_memory_size'
collect2: error: ld returned 1 exit status
make: *** [retroarch_3ds.elf] Error 1
</details>

**Comment by aliaspider** [comment]
and you are certain you have latest libctru.a inside /opt/devkitpro/libctru/lib ? maybe you built it with just make and not make install, in which case it will not copy the library there.

also that log shows that either you don't have a libretro_ctr.a in the same folder as Makefile.ctr, or that the file is there but invalid. try rebuilding the core again.

**Comment by Teuns** [comment]
Hmm, still facing the undefined reference errors..

**Comment by aliaspider** [comment]
which core are you trying to link ? did you try another core ? did you build the core correctly with make platform=ctr ?

**Comment by Teuns** [comment]
With https://github.com/shutterbug2000/dosbox-libretro-3ds. Am now getting only 4 errors, but that might because the libctru version.

<details>
ctr/ctr_system.o: In function `APT_ReceiveDeliverArg_':
ctr_system.c:(.text+0x3b4): undefined reference to `aptSendCommand'
ctr/ctr_system.o: In function `__system_initArgv':
ctr_system.c:(.text+0x5ac): undefined reference to `aptSendCommand'
griffin/griffin.o: In function `frontend_ctr_exec':
griffin.c:(.text+0x304bc): undefined reference to `APT_PrepareToDoApplicationJump'
griffin.c:(.text+0x304d4): undefined reference to `APT_DoApplicationJump'
</details>

Will downgrade my libctru to test it out again.

**Comment by aliaspider** [comment]
you need to upgrade it not downgrade it, those errors mean that you have an older version.

**Comment by Teuns** [comment]
Am using 1.10 now and it still shows the errors. What could the solution be?

**Comment by aliaspider** [comment]
1.10 is from january 6, you need to build it yourself from git.

**Comment by Teuns** [comment]
May I ask why it is closed? It is still not fixed, so it can't be.

**Comment by aliaspider** [comment]
it is fixed, the title was wrong "Can't build on latest libctru" when the issue was that you weren't using latest.

**Comment by Teuns** [comment]
Oh okay. Alright, got it compiled on Retroarch 1.3. Thanks for your help, am now going to look to upgrade it :)

**Comment by aliaspider** [comment]
np :)

**Comment by Teuns** [comment]
Offtopic: Do you may have an RSF file to build dosbox? For me it says after starting that there is an error occurred...

**Comment by aliaspider** [comment]
that's a problem with the core not the rsf.
why not use https://github.com/libretro/dosbox-libretro instead ?

**Comment by Teuns** [comment]
Oh okay, didn't new that that was open sourced. 

end
