### ISSUE TITLE
Shaders not working in Android

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#4302]
See https://libretro.com/forums/showthread.php?t=2304&page=37&p=53050&viewfull=1#post53050

I have experienced the same thing on my Shield Tablet, selecting a shader does nothing.

**Comment by twinaphex** [comment]
you're sure these are GLSL shader presets instead of cgp?

Android isn't going to support Cg shaders of course.

**Comment by loganmc10** [comment]
Ya I am using GLSL, it doesn't even get to the point where you could try it, when you select a shader preset it does nothing, the "Shader Passes" value is still 0

**Comment by twinaphex** [comment]
Yeah it still works on PC for whatever reason. Hope you can help investigate the issue.

**Comment by loganmc10** [comment]
This appears to be a buildbot issue, the APK doesn't have the actual shaders (.glsl files), just the presets (.glslp). You can verify this by opening the .APK with 7zip

**Comment by fr500** [comment]
```
buildbot@bot2:~$ cgc
The program 'cgc' is currently not installed. You can install it by typing:
sudo apt install nvidia-cg-toolkit

```

Fixed, on the next build (next commit) it should be able to convert them correctly

**Comment by loganmc10** [comment]
Just checked the latest buildbot APK and they are there now, still doesn't include the native GLSL shaders but I guess that's how it used to be
