### ISSUE TITLE
Crash on launch in KMS mode

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/RetroArch#4790]
## Description
This started at least a week ago. Doesn't seem to depend on any settings.
[Log](https://github.com/libretro/RetroArch/files/880463/retroarch.txt)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: dd80ffc61

### Environment information

- OS: Arch Linux

**Comment by twinaphex** [comment]
I can go as far back as two months ago and it's still broken then.

Seems something changed software-side on my Linux machine which makes it no longer work. Could be a bump in libdrm and some changes need to be made to get it to work again.

Anyway, I have no real idea so far why it no longer works.

**Comment by hizzlekizzle** [comment]
Ah, I think this has to do with mesa. It first popped up a week or so ago in Arch and reverting to the previous mesa package should fix it.

**Comment by twinaphex** [comment]
It fails at eglGetDisplay for some reason.

Could be a Mesa issue yeah. I am currently upgrading my system on Arch Linux hoping that will do the trick.

**Comment by twinaphex** [comment]
@hizzlekizzle Still fails on my end after having done a pacman -syu.

@GeneralFailer Try seeing if reverting to a previous mesage package fixes the issues for you.

**Comment by timde9** [comment]
I am having the same issue on arch.  I was actually suspecting that it may have something to do with the fact that mesa is now built with Nividia's libglvnd support by default on Arch linux.  Have no way to confirm that though.

**Comment by GeneralFailer** [comment]
Issue persists on 17.0.0-3. Installing 17.0.0-2 will break libglvnd's dependency.

**Comment by twinaphex** [comment]
I'm leaning towards this being a MESA bug rather than a bug in RetroArch.

If it was RetroArch's fault then it makes no sense that the very same code (including snapshots from months ago) still worked fine with the previous Mesa packages and after upgrading them they no longer work.

Sounds like somebody needs to take this upstream to Mesa.

**Comment by orbea** [comment]
I have a recent build of mesa/libdrm from the git master and it doesn't crash here, I can't say I tested kms recently so I'm not sure it was ever broken for me.

`libdrm-2017.03.29_8d61a9a9_master-x86_64-1_git`
`mesa-2017.03.29_1da7a11de8_master-x86_64-1_git`

**Comment by orbea** [comment]
I can confirm this is a libglvnd and / or mesa issue.

I built libglvnd from the git master and rebuilt mesa with `--enable-libglvnd`, now it segfaults RetroArch in kms.
`libglvnd-2017.03.08_8e6e102_master-x86_64-1_git`
`mesa-2017.03.30_331714d72e_master-x86_64-1_git`

I would additionally blame arch for building mesa with something strictly labeled as WIP.
```
This is a work-in-progress implementation of the vendor-neutral dispatch layer for arbitrating OpenGL API calls between multiple vendors on a per-screen basis, as described by Andy Ritger's OpenGL ABI proposal [1].
```
https://github.com/NVIDIA/libglvnd

A likely workaround would be to change the mesa build script to not include `--enable-libglvnd` and rebuild it.

I'll get some backtraces in a bit regardless.

**Comment by orbea** [comment]
The verdict is in, libglvnd sucks.

It first crashed xorg in KMS mode which proceeded to crash my running xorg session (Crashes without xorg running too), but when I went to 'startx' again xorg failed to start until I removed libglvnd and reinstalled my old mesa.

Well here is a backtrace, I can't say I am interested in pursuing this anymore though, my preferred solution is to not use Nvidia crap.
```
(gdb) bt
#0  0x00007ffff1c87c5e in __strstr_sse2 () from /usr/lib64/debug/libc.so.6
#1  0x0000000000565ec1 in gl_check_capability (enum_idx=GL_CAPS_TEX_STORAGE) at libretro-common/gfx/gl_capabilities.c:314
#2  0x0000000000568cfe in gl_load_texture_image (target=3553, level=0, internalFormat=32856, width=1024, height=1024, border=0, format=32993, type=33639, data=0x7fffe40b7010) at gfx/common/gl_common.c:98
#3  0x0000000000561727 in gl_init_textures_reference (gl=0xa164b0, i=0, internal_fmt=32856, texture_fmt=33639, texture_type=32993) at gfx/drivers/gl.c:619
#4  0x00000000005617b2 in gl_init_textures (gl=0xa164b0, video=0x7fffffffca80) at gfx/drivers/gl.c:680
#5  0x00000000005646a0 in gl_init (video=0x7fffffffca80, input=0x972aa0 <current_input>, input_data=0x972aa8 <current_input_data>) at gfx/drivers/gl.c:2082
#6  0x00000000004519de in video_driver_init_internal () at gfx/video_driver.c:819
#7  0x0000000000452ecb in video_driver_init () at gfx/video_driver.c:1523
#8  0x0000000000455f60 in drivers_init (flags=255) at driver.c:325
#9  0x0000000000414fd5 in retroarch_main_init (argc=1, argv=0x7fffffffe348) at retroarch.c:1101
#10 0x000000000042adca in content_load (info=0x7fffffffe210) at tasks/task_content.c:280
#11 0x000000000042bf8a in task_load_content (content_info=0x7fffffffe210, content_ctx=0x7fffffffe150, launched_from_menu=true, launched_from_cli=true, error_string=0x7fffffffe148) at tasks/task_content.c:837
#12 0x000000000042cdef in task_load_content_callback (content_info=0x7fffffffe210, loading_from_menu=true, loading_from_cli=true) at tasks/task_content.c:1397
#13 0x000000000042cf1d in task_push_load_content_from_cli (core_path=0x0, fullpath=0x0, content_info=0x7fffffffe210, type=CORE_TYPE_PLAIN, cb=0x0, user_data=0x0) at tasks/task_content.c:1454
#14 0x0000000000411879 in rarch_main (argc=1, argv=0x7fffffffe348, data=0x0) at frontend/frontend.c:113
#15 0x0000000000411906 in main (argc=1, argv=0x7fffffffe348) at frontend/frontend.c:147
```
https://pastebin.com/mR7LGSDm

**Comment by twinaphex** [comment]
I can try to safeguard against that crash that happens with the strstr call invocation (probably a null pointer dereference). Not sure if it will actually fix anything though, probably not.

**Comment by timde9** [comment]
I filed a bug report with libglvnd for this issue.
https://github.com/NVIDIA/libglvnd/issues/119

**Comment by kbrenneman** [comment]
At a quick glance, I'd guess that the problem is from using eglGetDisplay with a non-NULL native display, since then libEGL has to try to guess a platform. The resulting behavior varies from between implementations (and in Mesa's case, depending on configure options).

Libglvnd can identify an X11 or Wayland display on its own, but if that fails, it'll just return EGL_NO_DISPLAY rather than risk guessing wrong.

As an immediate workaround, and to check if platform detection really is the problem, you can override the guessing by setting the environment variable "EGL_PLATFORM" to a platform enum value. For example, EGL_PLATFORM=0x31D7 would tell it to use EGL_PLATFORM_GBM_KHR.

To handle different platforms reliably, the application needs to call eglGetPlatformDisplay or eglGetPlatformDisplayEXT.

**Comment by timde9** [comment]
tested launching retroarch with above reccommend environmental variable and indeed it has solved the problem.
