### ISSUE TITLE
Bounty to add MIDI support to libretro/RetroArch [$40]

### ISSUE THREAD

**Issue by anothername99** [libretro/RetroArch#4851]
IBM PC (DOS/Win9x), Amiga, RPG Maker 2k/3, PC-98 and SCUMMVM all support MIDI for music, and they all have at least one libretro core, but there is no way for those cores to speak to the user's MIDI device (Such as a real Sound Canvas).

To complete this bounty:

- Add a Libretro MIDI interface that cores can hook into.

- Add a MIDI mapper to RetroArch, allowing the user to select any MIDI Out device (hardware or software) that is recognized by the user's operating system.

- Modify an existing libretro core so that the MIDI Out device plays the game's music, if supported by the game.

**Comment by anothername99** [comment]
Some notes after an IRC discussion:

- This is *not* about integrating a synthesizer into libretro or RetroArch. We want to use external synthesizers from *outside* of RetroArch. The primary use here is hardware synths like the Sound Canvas series, Yamaha MU series, etc. You can also use software synths (especially if you don't own hardware) for testing, but again, they will be outside of RetroArch, only accessed through the operating system's MIDI interface.

- Somebody suggested using PortMidi. If you decide to use this, it would probably sit between RetroArch and the operating system. On the surface, it looks good, but please do your own research and see if this would actually work or make sense. Also, you may still have to do something entirely custom between libretro and RetroArch.

**Comment by casdevel** [comment]
@halfspiral are you working on this?

**Comment by halfspiral** [comment]
@casdevel Thanks for the ping, I almost forgot about this. I figured out what needs to be done but didn't finish the implementation yet. The libretro API should only need one/two additional functions to support MIDI messages. MIDI drivers should probably be separate from the existing audio drivers. I'm using Dosbox as a core for testing, with JACK on Linux as a MIDI backend.

**Comment by casdevel** [comment]
OK, I was just checking. If, for some reason, you wont be able to finish this, I'll appreciate it if you let me know since I'm interested in this.

As a side note, there is no need for additional Libretro API functions at this point.

**Comment by anothername99** [comment]
@halfspiral Do you have an estimate on when your implementation?

@casdevel How would this be done without additional libretro API functions? Keep in mind that we want to keep it as simple as possible for core devs who want to implement MIDI support in their libretro cores, with no need for OS-specific code on the core side.

**Comment by anothername99** [comment]
Also a note, I found that there is a library called QMidi: https://github.com/waddlesplash/QMidi
I'm not a dev, but my understanding is that it would be relatively simple to support multiple platforms if this sits between RetroArch and the operating system.

**Comment by casdevel** [comment]
@anothername99 
> How would this be done without additional libretro API functions?

Using 'retro_environment_t' callback.

Regarding OS-specific code in core(s), there would be no need for that (only on RetroArch side).
For core developers it should be fairly easy, they can probably get away dealing with raw MIDI data only.
I didn't tested this, but I think it should work. On the other hand, RetroArch part requires much more work (every platform will need it's own driver).

**Comment by ShadowOne333** [comment]
Dropping by to say I'm looking forward to the implementation of MIDI playback on RetroArch.
One other core which might benefit (but hasn't been brought up) is also PrBoom.
Hopefully, this also applies to PrBoom to be able to play with the original DOS OST of Doom and its many mods.

**Comment by anothername99** [comment]
@casdevel Fair enough. If you think you can do this, I'd say go ahead. I mean no disrespect to @halfspiral, but honestly, there is no implementation in sight yet as far as I can tell and the original estimation was August 31. I would like to actually use this feature in the foreseeable future. If we were to end up with two implementations and one feels slighted, we'll deal with that then and I'll compensate them.

**Comment by casdevel** [comment]
@anothername99  I'm currently having some issues with Bountysource and I'm waiting to see how will that end up before I decide what to do next. In any case I'll try to help with this (if @halfspiral doesn't come up with something in the meantime).

**Comment by Heather95** [comment]
Added a bounty to show my support, literally the one thing keeping me from switching to these cores over their stand-alones is lack of MIDI support. Hopefully @casdevel or @halfspiral can create this feature.

**Comment by casdevel** [comment]
@anothername99 I will probably start working on this in the next few days, and I don't know which OS (Linux/Windows) will be better choice for the first driver, so if you prefer one over other let me know, and I will take that into consideration.

**Comment by anothername99** [comment]
@casdevel Sorry again for the delay. I was away for a while.

My preference would be Windows (preferably XP or 7). It's much easier for me to test on. On Linux I assume Jack would be involved and I really have no idea how that thing works. I'll accept it either way though, it's just that I would need some help to test it on Linux. Thanks.

**Comment by casdevel** [comment]
@anothername99 @Heather95 I implemented RetroArch (Windows only) and Hatari MIDI support. Code is at [https://github.com/casdevel/RetroArch/tree/midi](https://github.com/casdevel/RetroArch/tree/midi) and [https://github.com/casdevel/hatari/tree/midi](https://github.com/casdevel/hatari/tree/midi). I didn't upload binaries, if you need them let me know.

Note that you need to set-up some RetroArch options first, MIDI driver should be set to 'winmm' and MIDI output should be set to your device of choice.

Here is the list of games that I used for testing: Bombjack, 'Karate Kid - Part 2', Pirates, Sapiens, 'The Adventures of Maddog Williams in the Dungeons of Duridian' and Ultima 4. Note that some of them produce both MIDI and audio data simultaneously.

There is possibility that current implementation is incompatible with some RetroArch feature(s). If you encounter some strange behavior let me know and I'll try to fix it.

**Comment by anothername99** [comment]
@casdevel Yes! Yes! yes! Thank you!!

I can look into compiling on Windows, but if you don't mind uploading binaries that would certainly help us a lot.

Also, you can go ahead and claim the bounty. I have seen your work before and I trust that there's nothing funny going on. The little that I understand of the code also indicates that. I'll still test it and report my findings when I have binaries.

**Comment by casdevel** [comment]
I uploaded 32-bit binaries, they can be downloaded from [https://github.com/casdevel/RetroArch/releases/download/v1.7.3-midi/retroarch.7z](https://github.com/casdevel/RetroArch/releases/download/v1.7.3-midi/retroarch.7z). DOSBox and Hatari cores are included.

@anothername99 regarding bounty, I think that bounty can be claimed only when this issue is closed and all "bakers" accept solution. Also, there is no need to rush anything, there may be some "hidden" issue(s) that will pop up on some machine/setup.

**Comment by anothername99** [comment]
@casdevel I did some testing with the DOSBox core. It seems to work just as well as stand-alone. Descent and Day of the Tentacle play the music through my hardware without a problem. I wasn't able to get it to work with Zeliard, but that game is very tricky in general. Probably not your code at fault.

One issue though was that I got RetroArch to crash by changing the MIDI Out device in RetroArch's settings while a game was running. If changing it like this isn't supposed to work, then maybe you can make RetroArch ignore the change until RetroArch has restarted, and add a note about this.

We can test this some more, but I'm already very, very happy with the work so far!

**Comment by anothername99** [comment]
For this first implementation, I consider it done if we have Windows support. I'm considering opening additional bounties for other operating systems like Linux and Haiku, as well as more cores.

**Comment by twinaphex** [comment]
OK, I guess this is ultimately up the bounty pledgers. Since you donated the majority of the money (with Heather95 chipping in an additional $10), I'm fine with that. @Heather95 Do you agree with this, that Windows support initially is enough for successful completion of this current bounty?

**Comment by twinaphex** [comment]
OK, after @anothername99 has tested those builds, you can send the PRs and we can consider the bounty completed.

**Comment by anothername99** [comment]
@twinaphex @casdevel I tried the new build and I think this works well enough that we can consider it complete. I am *very* interested in MIDI In, but there isn't a lot of DOS software to test it with. I would like to try the MIDI test core though.

Also, casdevel, would you be interested in more bounties? I posted one for PCem (https://github.com/libretro/RetroArch/issues/6891) today. I may also post other bounties like:

- Linux MIDI driver (we can explicitly target Lakka to avoid the distro hell)
- Native Haiku audio/input/MIDI driver (3 bounties, you can pick which one seems most interesting)
- Bounty for MIDI support in more cores

**Comment by casdevel** [comment]
@anothername99 you can download test core from [https://github.com/casdevel/RetroArch/releases/tag/v1.7.3-midi2](https://github.com/casdevel/RetroArch/releases/tag/v1.7.3-midi2), "how to" is also on the page.

Regarding bounties, if no one starts writing Linux MIDI driver I'll probably write one. Explicit targets are not necessary, ALSA should be a safe bet. With Haiku I'm not familiar, but I'll check it out. Bounty for MIDI support in more cores, I think, it's unnecessary, since, if a core send/receive MIDI data one byte at a time (which is probably the case with all of them), you can almost copy and paste code from one core to another to add MIDI support.

**Comment by twinaphex** [comment]
OK, I merged the MIDI PR now.

I trust that @casdevel will give us another PR tomorrow with the documentation notes. I will give @anothername99 the opportunity to test this with the latest nightly (once it has finished building), and from there on he can decide to close the comment so that we can finalize this bounty.

**Comment by anothername99** [comment]
The buildbot still isn't done, but I doubt there will be any issue that didn't already exist in casdevel's builds. Also, please keep in mind that in order to fully test this feature, especially the MIDI In part, we need more cores. With an updated PCem port especially, if we can get MIDI In support there, would allow for a whole host of new test cases considering the amount of music programs available for Windows 98/ME/XP.

@casdevel I tried out your test core a bit and I got good results. I did two tests with this:
1) TMIDI Player -> loopMIDI -> RetroArch -> Roland SC-D70. Works: https://i.imgur.com/Q0X4QNa.png
2) Roland A-49 (USB MIDI keyboard) -> RetroArch -> Roland SC-D70. Also works.

I did have an issue at first where I had to change the MIDI settings in RetroArch back and forth a few times. I don't know if this is a bug with the implementation or a hardware problem. In the end I got it to work though.

Anyway, I'll close this now. We can open new tickets if any issues pop up. Thanks again for this awesome feature!

**Comment by twinaphex** [comment]
Hi guys, that MIDI test core looks cool. Can the source to that be found anywhere? It would make a great addition to libretro-samples (https://github.com/libretro/libretro-samples).

**Comment by casdevel** [comment]
@twinaphex I uploaded source at [https://github.com/casdevel/RetroArch/releases/tag/v1.7.3-midi2](https://github.com/casdevel/RetroArch/releases/tag/v1.7.3-midi2). Code formatting is a little different from RetroArch's but code is short so reformatting it shouldn't be a problem. Also, there are no license, you are free to apply any license to the source.

**Comment by fr500** [comment]
So, how do I use this with dosbox? I enabled the stuff in RA, but do I need a custom dosbox config to enable the device, tyrian keeps saying no midi drivers found.

**Comment by fr500** [comment]
NVM, just works, midi music in tyrian stinks (although it could be the synth I guess)

**Comment by fr500** [comment]
So I tried again, with bassmidi and a Roland soundfont I found but I get only drums???
Ist that normal?

It should sound like this
https://www.youtube.com/watch?v=20Kwbkn2Ptg

But I get drums only... what to do?

**Comment by fr500** [comment]
I tried omnimidi now and with the soundfont I'm testing canyon,mid sounds fine in other apps.
Tried dosbox standalone too and it's perfectly fine.

Maybe our old outdate dosbox has bad midi support?

**Comment by fr500** [comment]
![image](https://user-images.githubusercontent.com/1721040/42407004-46af2924-8179-11e8-8912-e19e9cd45f43.png)

Tyrian track 6 in dosbox libretro:
![image](https://user-images.githubusercontent.com/1721040/42407007-4e0d3aee-8179-11e8-9295-e576f95056ec.png)

Same track in standalone:
![image](https://user-images.githubusercontent.com/1721040/42407011-62c341a4-8179-11e8-8a4a-8037c3340bde.png)

**Comment by casdevel** [comment]
@fr500 maybe it's something game related. On my machine Tyrian don't produce sound at all and frame rate is extremely low (few FPS). 
Can you try Space Quest 3? That game should work with Windows built-in general MIDI software synth. I also tested Space Quest 3 with CoolSoft VirtualMIDISynth and Roland MT32 sound fonts (FluidSynth-s general MIDI sound fonts work too).

**Comment by anothername99** [comment]
Might be a bug. It should work out of the box, provided you selected the right MIDI Out device in XMB. And if you configured something wrong, I would expect there to be 0 voices.

**Comment by fr500** [comment]
That's the thing, I get midi sound, just not all voices.
I'll try another game, and I'll also try to compile standalone dosbox circa
that version.

**Comment by casdevel** [comment]
> That's the thing, I get midi sound, just not all voices.

Then you should check which MIDI device(s) game supports, then find appropriate sound fonts. Different devices usually have different set of instruments.

**Comment by fr500** [comment]
I tried dosbox libretro and dosbox standalone with the same game, same midi device, same sound font, thats what the screenshots above are telling about.

Identical setup in both cases other than the fact one was dosbox libretro.

**Comment by fr500** [comment]
I'll make a video I guess :P
BTW I also made a new dosbox fork (based on the latest SVN) but I had to remove the midi stuff because it changed a lot from the 3 year old version we have, once I push it I'd appreciate guidance to readd midi support.

**Comment by anothername99** [comment]
I would like to try Tyrian too. Is there a setting in the game for MIDI?

**Comment by fr500** [comment]
Hey, you just run setup first, set MIDI to MIDI 330h
There is a sound test even, I tried on both and there is where I find the difference

**Comment by fr500** [comment]
you have to use the older core for now, I stll haven{t figured the midi interface

**Comment by fr500** [comment]
Fixed in the new core :)
![image](https://user-images.githubusercontent.com/1721040/42424562-be844b90-82d3-11e8-99d5-f0ad78dd3be2.png)

Also (but unrelated) added IPX support

**Comment by anothername99** [comment]
Very cool, thank you! Also please add your core to the buildbot if you don't mind so everyone can try.

**Comment by ner00** [comment]
@twinaphex

I'm not entirely sure what happened here... was the native MIDI support ever added to this core? I'm using latest binaries and cores and it doesn't seem to work at all. `mixer /listmidi` comes up empty instead of showing Microsoft GS Wavetable Synth. The user who initially pledged to the bounty and did some work on it seems to have disappeared so... was this a thing?
