### ISSUE TITLE
Mouse not working properly

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#5047]
## Description

The mouse pointer is jumping from one position to another

### Expected behavior

The mouse pointer should be stable

### Actual behavior

The mouse pointer is jumping from one position to another

### Steps to reproduce the bug

Launch RetroArch on Arch Linux on a macbook air 2013

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: cea6dbbb6a4d639299dd11297513124be406336f

### Environment information

- OS: Arch Linux
- Compiler: gcc version 7.1.1 20170528 (GCC)

**Comment by twinaphex** [comment]
Do a bisect, it could be this commit -

https://github.com/libretro/RetroArch/commit/e698e75a51c309ccb200c26b2af901be000606a8

but we have to be sure first that is the case.

**Comment by twinaphex** [comment]
I can still use the mouse fine, it might be the touchpad which is broken though. I already noticed this earlier with that new commit.

**Comment by casdevel** [comment]
@Kivutar Is this happens when you using mouse or touchpad?

**Comment by casdevel** [comment]
Maybe 34be556 will help.

**Comment by twinaphex** [comment]
Yes I just committed this. So @kivutar should be able to test the latest code and see if it fixes his problem.

**Comment by Kivutar** [comment]
@casdevel it's when using a touchpad.

The bug is still present.

**Comment by casdevel** [comment]
I will need more info in order to reproduce this bug, since on my laptop pointer is working properly.

Which video driver do you use?
Did you look at log and checked that RA is using udev input driver?

**Comment by Kivutar** [comment]
Sure, I'm using X11+GL:

```
RetroArch [INFO] :: This is RetroArch version 1.6.0 (Git cea6dbbb6)
RetroArch [INFO] :: === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES 
Built: Jun 10 2017
RetroArch [INFO] :: Version: 1.6.0
RetroArch [INFO] :: Git: cea6dbbb6
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [Config]: Loading default config.
RetroArch [INFO] :: [Config]: loading config from: (null).
RetroArch [INFO] :: Looking for config in: "/home/kivutar/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: [Audio]: Set audio input rate to: 29970.03 Hz.
RetroArch [INFO] :: Found shader "/home/kivutar/.config/retroarch/shaders/retroarch.cgp"
RetroArch [INFO] :: Found shader "/home/kivutar/.config/retroarch/shaders/retroarch.glslp"
RetroArch [INFO] :: [Video]: Video @ 960x720
RetroArch [ERROR] :: [Wayland]: Failed to connect to Wayland server.
RetroArch [INFO] :: [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
RetroArch [INFO] :: [GL]: Found GL context: x
RetroArch [INFO] :: [GL]: Detecting screen resolution 1440x900.
RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 960, H = 720.
RetroArch [INFO] :: [GLX]: Found swap function: glXSwapIntervalEXT.
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
RetroArch [INFO] :: [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Ivybridge Mobile .
RetroArch [INFO] :: [GL]: Version: 3.0 Mesa 17.1.1.
RetroArch [INFO] :: [GL]: Using resolution 960x720
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: [GLSL]: Checking GLSL shader support ...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: [GL]: Using GL_RGB565 for texture uploads.
RetroArch [INFO] :: [udev] Adding device /dev/input/event12 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/event11 as type ID_INPUT_TOUCHPAD.
RetroArch [INFO] :: [Joypad]: Found joypad driver: "udev".
RetroArch [INFO] :: [Font]: Using font rendering backend: freetype.
RetroArch [INFO] :: [DBus]: Suspended screensaver via DBus.
RetroArch [INFO] :: [PulseAudio]: Requested 24576 bytes buffer, got 18432.
RetroArch [INFO] :: [Menu]: Found menu display driver: "menu_display_gl".
RetroArch [INFO] :: [Font]: Using font rendering backend: freetype.
RetroArch [INFO] :: [Font]: Using font rendering backend: freetype.
RetroArch [INFO] :: bringing_up_command_interface_at_port 55355.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: Loading history file: [/home/kivutar/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: Loading history file: [/home/kivutar/.config/retroarch/content_music_history.lpl].
RetroArch [INFO] :: Loading history file: [/home/kivutar/.config/retroarch/content_video_history.lpl].
RetroArch [INFO] :: Loading history file: [/home/kivutar/.config/retroarch/content_image_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
RetroArch [INFO] :: [PulseAudio]: Unpausing.
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
RetroArch [INFO] :: [PulseAudio]: Pausing.
RetroArch [INFO] :: [PulseAudio]: Unpausing.
RetroArch [INFO] :: [PulseAudio]: Unpausing.
RetroArch [INFO] :: [Config]: Saved new config to "/home/kivutar/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: [PulseAudio]: Pausing.
RetroArch [INFO] :: [XINERAMA]: Xinerama version: 1.1.
RetroArch [INFO] :: [XINERAMA]: Xinerama screens: 1.
RetroArch [INFO] :: [XINERAMA]: Saved monitor #0.
RetroArch [INFO] :: [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
```

**Comment by casdevel** [comment]
I'm going to look at code to see what can be changed to help us track this down.

**Comment by casdevel** [comment]
Try this from [https://github.com/casdevel/RetroArch/tree/touchpad](https://github.com/casdevel/RetroArch/tree/touchpad).

Move pointer few times and exit RA.
Post four lines from log that starts with RetroArch [INFO] :: [TOUCHPAD]:

**Comment by Kivutar** [comment]
I compiled it, but I get no log messages with [TOUCHPAD] exept

    RetroArch [INFO] :: [udev] Adding device /dev/input/event11 as type ID_INPUT_TOUCHPAD.

**Comment by casdevel** [comment]
Look at  lines 780 trough 787 of /input/drivers/udev_input.c. There must be four RARCH_LOG function calls to confirm that you compiling the correct file. It looks like some mix-up with source tree.

**Comment by casdevel** [comment]
I just noticed that on my laptop pointer is available only when external mouse is connected.
Udev touchpad handling code has to be rewritten, this modifications I made only help in some situations.

@Kivutar wait until I have something that should work on all machines in all circumstances.

**Comment by Kivutar** [comment]
Additional information: the touchpad now behaves like a touch screen. When I tap my finger to the bottom left of the touchpad, the pointer directly jumps to the bottom left of my screen.

**Comment by casdevel** [comment]
Maybe [this](https://github.com/casdevel/RetroArch/tree/udev) will help. I couldn't test it on my machine.

**Comment by casdevel** [comment]
@Kivutar Regarding touchpad behaving like a touch screen, have you tried code at [https://github.com/casdevel/RetroArch/tree/udev](https://github.com/casdevel/RetroArch/tree/udev)?

**Comment by gamaghostmagus** [comment]
i have this problem too
