### ISSUE TITLE
With raw input driver, Desmume's cursor doesn't show up

### ISSUE THREAD

**Issue by Bezier89** [libretro/RetroArch#5179]
## Description

Change the input driver in Retroarch from the default (dinput) to "raw". Load a DS game using Desmume, which uses a mouse-controlled cursor to interact with the DS's touch screen.

### Expected behavior

Cursor shows up, able to interact with the game.

### Actual behavior

Cursor does not show up, clicking appears to do nothing. If this is expected behavior (i.e. simply haven't gotten around to adding mouse support to "raw"), then perhaps this should be stated when selecting the input driver. For example, it could be labeled "raw (no mouse)" or "raw (controller only)".

### Environment information

RetroArch: 1.6.0 (stable)
OS: Windows 10

**Comment by casdevel** [comment]
I created PR [https://github.com/libretro/desmume/pull/118](https://github.com/libretro/desmume/pull/118) that should fix this issue.

@Bezier89 in meantime try changing "Settings/Input/Input User 2 Binds/User 2 Mouse Index" to the index of mouse device that you are using.

**Comment by Bezier89** [comment]
@casdevel FYI I'm still seeing this issue. Using Desmume @ 71fcf52 (includes your commit) and Retroarch 1.6.3.

**Comment by casdevel** [comment]
Take a look at log and find line(s) that start with "[INFO] [WINRAW]: Mouse #". If you have one mouse, and log reports more than one, changing "User 1 Mouse Index" may solve the problem.

**Comment by Bezier89** [comment]
So I didn't see "INFO] [WINRAW]: Mouse #" in the log at all, but I figured out the issue. It's because I'm using software (in particular, Steam) to treat my controller as a virtual mouse. If I plug in a physical mouse it works fine. With "DInput" it works fine in both cases, so I'll just go ahead and stick with that for now.

**Comment by markwkidd** [comment]
Is anyone else still having trouble using the winraw input driver with Steam? This issue seems like it can be closed. The last message was posted in 2017.
