### ISSUE TITLE
Task Failed: Extracting "cheats.zip"

### ISSUE THREAD

**Issue by ddelella** [libretro/RetroArch#5391]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When attempting to Update Cheats via the Online Updater the extraction gets to 89% then fails with the message "Task failed: Extracting 'cheats.zip'".

### Expected behavior

The file would download and extract successfully.

### Actual behavior

Task failed: Extracting 'cheats.zip'

### Steps to reproduce the bug

1. Start RetroArch
2. Select Online Updater
3. Select Update Cheats

### Bisect Results

Not sure when it began to occur as I recently updated from 1.5.x to 1.6.7.  I confirmed the issue in the release version.  I then downloaded the latest code and confirmed it existed there as well.

### Version/Commit

All system information and build numbers are attached via a screen shot of the system information

![info](https://user-images.githubusercontent.com/548747/29976684-d4c97b74-8f08-11e7-833b-7b4cd6e5511c.png)
![error](https://user-images.githubusercontent.com/548747/29976683-d4c6d522-8f08-11e7-81e7-a5b98e6920d6.png)

**Comment by RobLoach** [comment]
What platform is this? I've heard Windows doesn't do ? characters well. May be other filenames in cheats that have speciial characters. Mind checking libretro-databse for them?

**Comment by ddelella** [comment]
The system information screen shot has all the information about the platform.  It is Windows 10 64-bit.   I don't know if this is relevant but it could be.  I tried to delete the RetroArch zip extracted release for 1.6.7 and there are two files in the "/cheats/Nintendo - Nintendo DS" folder that will not delete.  They are listed with 0kb and when trying to delete it says "This is no longer located in .... Verify the item's location and try again."  These files are Barbie Fashion Show and Planet Rescue.

**Comment by RobLoach** [comment]
This should fix it: https://github.com/libretro/libretro-database/pull/513 .... Mind a review?

**Comment by fseu-uniba** [comment]
Nope, extraction still fails... anyway sorry if this is a dumb question (I don't know how/if the cheats.zip archive interacts with the database), but how could a database update fix the problem if the files with special characters (some NDS cheats) are inside the downloaded cheats.zip archive?

**Comment by RobLoach** [comment]
Ran through another rename run: https://github.com/libretro/libretro-database/commit/d14346d5c849e5a449159294d001bb3ba8647b9c ... Once buildbot compresses the cheats again, have another try.

**Comment by fr500** [comment]
The whole cheats.zip is crap though, those scrapped cheats hardly ever work....
Cheats and thumbs should be scrapped from an online service using the content name and/or CRC instead this one zip fits all approach that utterly blows.

**Comment by RobLoach** [comment]
Agreed, an API around it would be good. This is about cheats.zip not extracting, which should be fixed. Feel free to close this one.

**Comment by orbea** [comment]
This should be fixed and works here so I am going to close this issue.
