### ISSUE TITLE
Disk Swapping for Sega Saturn Not Working

### ISSUE THREAD

**Issue by Phastor** [libretro/RetroArch#5640]
## Description

Attempting to swap disks in a loaded Sega Saturn .m3u results in error "Failed to set disk." Beetle Saturn also doesn't seem to recognize that I've tried to open the virtual disk tray via RA, as the game continues to play as normal while open.

### Expected behavior

Emulator to recognize that tray has been opened and that a different disk has been loaded. Expecting system to boot to the media player menu after reset while virtual tray is "open."

### Actual behavior

Emulator does not register that the tray has been opened when done so through RA menu. Also gives error, "Failed to set disk n/n" when attempting to change disk index.

### Steps to reproduce the bug

1. Load .m3u in RA
2. Enter RA menu
3. Select "Disk Control"
4. Select "Disk Cycle Tray Status" (Returning to game after this shows that it doesn't see that the tray has been opened.
5. Back in RA menu, attempt to change disk index. Results in "Failed to set disk n/n"

### Version/Commit
1.3.6

### Environment information

- OS: Windows 7 and Ubuntu

**Comment by orbea** [comment]
Can you try a more recent RetroArch version to compare this is still an issue? Preferably a nightly.

**Comment by Phastor** [comment]
Just tried the latest nightly build with the same results.

If it helps narrow it down at all, PSX games have no issues swapping disks within an m3u in the RA menu.

Another thing: Loading the .m3u will throw an error "Uncorrectable data at sector 0," However the game will play normal with the exception of the disk swapping issue. Loading disk1 directly instead of through the m3u will not give the error. Not sure if this is related to the swapping issue or not.

**Comment by hiddenasbestos** [comment]
This was a core issue - fixed here: https://github.com/libretro/beetle-saturn-libretro/pull/95

**Comment by Phastor** [comment]
Fantastic!

Updated core in RA and it does indeed recognize the tray cycle and swapped disks.

It still throws the "Uncorrectable data at sector 0" when first loading an m3u, but so far I haven't observed any adverse effects from it.
