### ISSUE TITLE
Some thumbnails are not extracted on right folder.

### ISSUE THREAD

**Issue by Danixu** [libretro/RetroArch#5787]
## Description
Some of the Thumbnails pack are extracted on thumbnails folder (root) instead inside thumbnails/console_name. This happen on some packs only. I've tried:
Wrong:
- NES
- GB
- GBA
- SNES

OK:
- GBC
- NDS
- N64

### Expected behavior
After download a thumbnail pack, the content should be extracted to a folder with the console name (like for example "Nintendo - Nintendo Entertainment System"), inside thumbnails folder.

### Actual behavior
Some of the covers are downloaded and extracted inside thumbnails folder. If you just create a folder with console name and move that files to that folder, then the thumbnails are showed on program.

### Steps to reproduce the bug
1. Go to main menu > Online Updater
2. Enter on Thumbnails updater
3. download the "Nintendo - Nintendo Entertainment System.zip" file

### Version/Commit
- RetroArch: [1.6.9/e8b10d342]

### Environment information

- OS: Windows 10 x64

**Comment by twinaphex** [comment]
@RobLoach This is relevant I think to what I pointed out before.

**Comment by RobLoach** [comment]
This should be fixed now. CloudFlare could have the file cached. Could you test it out again the GB one again?

**Comment by Danixu** [comment]
For now still failing, but if is cached maybe it will take one or two days to refresh.

**Comment by fr500** [comment]
purged the cache completely try now

**Comment by Danixu** [comment]
Thanks!!!, now looks OK.

Greetings!!
