### ISSUE TITLE
1.7.2 crashes with mother 3 translation hack

### ISSUE THREAD

**Issue by kcin2001** [libretro/RetroArch#6453]
## Description

when loading up the mother 3 v1.2 translation hack in vba-m, vba-next, and mgba (And possibly the others) and in 1.7.2 retroarch just crashes, this does not happen in 1.7.1

### Expected behavior

the game to run fine

### Actual behavior

retroarch crashes

### Steps to reproduce the bug

1. patch a mother 3 rom with the v1.2 english translation hack
2. load it up in a gba core in retroarch
3. "retroach has encountered a problem"

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.2 59bf897561 

### Environment information

- OS: windows 8.1
- Compiler: [In case you are running local builds]

**Comment by kcin2001** [comment]
i dont know if this works with any other roms but i would assume it would affect other things than just this hack

**Comment by kcin2001** [comment]
achievments off makes it not crash

**Comment by retro-wertz** [comment]
hmmm is this similar to mine? game that are detected as game ID 0 crashes whenh cheevos enabled?

Related? please confirm:
https://github.com/libretro/RetroArch/issues/6448

**Comment by fr500** [comment]
seems it uses one matching function, then another then another and so forth, then in mgba's case it reaches this code:

```c
   CORO_SUB(FILENAME_MD5)
   {
      char base_noext[PATH_MAX_LENGTH];
      fill_pathname_base_noext(base_noext, coro->path, sizeof(base_noext));

      MD5_Init(&coro->md5);
      MD5_Update(&coro->md5, (void*)base_noext, strlen(base_noext));
      MD5_Final(coro->hash, &coro->md5);

      CORO_GOTO(GET_GAMEID);
   }```

But mgba is not a `needs_fullpath` core, and path is populated from `info->path` so it ends up crashing.

**Comment by fr500** [comment]
I pushed a fix for the mgba's case. Can you check if that fixes it for you?

**Comment by kcin2001** [comment]
yeah the exe you had in the discord works but latest nightly still doesnt
