### ISSUE TITLE
[3DS] crashes on startup unless i change to old UI through editing the config file

### ISSUE THREAD

**Issue by brunocar** [libretro/RetroArch#6691]
## Description

the 3DS build wont launch on my new 3ds XL running the latest stable of luma3DS unless i go to the config file to set it so that the start up UI is the old one instead of the XMB style one, if i try to set it to the XMB UI it crashes.

### Expected behavior
it should launch without crashing or crashing the app when set to it

### Actual behavior

it crashes no matter what, going straight to an arm11 error screen

### Steps to reproduce the bug

1- launch app with default config file
2- watch it crash into an arm11 error

### Version/Commit

- RetroArch: latest stable as of the day of posting

### Environment information

- OS: luma3DS latest stable as of the day of posting

**Comment by bparker06** [comment]
Can you try installing the 2048 core and seeing if it runs then?

**Comment by brunocar** [comment]
do you mean the standalone build or the core itself?

**Comment by twinaphex** [comment]
@meepingsnesroms says this can be closed now.

**Comment by brunocar** [comment]
why is it closed? i still cant use retroarch, i installed the latest build and it doesnt crash, it just soft locks on a black screen, but that still doesnt mean its fixed

**Comment by twinaphex** [comment]
Did you try the latest nightly instead of the stable?

@meepingsnesroms Might want to keep an eye on this based on his response.

**Comment by brunocar** [comment]
mind linking it? i cant seem to find anything but the links to the latest stable (1.7.3)

**Comment by brunocar** [comment]
just so you guys now, i forgot to include that i can boot the individual core CIAs, but the main retroarch CIA just wont boot

**Comment by brunocar** [comment]
NVM, found it, i'll report back once i try them

**Comment by meepingsnesroms** [comment]
Well it will check what the last loaded core is and find the old .core file which is no longer supported the essentially try to execute a corrupt file but a clean installation should fix it, copy the core cias then launch and wait 20 seconds for the first one to install.

**Comment by brunocar** [comment]
did a compleatly clean install using today's nightly, its certainly not giving me a black screen anymore, it just boots me back to the home menu after the 3DS logo

**Comment by brunocar** [comment]
the standalone apps still work (though a lot of options still crash the console)

**Comment by meepingsnesroms** [comment]
I actually tested everything with genesis plus gx so I test salamander (the launcher that blackscreens).

**Comment by meepingsnesroms** [comment]
Also what options are crashing the console, I can try to fix those next.

**Comment by meepingsnesroms** [comment]
I just changed core launching and the build system is out of sync with the application, copy one of the .cia core files to sdmc:/retroarch/cores and then load it again, it will take ~20 seconds to launch, thats ok its installing the core if its not installed, then it will work.

**Comment by brunocar** [comment]
marvelous, that said for some weird reason, a gamebatte standalone core icon shows up on my home menu every time i boot the main retroarch app, no matter how many times i delete it (mind you, it was the first core i copied over to the cores folder)

**Comment by brunocar** [comment]
scratch that, every core's icon shows up when i try booting it, doesnt this make the retroarch app kinda redundant? are the home menu icons supposed to self delete but it got bugged?

**Comment by meepingsnesroms** [comment]
Thats how core launching works with the cia builds, cias have to be installed in order to run, and if not installed it auto installs, the 3dsx build doesnt require installation to run and wont do that.

This is all part of trying to get the 3ds port to be able to be able to manage its self without user intervention, just put all the icons in a home menu folder like before if you want to use the main launcher.

The RetroArch app itself is just a file lookup program that loads the most recent core and if never launched before launches the first core in alphabetical order.

**Comment by meepingsnesroms** [comment]
In a month it should all be working fine in both 3dsx and cia ports and the outdated .core files will be gone.

**Comment by brunocar** [comment]
thank you for the help, i dont have much time to report bugs right now, so i'll wait till the next stable for that, its quite crashy though, a bunch of video options crashed it, trying to enter the rosalina menu soft locks the console and trying to use the background template menu without templates gives me an arm11 error.
also, i have a small suggestion if you dont mind, could you implement a feature in which retroarch will uninstall whatever CIA core you are using after you close the app manually? it would really help for those of us with limited space in our log book, i know that would make actually using those cores take longer due to them having to get installed, but its just an idea you could use.
thank you for all your help, i hope you the best of luck fixing this extremely complex app.
