### ISSUE TITLE
Downloading Assets on Wii U never finishes

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#7278]
## Description

Downloading assets never finishes, it resets to 0% once it reaches 30% three times, then it does another extra 10% (adding up to 100%), but it never extracts.

### Expected behavior

It should work?

### Steps to reproduce the bug

1. Online updater
2. Update assets
3. Wait for an eternity
4. Boom, nothing

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.4 stable

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by RobLoach** [comment]
Is the assets package too large now? 141MB

**Comment by twinaphex** [comment]
The progress indicator not reporting correctly after 30% is a known flaw and might be a separate problem, and it happens on 32bit OSes. @kivutar knows about this. To date, nobody has looked into it or bothered to fix it though. We could use help here.

**Comment by orbea** [comment]
Is it possible its just so slow it doesn't seem to finish and the broken progress bar on some platforms gives the illusion that its stuck?

**Comment by fr500** [comment]
No it never does, it gets to 30%, then starts over till 30% then again,
then 10% then  I checked the SD card after a while... no assets.

**Comment by ShadowOne333** [comment]
I can confirm that this is indeed an issue, I got it when I tried to update the assets some days ago too, so it's not a connection being too slow issue.

**Comment by orbea** [comment]
Maybe this is a related issue, it sounds familiar.

https://github.com/libretro/RetroArch/issues/5692

**Comment by fr500** [comment]
It's downloading fine now (the issues with it looping/restarting was fixed, it was a math problem)
But it never extracts. I figure it's a memory problem because smaller packages do work.

I think Update assets should only download the assets for the **current menu driver** that would alleviate the problem in these memory constrained platforms.

Furthermore menu driver themes should be "dynamic" and populated dynamically instead of hardcoded.

**Comment by Cloud9Skywalker** [comment]
I am beginning to have this same problem now. So I decided to remove retroarch from App Store and removing the retroarch folders on my SD card and just start from scratch. After downloading the app again from the store and launching it. I update core info files and then move on to update assets but it keeps disappearing after 61% or so and never finishes. I keep on trying but it doesn't finish downloading. Any thoughts?

**Comment by AshleyPikachu** [comment]
Hi, this is still broken on 1.8.1 stable and the current 1.8.1 nightly. The issue currently is that Assets downloads but does not unzip. Also bundle is missing so it has to downloaded on pc and put in manually otherwise playlist fail to work.

**Comment by IllMethods** [comment]
I'm getting this issue on 1.84 on WiiU, Ps3 and Switch. Managed to copy it over from pc to switch and that worked but not for Ps3.

**Comment by LibretroAdmin** [comment]
@QuarkTheAwesome Is this still an ongoing issue, or can this be closed now?

**Comment by QuarkTheAwesome** [comment]
Since nobody's complained about it since those patches, it's probably fine
