### ISSUE TITLE
(Vita) RetroArch does not recognize the time zone from the system

### ISSUE THREAD

**Issue by CatKasha** [libretro/RetroArch#7632]
## Description

RetroArch does not recognize the time zone from the system, and the clock is displayed without correction the time zone.

### Expected behavior

Clock in RetroArch are the same as in the system

### Actual behavior

Clock in RetroArch show the time without correction the time zone

![default](https://user-images.githubusercontent.com/19823797/48896377-89b9fb80-ee58-11e8-8bdf-6c12aecf75e5.png)

System clock with time zone UTC+3
![default](https://user-images.githubusercontent.com/19823797/48896396-92123680-ee58-11e8-9c69-15ef109a27e2.png)

### Version/Commit
- RetroArch: stable 1.7.5
- RetroArch: nightly 2018-11-21 | b3d38c4

### Environment information
- PS Vita 3.60 Henkaku

**Comment by althonos** [comment]
Fixed in `vitasdk`, this should not occur in the next release if RetroArch is built against latest `newlib`.

**Comment by ofry** [comment]
But new vitasdk builds failed... https://github.com/vitasdk/autobuilds/issues/14

**Comment by CatKasha** [comment]
Hi developers, thank you for developing a patch for Vita
Today I checked the nightly build 2019-03-10 | ed5bd80 , and the time zone still does not work

**Comment by CatKasha** [comment]
It looks like time zones are working now, checked on version 1.8.1 (stable), thanks!
