### ISSUE TITLE
Menu toggle hotkey not used for closing the menu

### ISSUE THREAD

**Issue by luluco250** [libretro/RetroArch#7756]
## Description
The `input_menu_toggle` setting seems to only affect which key opens the menu, the menu still can only be closed with `F1` (or resuming through the quick menu).

### Expected behavior
That `input_menu_toggle` is used for both opening *and* closing the menu.

### Actual behavior
Closing the menu doesn't use the key set with `input_menu_toggle`, instead only the default `F1`.
Opening it works fine.

### Steps to reproduce the bug

1. Set the menu toggle hotkey (or `input_menu_toggle` directly in `retroarch.cfg`) to a different key than the default (`F1`), like `ESC`.
2. Run some content.
3. Use the newly configured key to open the menu.
4. Try closing the menu using the same key, when it doesn't work try using `F1`.

### Bisect Results
I've noticed this after seeing the menu wouldn't close with my set key (`ESC`), I tested using the default key and it closed. I've also tested setting the hotkey to `Tab` but the problem still occurred, I suspect it'd happen to other keys as well.

### Version/Commit
- RetroArch: v1.7.5/c9c6c5a

### Environment information

- OS: Linux Xubuntu 18.04.1 LTS x64 (though I noticed the same problem on Windows 10 Pro x64)
- Compiler: GCC v7.3.0 x64 (obtained through `retroarch --version`, I didn't actually compile RA myself)

**Comment by orbea** [comment]
I can reproduce this with the master when changing the keybind to `j` since that doesn't conflict with other binds.

**Comment by orbea** [comment]
This broke between `v1.3.6` and `v1.4.1`.

First bad commit.
```
commit a9a2749af988781e3800ccf5e111f17124869ddf
Author: twinaphex <libretro@gmail.com>
Date:   Thu Oct 27 00:13:29 2016 +0200

    Add input_menu_keys_pressed

:040000 040000 d77ebbd24f6524ae15e03dcc66117157c9f39990 070cae2ce5928f1f6a8af072a18efd88d9b14d98 M	input
:040000 040000 afee92165d182d44bdbe04acb6690feb9021ba40 6890e24b09d3346e71e8e67306a02c309f3449e2 M	menu
:100644 100644 ebfcfe7781d51d6b9aac9f359abe043b3619866f 491b23c66f016599ddebc891f1b99c62df3932f6 M	runloop.c
```
a9a2749af988781e3800ccf5e111f17124869ddf

In the parent commit it works, in this commit only the gamepad can close the menu and in the follow commit (2bcbe017cd82c2a02ba031ab50c8d606f0769158) it matches the current behavior.

**Comment by orbea** [comment]
I think the problem is the use of `RETROK_F1` here.

https://github.com/libretro/RetroArch/blob/708c9c0774518352d382df8750f987ca3851e7f6/retroarch.c#L2862

@twinaphex Any idea how to fix this one?

**Comment by fr500** [comment]
Weird, why is it hardcoded to that

**Comment by twinaphex** [comment]
There was a lot of complaints back then from various users that the 'input' was the same for both the cores and RetroArch's menu UI itself. So we tried to split up the controls that way. However, it has turned into a rather big mess to be honest.

That the menu toggle cannot be rebound right now is certainly not intentional and is definitely a bug.

I would wish we wouldn't need to have what is essentially a copy of the 'input pressed' function to begin with.

**Comment by twinaphex** [comment]
PRs are welcome for this one.

**Comment by AnotherLife** [comment]
I wish this really worked as a toggle ...

**Comment by bparker06** [comment]
This should be fixed now in the latest nightly.

**Comment by nothor** [comment]
Using the version 1.8.4, it's still not working properly.
When the option "All Users Control Menu" is activated then it's again not possible to turn back from the Menu with the controller, only with F1.

System Ubuntu 19.10, Controller Logitech F710 XInput.

**Comment by orbea** [comment]
@nother See https://github.com/libretro/RetroArch/issues/5127

**Comment by Roet-Ivar** [comment]
Version 1.8.6 still not working.
