### ISSUE TITLE
(Xbox One) loading savestates on retroarch for pcsx ReARMed Crashes

### ISSUE THREAD

**Issue by dominater01** [libretro/RetroArch#7965]
## Description

when i try to load a savestate it crashes back to the xbox one menu
it saves tho because i can load the state and it shows where i left off then it crashes

### Expected behavior

loadstates to work

### Actual behavior

crashes the emulator

### Steps to reproduce the bug

load a savestate from a psx game with this core

### Bisect Results

Idk

### Version/Commit

1.7.5

- RetroArch: [version/commit]

### Environment information

Xbox One

**Comment by orbea** [comment]
Is it only this one core or do other cores crash too? Does it happen on other platforms or only with xbox one?

**Comment by orbea** [comment]
I suspect its a core issue, can either of you get a backtrace with debugging symbols to confirm?

https://github.com/libretro/pcsx_rearmed/issues

**Comment by krzys-h** [comment]
```
warning: Unpaused.
warning: Saving state: "C:\Users\krzys\AppData\Local\Packages\1e4cf179-f3c2-404f-b9f3-cb2070a5aad8_t9k5fqjen2nz4\LocalState\states\Crash Bandicoot.state".
warning: State size: 4456448 bytes.
warning: State size: 4456448 bytes.
warning: File already exists. Saving to backup buffer ...
warning:
warning: Loading state: "C:\Users\krzys\AppData\Local\Packages\1e4cf179-f3c2-404f-b9f3-cb2070a5aad8_t9k5fqjen2nz4\LocalState\states\Crash Bandicoot.state".
warning: State size: 4456448 bytes.
[Thread 9380.0x1344 exited with code 0]
warning:
warning: Loading state: "C:\Users\krzys\AppData\Local\Packages\1e4cf179-f3c2-404f-b9f3-cb2070a5aad8_t9k5fqjen2nz4\LocalState\states\Crash Bandicoot.state".
warning: State size: 4456448 bytes.
warning: Saving state: "RAM".
warning: State size: 4456448 bytes.
warning: State size: 4456448 bytes.

Thread 8 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 9380.0x25bc]
0x000000000025c662 in decode_block (unused=0x0, ch=1, SB=0x1af7a522e10) at plugins/dfsound/spu.c:429
429      predict_nr = start[0];
(gdb) 
```

**Comment by orbea** [comment]
Its a potentially buggy core which was broken on windows entirely for a long time, I wouldn't be surprised if there are lingering issues. Can you provide a full backtrace?

**Comment by krzys-h** [comment]
```
Thread 8 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 15488.0x1c70]
0x000000000083c662 in decode_block (unused=0x0, ch=0, SB=0x2b8a5b210d0)
    at plugins/dfsound/spu.c:429
429      predict_nr = start[0];
(gdb) bt
#0  0x000000000083c662 in decode_block (unused=0x0, ch=0, SB=0x2b8a5b210d0) at plugins/dfsound/spu.c:429
#1  0x000000000083cd13 in do_samples_simple (decode_f=0x83c5b4 <decode_block>, ctx=0x0, ch=0, ns_to=736, SB=0x2b8a5b210d0, sinc=38968, spos=0x2b8a5b20964, sbpos=0x2b8a5b20960) at plugins/dfsound/spu.c:589
#2  0x000000000083d57c in do_channels (ns_to=736) at plugins/dfsound/spu.c:793
#3  0x000000000083da25 in do_samples (cycles_to=177199498, do_direct=1) at plugins/dfsound/spu.c:1155
#4  0x000000000083df01 in SPUasync (cycle=177199498, flags=1) at plugins/dfsound/spu.c:1256
#5  0x000000000081def7 in psxRcntUpdate () at libpcsxcore/psxcounters.c:340
#6  0x00000000008255cb in psxBranchTest () at libpcsxcore/r3000a.c:119
#7  0x0000000000821f18 in doBranch (tar=2147739232) at libpcsxcore/psxinterpreter.c:469
#8  0x000000000082345e in psxBNE () at libpcsxcore/psxinterpreter.c:615
#9  0x00000000008243b3 in execI () at libpcsxcore/psxinterpreter.c:942
#10 0x000000000082424f in intExecute () at libpcsxcore/psxinterpreter.c:916
#11 0x000000000086a4b8 in retro_run () at frontend/libretro.c:1780
#12 0x00007ff7e811f170 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by orbea** [comment]
It looks like its crashing entirely inside the core and since other cores are not affected it should be fixed inside the core.

Can you make a core issue?

**Comment by dominater01** [comment]
sorry guys i thought it was the xbox one version that was causing issues since thats where i tested it

i thought maybe something didnt have permission or something

in my mind i thought these issues were fixed on pc my bad

**Comment by krzys-h** [comment]
Well, it IS happening on the xbox version only, but it appears the fault is on the core side, not RetroArch side

**Comment by dominater01** [comment]
you guys want me to make a core issue on the core page then?

**Comment by orbea** [comment]
Could you please? Thanks!

**Comment by Ploggy** [comment]
Figured out a work-around for the Load State crash (on Xbox One at least)
You need to set the Save and State path in Retroarch to .\Savefile and .\Savestate ;) (create the folders there first tho of course) :) 
Looks like it crashes because it doesn't like the default path?

**Comment by dominater01** [comment]
then its not a core issue like i thought

**Comment by orbea** [comment]
It is a core issue since the other cores apparently do not have a problem with the default path.

**Comment by orbea** [comment]
What are the default paths for Xbox One? Maybe its reproducible on linux using the correct configuration?

**Comment by dominater01** [comment]
it says

for savefiles

U:\Users\UserMgr3\Appdata\Local\Packages\1e4cf179-f3c2-404f-b9f3-cb2070a5aad8_1.0.1.0_x64__t9k5fqjen2nz4\LocalState\saves

for savesates

U:\Users\UserMgr3\Appdata\Local\Packages\1e4cf179-f3c2-404f-b9f3-cb2070a5aad8_1.0.1.0_x64__t9k5fqjen2nz4\LocalState\states

**Comment by krzys-h** [comment]
Remember that `.\Savestates` is technically a read-only folder. It sometimes is not when deploying from Visual Studio, but you should really not depend on that.
Maybe the path is too long or something?

**Comment by orbea** [comment]
Does the directory actually exist?

**Comment by krzys-h** [comment]
@orbea The default works on other cores and is placed in a proper read-write directory. What they are saying is that if you put it in the normally-read-only-but-in-dev-mode-sometimes-writable directory and reference it using a path relative to the .exe, it works properly on pcsxe too...

**Comment by dominater01** [comment]
for the cores directory it shows

S:\Program Files\WindowsApps\1e4cf179-f3c2-404f-b9f3-cb2070a5aad8_1.0.1.0_x64__t9k5fqjen2nz4\cores

**Comment by dominater01** [comment]
i got a crash dump if you need it

**Comment by krzys-h** [comment]
@dominater01 I posted all of that already. Your info by itself is not useful since you don't have debugging symbols, and even if you did Visual Studio can't read mingw debugging data and pcsx doesn't buid on MSVC so you have to use gdb (and vice-versa, you can't debug RetroArch with gdb since the symbols are in the MSVC format)

**Comment by orbea** [comment]
@krzys-h So is it a problem with absolute vs relative paths?

**Comment by dominater01** [comment]
it shows paths for 

C:\

S:\

it doesnt show

U:\

**Comment by krzys-h** [comment]
Hard to say, I'll do some tests later to check

**Comment by dominater01** [comment]
this isnt a core issue it was a rights issue and is fixed but the new build hasnt been merged yet

**Comment by orbea** [comment]
What do you mean by "rights issue"? Where was this fixed?

Given this only happens with one core and is clearly crashing in the core, it still seems to be a core issue even if the bug can be masked by changes in the frontend.

**Comment by Ploggy** [comment]
@dominater01 it's still happening it's not a permission thing like we thought :/

**Comment by dominater01** [comment]
rights as in permission my bad

i could have sworn i fixed this by changing the savestate location, i will test soon

**Comment by orbea** [comment]
Going to close this since no one made a core issue...please continue this in the correct repo.
