### ISSUE TITLE
Using an overlay set to 100% covers RA OSD

### ISSUE THREAD

**Issue by Wilstorm** [libretro/RetroArch#7989]
## Description

When using overlays set to 100% opacity in mame2003-plus it covers the OSD. I was advised by @markwkidd to open an issue here from an [issue](https://github.com/libretro/mame2003-plus-libretro/issues/581) I opened on the mame2003-plus page. The OSD seems to sit above backdrops but below overlays.

### Expected behavior

To be able to see the OSD when loading/saving games, pausing or other informational messages from RA.

### Actual behavior

When using an overlay at 100% it completely covers the OSD and no messages are visible.

### Steps to reproduce the bug

1. Load an overlay into mame2003-plus
2. Make sure opacity is set to 100%
3. Load game

### Bisect Results

Unsure

### Version/Commit

mame2003-plus 8ff5a43

- RetroArch: [version/commit]

1.7.5

### Environment information

Running RetroPie 4.4.4 on a Raspberry Pi 3. Here's a pic of the overlay set to 50% to give you an idea what's happening. If set to 100% it's completely covered.

![si osd](https://user-images.githubusercontent.com/8192258/51063524-fdf35e80-15c0-11e9-81d0-8df2a30736cf.png)

**Comment by hhromic** [comment]
This happens in every core, not only in mame2003-plus. Also it happens in other platforms, not only on RPI.
OSD messages should always be rendered on top of everything else, including overlays, as they contain important system messages for the user.

**Comment by grant2258** [comment]
there is a notification background opacity setting in settings->onscreen display-> onscreen notifications

**Comment by Wilstorm** [comment]
@grant2258 - It's set to 1.00 and then rolls over to 0.00 but no change as it's set to max now at 1.00.

**Comment by hhromic** [comment]
@grant2258 the overlay is rendered on top of the OSD, so even if you set a message background the bezel/overlay still occludes it. The solution is to draw the OSD messages on top of everything else.

**Comment by orbea** [comment]
@Wilstorm Is this fixed by PR https://github.com/libretro/RetroArch/pull/8312?

**Comment by Wilstorm** [comment]
@orbea - Sorry for the late reply and thanks for the fix.

I am using RetroPie 4.4.8 and RetroArch to 1.7.6 (Git version 9750719) but I am still having the same issue after upgrading.

Something I noticed that I hadn't noticed before is when I enter RetroArch with the hotkey combo it actually "strips" away the overlay and you only see the game play area and backdrop.

It adds the overlay back over the top of the game play area and backdrop when you exit the RetroArch.
It might have always done that and I didn't notice from before the upgrading.

**Comment by orbea** [comment]
@Wilstorm I did not fix it and you will need to try a nightly version to see the fix or wait until the next release.

**Comment by hizzlekizzle** [comment]
I just verified that notifications are on top of the overlays with the GL driver in the latest commit. I'll go ahead and close this issue based on that, but @Wilstorm is welcome to reopen it if it's not resolved for them.

**Comment by Wilstorm** [comment]
@orbea - Ah ok but thanks for the update. :)

@hizzlekizzle - Thanks for testing and the update. Have a great weekend fellas!
