### ISSUE TITLE
Wrong quick menu after launching content from favorites

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#8389]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When toggling the quick menu after starting content from the `Favorites` playlist RetroArch will return the menu with `Run`, `Remove`, `Add to Favorites` and `Reset Core Association` instead of the `Quick Menu`.

### Expected behavior

Toggling the menu after launching content should always bring up the correct quick menu.

### Actual behavior

Toggling the menu after launching content from the `Favorites` playlist brings up the wrong menu.

### Steps to reproduce the bug

1. Add content to favorites.
2. Launch content from the `Favorites` playlist.
3. Toggle the quick menu.

### Bisect Results

```
e96b872693900776fc309093b514e9c187c85eb5 is the first bad commit
commit e96b872693900776fc309093b514e9c187c85eb5
Author: jdgleaver <james@leaver.myzen.co.uk>
Date:   Mon Feb 18 15:09:19 2019 +0000

    Make playlist sorting optional and consistent

:100644 100644 71efaaea98b2b2d4250a492c7e42c50d53ce3b1b dddd8f7cb43bab6054e059c78edb22310ffc8816 M	config.def.h
:100644 100644 f60752c5480e15d33da3bb02c6204836b5a5363f ade4d9280278fcf7feb13ef0fb70285ab21e87b6 M	configuration.c
:100644 100644 ed6561798b9366d3fc5accd47a0972cf8bde04ec 49748cc0c53f171360ae3b171236d00d1654a9d5 M	configuration.h
:040000 040000 4c57fb389a632e3c2b1d4f32d7d50e5185e86a1d aab3328c122e356bcb1731b3ac8ab06a4ca47468 M	intl
:040000 040000 5b38d23ac1de8ba5c981672f296133734d5cb0e0 4c41a49808d10941556f2840a6a873c950bcc1a6 M	menu
:100644 100644 f8b2dfa45f6b7821e951d6b064c8e7d0c38130b6 0956888179d1ac13d12f6dfceefcebb00ebd57cb M	msg_hash.h
```
e96b872693900776fc309093b514e9c187c85eb5 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/5e5c9e472905c547ed964f6fff57bfb402ffad85

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-8.3.0`

**Comment by orbea** [comment]
@jdgleaver Can you take a look at this? Also is it just me or is the playlist menu is not showing the playlist menu correctly? (Missing items and wrongly titled items)

**Comment by orbea** [comment]
I see, on RGUI the playlist names are being sorted, but the actual entries are not. On xmb they are not being sorted at all...

**Comment by jdgleaver** [comment]
@orbea Whoa, that's some bug...

I initially couldn't reproduce it at all - took me 20 minutes of messing about (I guess that's why I didn't notice it earlier...). But now I see what you mean.

It looks like enabling alphabetical sorting of the Favourites list has exposed some nastiness in the underlying code. I really don't have much time this weekend - I'll take another look this afternoon, but if I can't fix it quickly then I'll make a PR that temporarily disables Favourites sorting, and work out a proper solution next week.

**Comment by jdgleaver** [comment]
Oh for goodness sake...

This was getting tedious to try and test, since you can only add to favourites after loading a core.

So I fixed this (issue #6909), and now I cannot under any circumstances reproduce the error that you're seeing here.

This makes no sense at all.

I'm going to make a PR with the 'add to favourites' fix - once it's merged, could you please test the favourites playlist again? (because this is driving me crazy...)

**Comment by orbea** [comment]
I tried the current master (389138197b4be5be6d6a9d2d664f429817b0b3f6) and can still reproduce these issues.

1. Loading content from the favorites playlist brings up the wrong quick menu (Sometimes it works in rgui, but never in xmb).
2. In xmb when windowed the favorites playlist is invisible unless selecting content blindly and going back or toggling full screen. It seems related to the window size and the smaller the window the less that is visible.
3. In rgui its sorting the names in the favorites playlist, but its not sorting the actual entries, for example it displays `Chrono Trigger` as the first item and really plays `Sonic The Hedgehog 3`.
4. In xmb its not actually sorting anything.

Do you have a fix for https://github.com/libretro/RetroArch/issues/6909? :)

**Comment by orbea** [comment]
@jdgleaver You may need to go back before the json playlists and create a favorites playlist to reproduce some of these issues, with a fresh favorites playlist I can no longer reproduce issues `2` and `4` as well as exposing `3` for xmb. Additionally I am now experiencing a new issue.

5. In xmb it doesn't sort the playlist until actually navigating inside the playlist.

**Comment by orbea** [comment]
I tested it more and I think I understand the issues better.

For `1`, `3` and `5` these occur when a playlist file exists that is not correctly ordered. When making a new playlist it adds items in the correct order so this is not a problem.

With `2` and `4`this seems to occur when people have older favorites playlists using the old format.

**Comment by jdgleaver** [comment]
@orbea Ah, cool, glad you worked out what's going on.

We should be able to handle corrupted playlists without issue though (i.e. fallback gracefully) - I'll have a look and see if I can do anything about this...

**Comment by orbea** [comment]
Fixed in https://github.com/libretro/RetroArch/pull/8414.
