### ISSUE TITLE
[Android] Notification (widgets) behind overlay

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9119]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The notification popups (such as controller configured etc) pop up behind overlays.  This was the case with the windows client as well and was recently fixed.  Unsure if it just hasnt made it to the android port yet, or you guys are unaware - so i figured id flap my gums s'more. 

### Expected behavior

The notifications to be on top of the overlay so you can actually see them :)

### Actual behavior

the yellow notifications such as those that declare overrides being loaded, do show on top of overlays.  however the native blue/greenish ones, are unfortunately hidden behind overlays/borders. 

### Steps to reproduce the bug

1. load an overlay or border/bezel etc.
2. load a game with a controller connected
3. observe the popup being obstructed by said overlay and use elite coding skills to fix. 

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: May 8 2019 - 8c17f12

### Environment information

- OS: Android (Shield TV)

**Comment by klepp0906** [comment]
This is happening on windows too.  Thought it was android only as it was fixed on windows last i checked.  But also happening on windows.

**Comment by Khaine17** [comment]
Any chance of this being resolved? Confirmed that this is still an issue in current version of RetroArch for Windows.

**Comment by LibretroAdmin** [comment]
There is now a setting that deals with this - 'Show Overlay Behind Menu'. This works well ingame, although inside the menu it might be undesirable because the overlay is literally behind the menu then, and it's a bit too non visible with the default opacity setting.
